### PR TITLE
Fix an infinite loop in the WebP fallback mechanism

### LINKED ISSUE #432: Infinite loop in the fallback mechanism
## Bug Description

This bug is introduced after merg of the PR #360, When I open any page with an image with the webp version, that page never stops loading.

## Steps to reproduce

1. Clone trunk copy
2. Upload image in post/page
3. Check frontend page
4. See error. The page never stops loading.

## Additional Context

 - PHP Version: 8.0.15
 - OS: Windows, Mac
 - Browser: chrome, edge
 - Plugin Version: trunk
 - Device: desktop

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
## Summary

Fixes #432

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

File: modules/images/webp-uploads/load.php [hunk 1]
```diff
@@ -663,9 +663,9 @@ function webp_uploads_wepb_fallback() {
 
 		i = d.createElement( i );
 		i.src = p + 'jIAAABXRUJQVlA4ICYAAACyAgCdASoCAAEALmk0mk0iIiIiIgBoSygABc6zbAAA/v56QAAAAA==';
-		i.onload = function() {
+		i.addEventListener( 'load', function() {
 			i.src = p + 'h4AAABXRUJQVlA4TBEAAAAvAQAAAAfQ//73v/+BiOh/AAA=';
-		};
+		}, { once: true } );
```
Comment (eugene-manuilov) [inline modules/images/webp-uploads/load.php]: This will not work in older browsers, I have created another PR that fixes this problem: #434. @mukeshpanchal27 could you please revert your changes and just use the same approach as in my PR? I'll close my PR as duplicate for this one.

**Review by eugene-manuilov — CHANGES_REQUESTED** [review]

**Review by jjgrainger — APPROVED** [review]
Good spot on the issue and fix

File: modules/images/webp-uploads/load.php (hunk 1 above)
Comment (mukeshpanchal27) [reply modules/images/webp-uploads/load.php]: Thank you! PR updated with changes

**Review by eugene-manuilov — APPROVED** [review]
LGTM

**Review by mehulkaklotar — APPROVED** [review]
LGTM 🚀

**Review by mitogh — APPROVED** [review]

**Review by felixarntz — APPROVED** [review]
Great catch @mukeshpanchal27, and thank you for the quick fix!

This will need to go into the 1.3.0 release of course since it is critical, so I'll change the base branch accordingly.
