### PR TITLE
Don't wrap PICTURE element if JPEG fallback is not available

### LINKED ISSUE #1447: Enabling picture element after having uploaded images while JPEG fallbacks were disabled results in invalid markup
_Originally posted in https://github.com/WordPress/performance/issues/1439#issuecomment-2271472822_

When images are uploaded while "Also output JPEG" is turned off, when that setting and the picture element are later enabled, the result is incorrectly that both the `PICTURE > SOURCE` and `PICTURE > IMG` are serving JPEG. When JPEG is not available, a `PICTURE` should not be served at all since our purpose for `PICTURE` is exclusively to serve a modern image format with a JPEG fallback.

Steps to reproduce this issue:

1. Activate the plugin
2. Leave the "Also output JPEG" option disabled
3. Upload a few JPEG images
4. Insert these images as a large size in Image blocks
5. Enable "Also output JPEG" and the "Picture element" options

Bug: Go to the frontend and see that it is generating the wrong markup with the `IMG` being the modern format, not the JPEG fallback:

```html
<picture class="not-transparent wp-picture-99" style="--dominant-color: #828ca3; display: contents;">
    <source type="image/webp" srcset="http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-828x1024.webp 828w, http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-242x300.webp 242w, http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-768x950.webp 768w" sizes="(max-width: 650px) 100vw, 650px">
    <img data-has-transparency="false" decoding="async" width="828" height="1024" src="http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-828x1024.webp" alt="" class="not-transparent wp-image-99" srcset="http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-828x1024.webp 828w, http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-242x300.webp 242w, http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-768x950.webp 768w, http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-1241x1536.webp 1241w, http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-1655x2048.webp 1655w" sizes="(max-width: 650px) 100vw, 650px">
</picture>
```

The problem here is that there was no JPEG fallback available for this image, so it should be ineligible for the picture element. It should instead be generating:

```html
<img data-has-transparency="false" decoding="async" width="828" height="1024" src="http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-828x1024.webp" alt="" class="not-transparent wp-image-99" srcset="http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-828x1024.webp 828w, http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-242x300.webp 242w, http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-768x950.webp 768w, http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-1241x1536.webp 1241w, http://localhost:8888/wp-content/uploads/2024/08/Spectacled_weaver_Ploceus_ocularis_ocularis_male_Mbombela-1655x2048.webp 1655w" sizes="(max-width: 650px) 100vw, 650px">
```

In contrast, if I upload another image after I have the "Also output JPEG" and the "Picture element" settings enabled, then I see what is expected:

```html
<picture class="not-transparent wp-picture-102" style="--dominant-color: #62759f; display: contents;">
    <source type="image/webp" srcset="http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-1024x588-jpg.webp 1024w, http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-300x172-jpg.webp 300w, http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-768x441-jpg.webp 768w" sizes="(max-width: 650px) 100vw, 650px">
    <source type="image/jpeg" srcset="http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-1024x588.jpg 1024w, http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-300x172.jpg 300w, http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-768x441.jpg 768w" sizes="(max-width: 650px) 100vw, 650px">
    <img data-dominant-color="62759f" data-has-transparency="false" decoding="async" width="1024" height="588" src="http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-1024x588-jpg.webp" alt="" class="not-transparent wp-image-102" srcset="http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-1024x588-jpg.webp 1024w, http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-300x172-jpg.webp 300w, http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-768x441-jpg.webp 768w, http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-1536x882.jpg 1536w, http://localhost:8888/wp-content/uploads/2024/08/Samango_monkey_Cercopithecus_mitis_erythrarchus_Mount_Sheba-2048x1176.jpg 2048w" sizes="(max-width: 650px) 100vw, 650px">
</picture>
```

There should be some message shown with the Picture element setting to say something like:

> Picture elements will only be used when JPEG fallback images are available. So any images you have uploaded while the "Also generate JPEG" setting was disabled won't get served in any picture elements.

### PR DESCRIPTION
**Pull request by sagarnasit**
## Summary

This PR accounts following:

- Skip wrapping the image in the picture element if the jpeg fallback is not available.

Fixes #1447

### CODE REVIEW

File: plugins/webp-uploads/picture-element.php [hunk 1]
```diff
@@ -75,6 +75,11 @@ function webp_uploads_wrap_image_in_picture( string $image, string $context, int
 		return $image;
 	}
 
+	// If jpeg fallback is not available, don't wrap in picture element.
+	if ( ! in_array( 'image/jpeg', $mime_types, true ) ) {
```
Comment (adamsilverstein) [inline plugins/webp-uploads/picture-element.php]:
```suggestion
	if ( ! in_array( $original_file_mime_type, $mime_types, true ) ) {
```
If we use the original upload mime type here, this will continue to work when we add handling for PNG uploads in https://github.com/WordPress/performance/pull/1421

Comment (sagarnasit) [reply plugins/webp-uploads/picture-element.php]: @adamsilverstein I have updated the check with the original mime type. Thank you for the suggestion.

File: plugins/webp-uploads/settings.php [hunk 2]
```diff
@@ -214,7 +215,15 @@ function webp_uploads_use_picture_element_callback(): void {
 			<em><?php esc_html_e( '(experimental)', 'webp-uploads' ); ?></em>
 		</label>
 		<p class="description" id="webp_uploads_use_picture_element_description"><?php esc_html_e( 'The picture element serves a modern image format with a fallback to JPEG. Warning: Make sure you test your theme and plugins for compatibility. In particular, CSS selectors will not match images when using the child combinator (e.g. figure > img).', 'webp-uploads' ); ?></p>
+		<div id="webp_uploads_jpeg_fallback_notice" class="notice notice-info inline" <?php echo $picture_element_enabled ? '' : 'hidden'; ?>>
+			<p><?php esc_html_e( 'Picture elements will only be used when JPEG fallback images are available. So any images you have uploaded while the "Also generate JPEG" setting was disabled won\'t get served in any picture elements.', 'webp-uploads' ); ?></p>
+		</div>
 	</div>
+	<script>
+		document.getElementById( 'webp_uploads_use_picture_element' ).addEventListener( 'change', function () {
+			document.getElementById( 'webp_uploads_jpeg_fallback_notice' ).hidden = !this.checked;
```
Comment (westonruter) [inline plugins/webp-uploads/settings.php]: Micro nit:

```suggestion
			document.getElementById( 'webp_uploads_jpeg_fallback_notice' ).hidden = ! this.checked;
```

File: plugins/webp-uploads/settings.php [hunk 3]
```diff
@@ -214,7 +215,15 @@ function webp_uploads_use_picture_element_callback(): void {
 			<em><?php esc_html_e( '(experimental)', 'webp-uploads' ); ?></em>
 		</label>
 		<p class="description" id="webp_uploads_use_picture_element_description"><?php esc_html_e( 'The picture element serves a modern image format with a fallback to JPEG. Warning: Make sure you test your theme and plugins for compatibility. In particular, CSS selectors will not match images when using the child combinator (e.g. figure > img).', 'webp-uploads' ); ?></p>
+		<div id="webp_uploads_jpeg_fallback_notice" class="notice notice-info inline" <?php echo $picture_element_enabled ? '' : 'hidden'; ?>>
+			<p><?php esc_html_e( 'Picture elements will only be used when JPEG fallback images are available. So any images you have uploaded while the "Also generate JPEG" setting was disabled won\'t get served in any picture elements.', 'webp-uploads' ); ?></p>
```
Comment (westonruter) [inline plugins/webp-uploads/settings.php]:
```suggestion
			<p><?php esc_html_e( 'Picture elements will only be used when JPEG fallback images are available. So this will not apply to any images you uploaded while the "Also generate JPEG" setting was disabled.', 'webp-uploads' ); ?></p>
```

**Review by westonruter — COMMENTED** [review]
Looking good! Just a couple tweaks, and then it seems the only thing left is to add a test.

**Comment by sagarnasit** [comment]
@westonruter I updated the check for `$original_file_mime_type` with `$sub_size_mime_types` and made other changes as per your suggestions.

Additionally, I've included a separate test file for the fallback image as the "Output JPEG" setting needs to be disabled initially, which is not viable in the [existing test file](https://github.com/wordpress/performance/blob/trunk/plugins/webp-uploads/tests/test-picture-element.php#L47).

File: plugins/webp-uploads/tests/test-picture-element-original-fallback.php [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+
+		// Run critical hooks to satisfy webp_uploads_in_frontend_body() conditions.
+		$this->mock_frontend_body_hooks();
+	}
+
+	/**
+	 * Setup shared fixtures.
+	 */
+	public static function wpSetUpBeforeClass( WP_UnitTest_Factory $factory ): void {
+		// Fallback to JPEG IMG.
```
Comment (mukeshpanchal27) [inline plugins/webp-uploads/tests/test-picture-element-original-fallback.php]:
```suggestion
		// Disable Fallback to JPEG IMG.
```

File: plugins/webp-uploads/tests/test-picture-element-original-fallback.php [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+		update_option( 'perflab_generate_webp_and_jpeg', '0' );
+
+		self::$image_id = $factory->attachment->create_upload_object( TESTS_PLUGIN_DIR . '/tests/data/images/leaves.jpg' );
+	}
+
+	public static function wpTearDownAfterClass(): void {
+		wp_delete_attachment( self::$image_id, true );
+
+		delete_option( 'perflab_generate_webp_and_jpeg' );
```
Comment (mukeshpanchal27) [inline plugins/webp-uploads/tests/test-picture-element-original-fallback.php]:
```suggestion
		wp_delete_attachment( self::$image_id, true );
		delete_option( 'perflab_generate_webp_and_jpeg' );
```

File: plugins/webp-uploads/tests/test-picture-element-original-fallback.php [hunk 6]
```diff
@@ -0,0 +1,97 @@
...
+	}
+
+	/**
+	 * Test that the picture element is not applied when the original fallback image is not available.
+	 */
+	public function test_no_picture_tag_wrap_and_original_image_fallback(): void {
+		update_option( 'perflab_generate_webp_and_jpeg', '1' );
+
```
Comment (mukeshpanchal27) [inline plugins/webp-uploads/tests/test-picture-element-original-fallback.php]:
```suggestion
```

There is no effect of this code.

File: plugins/webp-uploads/tests/test-picture-element-original-fallback.php [hunk 7]
```diff
@@ -0,0 +1,97 @@
...
+		$picture_processor = new WP_HTML_Tag_Processor( $image_markup );
+
+		$picture_processor->next_tag( array( 'tag_name' => 'IMG' ) );
+		// Fallback image should not be available.
+		$this->assertStringEndsWith( '.webp', $picture_processor->get_attribute( 'src' ), 'Make sure the IMG should return WEBP src.' );
+		$this->assertStringContainsString( '.webp', $picture_processor->get_attribute( 'srcset' ), 'Make sure the IMG srcset should return WEBP images.' );
+
+		$picture_processor = new WP_HTML_Tag_Processor( $image_markup );
+		$picture_processor = $picture_processor->next_tag( array( 'tag_name' => 'picture' ) );
+		$this->assertFalse( $picture_processor, 'There should not be a PICTURE tag.' );
```
Comment (mukeshpanchal27) [inline plugins/webp-uploads/tests/test-picture-element-original-fallback.php]:
```suggestion
		$img_markup = apply_filters( 'the_content', $image );
		$img_processor = new WP_HTML_Tag_Processor( $img_markup );
		$this->assertTrue( $img_processor->next_tag( array( 'tag_name' => 'IMG' ) ), 'There should be an IMG tag.' );
		$this->assertStringEndsWith( '.webp', $img_processor->get_attribute( 'src' ), 'Make sure the IMG should return WEBP src.' );

		// Apply picture element support.
		$this->opt_in_to_picture_element();

		$picture_markup    = apply_filters( 'the_content', $image );
		$picture_processor = new WP_HTML_Tag_Processor( $picture_markup );
		$this->assertFalse( $picture_processor->next_tag( array( 'tag_name' => 'picture' ) ), 'There should not be a PICTURE tag.' );

		$picture_processor = new WP_HTML_Tag_Processor( $picture_markup );
		$picture_processor->next_tag( array( 'tag_name' => 'IMG' ) );
		$this->assertStringEndsWith( '.webp', $picture_processor->get_attribute( 'src' ), 'Make sure the IMG should return WEBP src.' );
		$this->assertSame( $img_markup, $picture_markup, 'Make sure the IMG and Picture markup are same.' );
```

- Use proper variable names
- Remove `srcset` related asserts.
- Add assert that check both markup. It should be same.

File: plugins/webp-uploads/settings.php [hunk 8]
```diff
@@ -214,7 +215,15 @@ function webp_uploads_use_picture_element_callback(): void {
 			<em><?php esc_html_e( '(experimental)', 'webp-uploads' ); ?></em>
 		</label>
 		<p class="description" id="webp_uploads_use_picture_element_description"><?php esc_html_e( 'The picture element serves a modern image format with a fallback to JPEG. Warning: Make sure you test your theme and plugins for compatibility. In particular, CSS selectors will not match images when using the child combinator (e.g. figure > img).', 'webp-uploads' ); ?></p>
+		<div id="webp_uploads_jpeg_fallback_notice" class="notice notice-info inline" <?php echo $picture_element_enabled ? '' : 'hidden'; ?>>
+			<p><?php esc_html_e( 'Picture elements will only be used when JPEG fallback images are available. So this will not apply to any images you uploaded while the "Also generate JPEG" setting was disabled.', 'webp-uploads' ); ?></p>
```
Comment (westonruter) [inline plugins/webp-uploads/settings.php]: Another slight copy improvement:

```suggestion
			<p><?php esc_html_e( 'Picture elements will only be used when JPEG fallback images are available. So this will not apply to any images you may have uploaded while the "Also generate JPEG" setting was disabled.', 'webp-uploads' ); ?></p>
```

**Comment by mukeshpanchal27** [comment]
@sagarnasit Have you replicate https://github.com/WordPress/performance/actions/runs/10364966081/job/28691196072?pr=1450#step:9:290 unit test failed in PHP 8.3 in your local? I didn't replicate it 🤔 

Screenshot 2024-08-13 at 3 32 40 PM

**Comment by sagarnasit** [comment]
@mukeshpanchal27 The issue is not with PHP 8.3 but with the WordPress trunk. I tried to load the WordPress trunk on a local setup and was able to replicate the issue with the following.

```
WP_ENV_CORE=WordPress/WordPress WP_ENV_PHP_VERSION=8.3 npx wp-env start
```

I also attempted to debug further, but I was unsuccessful in finding out why `next_tag` is returning true even if there is no PICTURE tag in the markup.

**Comment by westonruter** [comment]
Probably a regression in the HTML Tag Processor in WP Core `trunk` since a lot has been going into that lately. We should do a git bisect on `trunk` to pinpoint the problematic commit.

**Comment by westonruter** [comment]
Doing so now...

**Comment by westonruter** [comment]
OK, I found that the regression was introduced in r58613 (in WordPress/WordPress this is commit [`df598e1d9`](https://github.com/WordPress/WordPress/commit/df598e1d9)). If I check out the parent commit, then I get no failure here.

**Comment by westonruter** [comment]
For reference, the unit test assertion is failing here:

https://github.com/WordPress/performance/blob/da7d55ff9dde24657f22aa8a306f196363834068/plugins/webp-uploads/tests/test-picture-element-original-fallback.php#L79-L80

The markup contained in `$picture_markup` is the following:

```html
<p><img width="1024" height="683" src="http://localhost:8889/wp-content/uploads/2024/08/leaves-232-1024x683.webp" class="wp-image-9" alt="Green Leaves" decoding="async" loading="lazy" srcset="http://localhost:8889/wp-content/uploads/2024/08/leaves-232-1024x683.webp 1024w, http://localhost:8889/wp-content/uploads/2024/08/leaves-232-300x200.webp 300w, http://localhost:8889/wp-content/uploads/2024/08/leaves-232-768x512.webp 768w, http://localhost:8889/wp-content/uploads/2024/08/leaves-232-jpg.webp 1080w" sizes="(max-width: 1024px) 100vw, 1024px" /></p>
```

With formatting:

```html
<p>
  <img
    width="1024"
    height="683"
    src="http://localhost:8889/wp-content/uploads/2024/08/leaves-232-1024x683.webp"
    class="wp-image-9"
    alt="Green Leaves"
    decoding="async"
    loading="lazy"
    srcset="
      http://localhost:8889/wp-content/uploads/2024/08/leaves-232-1024x683.webp 1024w,
      http://localhost:8889/wp-content/uploads/2024/08/leaves-232-300x200.webp   300w,
      http://localhost:8889/wp-content/uploads/2024/08/leaves-232-768x512.webp   768w,
      http://localhost:8889/wp-content/uploads/2024/08/leaves-232-jpg.webp      1080w
    "
    sizes="(max-width: 1024px) 100vw, 1024px"
  />
</p>
```

There is definitely no `PICTURE` tag here. 

And yet, for some reason, `$picture_processor->next_tag( array( 'tag_name' => 'picture' ) )` is returning `true`.

**Comment by mukeshpanchal27** [comment]
It's WP Trunk error not related to PHP version. I have open https://github.com/WordPress/wordpress-develop/pull/7185 to verify that.

**Comment by westonruter** [comment]
Given this code:

```php
$picture_markup = '<p><img width="1024" height="683" src="http://localhost:8889/wp-content/uploads/2024/08/leaves-232-1024x683.webp" class="wp-image-9" alt="Green Leaves" decoding="async" loading="lazy" srcset="http://localhost:8889/wp-content/uploads/2024/08/leaves-232-1024x683.webp 1024w, http://localhost:8889/wp-content/uploads/2024/08/leaves-232-300x200.webp 300w, http://localhost:8889/wp-content/uploads/2024/08/leaves-232-768x512.webp 768w, http://localhost:8889/wp-content/uploads/2024/08/leaves-232-jpg.webp 1080w" sizes="(max-width: 1024px) 100vw, 1024px" /></p>';
$picture_processor = new WP_HTML_Tag_Processor( $picture_markup );
var_dump( $picture_processor->next_tag( array( 'tag_name' => 'picture' ) ) );
var_dump( $picture_processor->get_tag() );
```

It outputs:

```
bool(true)
string(1) "P"
```

If I remove the `<p>` from the markup, then I get:

```
bool(false)
NULL
```

So it seems that the Tag Processor is only looking at the first character of the tag name now, which is a bug. 

Quick workaround to get the tests to pass: remove the `<p>` tag.

**Comment by westonruter** [comment]
Reported upstream: https://core.trac.wordpress.org/ticket/61545#comment:6

File: plugins/webp-uploads/tests/test-picture-element-original-fallback.php [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+
+		$img_markup    = apply_filters( 'the_content', $image );
+		$img_processor = new WP_HTML_Tag_Processor( $img_markup );
+		$this->assertTrue( $img_processor->next_tag( array( 'tag_name' => 'IMG' ) ), 'There should be an IMG tag.' );
+		$this->assertStringEndsWith( '.webp', $img_processor->get_attribute( 'src' ), 'Make sure the IMG should return WEBP src.' );
+		// Apply picture element support.
+		$this->opt_in_to_picture_element();
+		$picture_markup    = apply_filters( 'the_content', $image );
+		$picture_processor = new WP_HTML_Tag_Processor( $picture_markup );
+		$this->assertFalse( $picture_processor->next_tag( array( 'tag_name' => 'picture' ) ), 'There should not be a PICTURE tag.' );
```
Comment (mukeshpanchal27) [inline plugins/webp-uploads/tests/test-picture-element-original-fallback.php]:
```suggestion
```

To unblock WP TRUNK error: Let's remove this PICTURE tag check as we already have `$this->assertSame( $img_markup, $picture_markup, 'Make sure the IMG and Picture markup are same.' );` that check both markups.

**Comment by westonruter** [comment]
✅ Behavior looks good.

Before:

```html
<picture
  class="not-transparent wp-picture-155"
  style="--dominant-color: #594e4a; display: contents"
  ><source
    type="image/webp"
    srcset="
      http://localhost:8888/wp-content/uploads/2024/08/image-1-jpeg.webp     1300w,
      http://localhost:8888/wp-content/uploads/2024/08/image-1-300x201.webp   300w,
      http://localhost:8888/wp-content/uploads/2024/08/image-1-1024x688.webp 1024w,
      http://localhost:8888/wp-content/uploads/2024/08/image-1-768x516.webp   768w
    "
    sizes="(max-width: 650px) 100vw, 650px" />
  <img
    data-dominant-color="594e4a"
    data-has-transparency="false"
    decoding="async"
    width="1300"
    height="873"
    src="http://localhost:8888/wp-content/uploads/2024/08/image-1-jpeg.webp"
    alt=""
    class="not-transparent wp-image-155"
    srcset="
      http://localhost:8888/wp-content/uploads/2024/08/image-1-jpeg.webp     1300w,
      http://localhost:8888/wp-content/uploads/2024/08/image-1-300x201.webp   300w,
      http://localhost:8888/wp-content/uploads/2024/08/image-1-1024x688.webp 1024w,
      http://localhost:8888/wp-content/uploads/2024/08/image-1-768x516.webp   768w
    "
    sizes="(max-width: 650px) 100vw, 650px"
/></picture>
```

After:

```html
<img
  data-dominant-color="594e4a"
  data-has-transparency="false"
  style="--dominant-color: #594e4a"
  decoding="async"
  width="1300"
  height="873"
  src="http://localhost:8888/wp-content/uploads/2024/08/image-1-jpeg.webp"
  alt=""
  class="not-transparent wp-image-155"
  srcset="
    http://localhost:8888/wp-content/uploads/2024/08/image-1-jpeg.webp     1300w,
    http://localhost:8888/wp-content/uploads/2024/08/image-1-300x201.webp   300w,
    http://localhost:8888/wp-content/uploads/2024/08/image-1-1024x688.webp 1024w,
    http://localhost:8888/wp-content/uploads/2024/08/image-1-768x516.webp   768w
  "
  sizes="(max-width: 650px) 100vw, 650px"
/>
```

----

Settings screen:

image

**Review by westonruter — APPROVED** [review]

**Review by mukeshpanchal27 — APPROVED** [review]

**Comment by mukeshpanchal27** [comment]
https://github.com/WordPress/performance/pull/1450#issuecomment-2286319675 the core issue is fixed now in https://core.trac.wordpress.org/changeset/58893
