### PR TITLE
Fix URL encoding in Link HTTP response header

### LINKED ISSUE #1906: Preload links for image URLs containing commas can be erroneously percent-encoded
## Bug Description

On my site I'm using the Jetpack Image CDN (Photon). The LCP `IMG` element on the homepage is rendered by WordPress as:

```html
<img
  width="1200"
  height="675"
  src="https://weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond-1200x675.png"
  class="attachment-post-thumbnail size-post-thumbnail wp-post-image"
  alt="Boosting Performance with Optimization Detective"
  style="width: 100%; height: 100%; object-fit: cover"
  decoding="async"
  fetchpriority="high"
  srcset="
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1200%2C675&amp;ssl=1  1200w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=300%2C169&amp;ssl=1    300w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=700%2C394&amp;ssl=1    700w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=768%2C432&amp;ssl=1    768w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1536%2C864&amp;ssl=1  1536w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=2048%2C1152&amp;ssl=1 2048w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1980%2C1114&amp;ssl=1 1980w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=150%2C84&amp;ssl=1     150w
  "
  sizes="(max-width: 1200px) 100vw, 1200px"
/>
```

When Optimization Detective with Image Prioritizer runs, it identifies that this is the LCP element and it adds a preload link with `fetchpriority=high`, as expected:

```html
<link
  data-od-added-tag
  rel="preload"
  fetchpriority="high"
  as="image"
  href="https://weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond-1200x675.png"
  imagesrcset="https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1200%2C675&amp;ssl=1 1200w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=300%2C169&amp;ssl=1 300w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=700%2C394&amp;ssl=1 700w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=768%2C432&amp;ssl=1 768w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1536%2C864&amp;ssl=1 1536w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=2048%2C1152&amp;ssl=1 2048w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1980%2C1114&amp;ssl=1 1980w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=150%2C84&amp;ssl=1 150w"
  imagesizes="(width &lt;= 480px) 300px, (480px &lt; width &lt;= 600px) 455px, (600px &lt; width &lt;= 782px) 644px, (782px &lt; width) 645px"
  media="screen"
/>
```

Nevertheless, when I look at the Chrome DevTools console I see an unexpected warning:

> [!WARNING]
> The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally. The resource https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=768,432&ssl=1 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

When I look at the network panel I see that there are _two_ copies of this image being loaded:

Image

One of the URLs is getting the comma percent-encoded (the one in the `LINK` tag) and Chrome isn't understanding the URLs are the same. This seems like a bug in Chromium because these two URLs should be normalized to be the same, I should think:

* https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=768,432&ssl=1
* https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=768%2C432&ssl=1

In any case, the problem is that there is a percent-encoding which was originally present in the URL which was stripped out:

https://github.com/WordPress/performance/blob/db322a37e675aeea54db7afba8a31ac0c40e6393/plugins/optimization-detective/class-od-link-collection.php#L331-L343

This originates in https://github.com/WordPress/performance/pull/1802 and https://github.com/WordPress/performance/pull/1866.

The issue is not limited to percent encodings in the query parameters either. If I try to percent-encode the "j" in the `.jpg` file extension as `.%6Apg`, I get the same issue. _However_, if I add a query parameter with percent-encoding for text which _must_ be percent-encoded (e.g. Arabic text), then I do _not_ experience this issue. For example:

```html
<figure>
  <img
    src="https://upload.wikimedia.org/wikipedia/commons/8/8d/American_bison_k5680-1.jpg?arabic=%D8%A7%D9%84%D8%A8%D9%8A%D8%B3%D9%88%D9%86&hebrew=חנות"
    alt="Bison"
    style="max-width: 100%; height: auto; aspect-ratio: 1270 / 828"
  />
</figure>
```

Results in this `LINK` tag:

```html
<figure>
  <img
    src="https://upload.wikimedia.org/wikipedia/commons/8/8d/American_bison_k5680-1.jpg?arabic=%D8%A7%D9%84%D8%A8%D9%8A%D8%B3%D9%88%D9%86&hebrew=חנות"
    alt="Bison"
    style="max-width: 100%; height: auto; aspect-ratio: 1270 / 828"
  />
</figure>
```

And this HTTP `Link` response header:

```http
Link: <https://upload.wikimedia.org/wikipedia/commons/8/8d/American_bison_k5680-1.jpg?arabic=%D8%A7%D9%84%D8%A8%D9%8A%D8%B3%D9%88%D9%86&hebrew=%D7%97%D7%A0%D7%95%D7%AA>; rel="preload"; fetchpriority="high"; as="image"; media="screen and (782px < width)"
```

Nevertheless, only entry URL shows up in the Network log:

Image

So it appears that we need to (1) stop doing `urldecode()` and then (2) only encode the characters that must be encoded (while leaving any percent encodings in the URL intact).

## Steps to reproduce

0. Activate the Image Prioritizer plugin.
1. Add a Custom HTML block with the following contents:

```html
<figure>
  <img
    src="https://upload.wikimedia.org/wikipedia/commons/8/8d/American_bison_k5680-1.%6Apg?foo=bar%2Cbaz"
    alt="Bison"
    style="max-width: 100%; height: auto; aspect-ratio: 1270 / 828"
  />
</figure>
```

2. Visit the frontend to trigger URL Metric collection.
3. Reload the page in which a preload link has been added.
4. Look at Network panel to see two almost-identical image URLs being loaded with high priority, when there should only be one.

### PR DESCRIPTION
**Pull request by ShyamGadde**
## Summary

Fixes #1906 

## Relevant technical choices

- Removed `urldecode()` to prevent double encoding.
- Adjusted regex in `encode_url_for_response_header()` to preserve existing percent-encoded sequences while properly encoding invalid characters.

### CODE REVIEW

File: plugins/optimization-detective/tests/test-class-od-link-collection.php [hunk 1]
```diff
@@ -489,7 +489,7 @@ public function data_provider_to_test_add_link(): array {
 				'expected_html'   => '
 					<link data-od-added-tag rel="preload" href="https://example.com/חנות/wp-content/uploads/2025/01/example.jpg?ver=1+2" as="image">
 				',
-				'expected_header' => 'Link: <https://example.com/%D7%97%D7%A0%D7%95%D7%AA/wp-content/uploads/2025/01/example.jpg?ver=1%202>; rel="preload"; as="image"',
+				'expected_header' => 'Link: <https://example.com/%D7%97%D7%A0%D7%95%D7%AA/wp-content/uploads/2025/01/example.jpg?ver=1+2>; rel="preload"; as="image"',
```
Comment (westonruter) [inline plugins/optimization-detective/tests/test-class-od-link-collection.php:492]: Could you add test cases for the example URLs I have in the issue description as well?

Comment (ShyamGadde) [reply plugins/optimization-detective/tests/test-class-od-link-collection.php:492]: Done in 20a03ca.

File: plugins/optimization-detective/class-od-link-collection.php [hunk 2]
```diff
@@ -325,19 +325,17 @@ function ( $image_candidate ) {
...
+	 * @param string $url URL to percent encode.
 	 * @return string Percent-encoded URL.
 	 */
 	private function encode_url_for_response_header( string $url ): string {
-		$decoded_url = urldecode( $url );
-
 		// Encode characters not allowed in a URL per RFC 3986 (anything that is not among the reserved and unreserved characters).
 		$encoded_url = (string) preg_replace_callback(
-			'/[^A-Za-z0-9\-._~:\/?#\[\]@!$&\'()*+,;=]/',
+			'/[^A-Za-z0-9\-._~:\/?#\[\]@!$&\'()*+,;=%]/',
```
Comment (westonruter) [inline plugins/optimization-detective/class-od-link-collection.php:334]: One thing that comes to mind. What if someone has a URL like: `https://example.com/price.jpg?amount=100%-free`. What happens here? Will browsers force that `%` to get encoded as if they encountered non-ASCII characters?

Comment (ShyamGadde) [reply plugins/optimization-detective/class-od-link-collection.php:334]: After looking into how WordPress handles standalone `%` characters in URLs via `esc_url_raw()`, I found that:

1. WordPress allows standalone `%` characters in URLs since they are part of the allowed character set.
2. It only strips truly invalid characters, not malformed percent encodings.

Additionally, modern browsers (tested on Edge, Chrome, and Firefox) accept URLs with standalone `%` characters. For example, given a URL like `https://example.com/price.jpg?amount=100%-free`:
- Both browsers and WordPress preserve the standalone `%`.
- The image loads correctly without errors.
- The URL is not rejected as invalid.

I considered encoding standalone `%` with something like:
```php
preg_replace_callback(
    '/%(?![0-9A-Fa-f]{2})/',
    static function () {
        return '%25';
    },
    $url
);
```

However, this would create inconsistency between how the URL appears in HTML vs. HTTP headers, potentially causing the same double-request issue we're trying to fix.

Comment (westonruter) [reply plugins/optimization-detective/class-od-link-collection.php:334]: I can confirm that in `trunk` right now, a bare `%` is resulting in the incorrect behavior where the `%` is getting percent-encoded:

image

> [!WARNING]
> The resource https://upload.wikimedia.org/wikipedia/commons/8/8d/American_bison_k5680-1.jpg?amount=100%25-free was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

Whereas on this branch it is working correctly with only one image is getting preloaded:

image

And no warning appears in the console.

**Review by westonruter — APPROVED** [review]
Thank you!!
