### PR TITLE
Fix: Moved `column_count` context from `column` block to `columns` block to ensure it is available to ancestor blocks

### LINKED ISSUE #2137: Accurate Sizes: The calculation of sizes attribute ignores column layout for default two/three-column
## Bug Description

The accurate sizes calculation didn't apply when we use column layout with default two/three-column layouts.

## Steps to reproduce

1. Create a new Page/Post.
2. Add a Columns block (choose the default 2 columns (50/50) or 3 columns (33/33/33) layout).
3. Insert a `core/Image` block into any one column.
4. View the post on the frontend.

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
## Summary

Fixes #2137

The columns block was not passing the column_count context to the column block, which caused the issue. This PR moves the column_count context to the columns block so it can be passed to its ancestor blocks.

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
@felixarntz @joemcgill could you please take a look when you have moment!

File: plugins/auto-sizes/tests/test-improve-calculate-sizes.php [hunk 1]
```diff
@@ -1272,6 +1272,59 @@ public static function data_image_block_with_parent_columns_and_its_parent_group
 		);
 	}
 
+	/**
+	 * Test that the image block in a two-column layout renders the correct sizes attribute.
```
Comment (westonruter) [inline plugins/auto-sizes/tests/test-improve-calculate-sizes.php:1276]: There are `@covers` annotations relevant for this test and others, no?

**Comment by westonruter** [comment]
@mukeshpanchal27 What is the expected impact of this change? 

I created a post with a Columns block as follows:

> image

<details><summary>Post Content</summary>

```html
<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"25%"} -->
<div class="wp-block-column" style="flex-basis:25%"><!-- wp:image {"id":62,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="http://localhost:8000/wp-content/uploads/2025/07/Juraparc_06-07-2013_-_Buffalo_calf-1024x678.jpg" alt="" class="wp-image-62"/><figcaption class="wp-element-caption">Buffalo calf</figcaption></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:image {"id":10,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="http://localhost:8000/wp-content/uploads/2025/06/American_bison_k5680-1-1-1024x668.jpg" alt="" class="wp-image-10"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"25%"} -->
<div class="wp-block-column" style="flex-basis:25%"><!-- wp:image {"id":63,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="http://localhost:8000/wp-content/uploads/2025/07/Bison_bison_Wichita_Mountain_Oklahoma-1024x741.jpg" alt="" class="wp-image-63"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

</details> 

The rendered markup on the frontend is the same on `trunk` as it is when this PR's branch is checked out:

```html
<div
  class="wp-block-columns is-layout-flex wp-container-core-columns-is-layout-28f84493 wp-block-columns-is-layout-flex"
>
  <div
    class="wp-block-column is-layout-flow wp-block-column-is-layout-flow"
    style="flex-basis: 25%"
  >
    <figure class="wp-block-image size-large">
      <img
        fetchpriority="high"
        decoding="async"
        width="1024"
        height="678"
        sizes="(max-width: 161px) 100vw, 161px"
        src="http://localhost:8000/wp-content/uploads/2025/07/Juraparc_06-07-2013_-_Buffalo_calf-1024x678.jpg"
        alt=""
        class="wp-image-62"
        srcset="
          http://localhost:8000/wp-content/uploads/2025/07/Juraparc_06-07-2013_-_Buffalo_calf-1024x678.jpg  1024w,
          http://localhost:8000/wp-content/uploads/2025/07/Juraparc_06-07-2013_-_Buffalo_calf-300x199.jpg    300w,
          http://localhost:8000/wp-content/uploads/2025/07/Juraparc_06-07-2013_-_Buffalo_calf-768x509.jpg    768w,
          http://localhost:8000/wp-content/uploads/2025/07/Juraparc_06-07-2013_-_Buffalo_calf-1536x1017.jpg 1536w,
          http://localhost:8000/wp-content/uploads/2025/07/Juraparc_06-07-2013_-_Buffalo_calf-2048x1356.jpg 2048w
        "
      />
      <figcaption class="wp-element-caption">Buffalo calf</figcaption>
    </figure>
  </div>

  <div
    class="wp-block-column is-layout-flow wp-block-column-is-layout-flow"
    style="flex-basis: 50%"
  >
    <figure class="wp-block-image size-large">
      <img
        decoding="async"
        width="1024"
        height="668"
        sizes="(max-width: 322px) 100vw, 322px"
        src="http://localhost:8000/wp-content/uploads/2025/06/American_bison_k5680-1-1-1024x668.jpg"
        alt=""
        class="wp-image-10"
        srcset="
          http://localhost:8000/wp-content/uploads/2025/06/American_bison_k5680-1-1-1024x668.jpg  1024w,
          http://localhost:8000/wp-content/uploads/2025/06/American_bison_k5680-1-1-300x196.jpg    300w,
          http://localhost:8000/wp-content/uploads/2025/06/American_bison_k5680-1-1-768x501.jpg    768w,
          http://localhost:8000/wp-content/uploads/2025/06/American_bison_k5680-1-1-1536x1002.jpg 1536w,
          http://localhost:8000/wp-content/uploads/2025/06/American_bison_k5680-1-1-2048x1336.jpg 2048w
        "
      />
    </figure>
  </div>

  <div
    class="wp-block-column is-layout-flow wp-block-column-is-layout-flow"
    style="flex-basis: 25%"
  >
    <figure class="wp-block-image size-large">
      <img
        decoding="async"
        width="1024"
        height="741"
        sizes="(max-width: 161px) 100vw, 161px"
        src="http://localhost:8000/wp-content/uploads/2025/07/Bison_bison_Wichita_Mountain_Oklahoma-1024x741.jpg"
        alt=""
        class="wp-image-63"
        srcset="
          http://localhost:8000/wp-content/uploads/2025/07/Bison_bison_Wichita_Mountain_Oklahoma-1024x741.jpg  1024w,
          http://localhost:8000/wp-content/uploads/2025/07/Bison_bison_Wichita_Mountain_Oklahoma-300x217.jpg    300w,
          http://localhost:8000/wp-content/uploads/2025/07/Bison_bison_Wichita_Mountain_Oklahoma-768x556.jpg    768w,
          http://localhost:8000/wp-content/uploads/2025/07/Bison_bison_Wichita_Mountain_Oklahoma-1536x1112.jpg 1536w,
          http://localhost:8000/wp-content/uploads/2025/07/Bison_bison_Wichita_Mountain_Oklahoma-2048x1483.jpg 2048w
        "
      />
    </figure>
  </div>
</div>
```

File: plugins/auto-sizes/tests/test-improve-calculate-sizes.php (hunk 1 above)
Comment (mukeshpanchal27) [reply plugins/auto-sizes/tests/test-improve-calculate-sizes.php:1276]: Added in https://github.com/WordPress/performance/pull/2138/commits/05732475e16644428b146d5bd459713c335e4cf1

**Comment by mukeshpanchal27** [comment]
> @mukeshpanchal27 What is the expected impact of this change?

@westonruter The intention of this change is to improve the accuracy of the `sizes` attribute when the **Columns** block uses equal column layouts (e.g. `50/50` or `33/33/33`).

In those cases, the editor currently doesn’t add a `width` attribute in `column` elements. As a result, the responsive `sizes` calculation falls back to the overall block width instead of the actual column width which leads to oversized `sizes` values.

**Example (current trunk):** TT4 Theme

Layout | Generated sizes value
-- | --
2 columns (50/50) | (max-width: 620px) 100vw, 620px
3 columns (33/33/33) | (max-width: 620px) 100vw, 620px


In both cases, it uses the columns default alignment width (620px), which is not correct in a multi-column layout.

**With this change (current branch)** we calculate the `sizes` value based on the column width instead of the columns block width: TT4 Theme
Layout | Generated sizes value
-- | --
2 columns (50/50) | (max-width: 310px) 100vw, 310px
3 columns (33/33/33) | (max-width: 206px) 100vw, 206px

This results in more accurate image size selection and improves performance by avoiding unnecessarily large images.

In your use-case (`25/50/25`), the columns already have an explicit width in the markup, so the `sizes` calculation works correctly in both trunk and this branch. The change mainly targets equal-width layouts where the editor does not output an explicit column width.

**Review by swissspidy — APPROVED** [review]

**Comment by westonruter** [comment]
@mukeshpanchal27 Thank you. I can confirm in a Columns block with two columns of equal widths, there is indeed a change:

```diff
--- /tmp/before.html	2025-08-18 09:55:09
+++ /tmp/after.html	2025-08-18 09:55:23
@@ -10,7 +10,7 @@
         decoding="async"
         width="1024"
         height="668"
-        sizes="(max-width: 645px) 100vw, 645px"
+        sizes="(max-width: 322px) 100vw, 322px"
         src="http://localhost:8000/wp-content/uploads/2025/06/American_bison_k5680-1-1-1024x668.jpg"
         alt=""
         class="wp-image-10"
@@ -33,7 +33,7 @@
         decoding="async"
         width="1024"
         height="741"
-        sizes="(max-width: 645px) 100vw, 645px"
+        sizes="(max-width: 322px) 100vw, 322px"
         src="http://localhost:8000/wp-content/uploads/2025/07/Bison_bison_Wichita_Mountain_Oklahoma-1024x741.jpg"
         alt=""
         class="wp-image-63"
```

**Review by westonruter — APPROVED** [review]
