### PR TITLE
Use more robust HTML Tag Processor for Image Placeholders

### LINKED ISSUE #1475: Image Placeholders can be hardened with HTML Tag Processor
Per https://github.com/WordPress/performance/issues/1446#issuecomment-2274643725:

I just realized a case where this drafted code using HTML Tag Processor might not work as expected, and that is specifically in relation to the `PICTURE` element output by Modern Image Formats. Enhanced Responsive Images is adding the `auto` value at priority 10 of the `wp_content_img_tag` filter:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/auto-sizes/hooks.php#L79

However, Modern Image Formats is also using this same filter and priority to rewrite the `IMG` as `PICTURE`:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/webp-uploads/hooks.php#L769

Since the `auto-sizes` slug is alphabetically before `webp-uploads`, then it seems the `auto` value is injected first so that when the `PICTURE` is generated by Modern Image Formats, it has `auto` in all the `sizes` attributes as expected. However, this seems brittle. To be even more robust, it seems the HTML Tag Processor code here should be updated to support adding `auto` to the `SOURCE` tags. Otherwise, the priorities of the filters could be made distinctly different, either having `auto_sizes_update_content_img_tag()` run at a priority below 10 or have `webp_uploads_wrap_image_in_picture()` run at a priority over 10.

Nevertheless, take note that Enhanced Responsive Images also has a `wp_content_img_tag` filter that runs at priority 9, so it would need to be bumped down to priority 8 if we go in that direction:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/auto-sizes/hooks.php#L226

Lastly, Image Placeholders is also filtering `wp_content_img_tag` but at priority 20:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/dominant-color-images/hooks.php#L166

I was worried that this would mean that `PICTURE` elements generated by Modern Image Formats would be broken with Image Placeholders. But this doesn't seem to be the case. Example image with picture element turned off:

```html
<img
  data-dominant-color="8c7d58"
  data-has-transparency="false"
  style="--dominant-color: #8c7d58"
  fetchpriority="high"
  decoding="async"
  width="1024"
  height="668"
  src="http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668-jpg.webp"
  alt=""
  class="not-transparent wp-image-13"
  srcset="
    http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668-jpg.webp 1024w,
    http://localhost:8888/wp-content/uploads/2024/06/bison1-300x196-jpg.webp   300w,
    http://localhost:8888/wp-content/uploads/2024/06/bison1-768x501-jpg.webp   768w,
    http://localhost:8888/wp-content/uploads/2024/06/bison1-1536x1002.jpg     1536w,
    http://localhost:8888/wp-content/uploads/2024/06/bison1-2048x1336.jpg     2048w,
    http://localhost:8888/wp-content/uploads/2024/06/bison1-1568x1023.jpg     1568w
  "
  sizes="(max-width: 650px) 100vw, 650px"
/>
```

And with picture element turned on:

```html
<picture
  class="not-transparent wp-picture-13"
  style="--dominant-color: #8c7d58; display: contents"
  ><source
    type="image/webp"
    srcset="
      http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668-jpg.webp 1024w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-300x196-jpg.webp   300w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-768x501-jpg.webp   768w
    "
    sizes="(max-width: 650px) 100vw, 650px" />
  <source
    type="image/jpeg"
    srcset="
      http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668.jpg 1024w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-300x196.jpg   300w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-768x501.jpg   768w
    "
    sizes="(max-width: 650px) 100vw, 650px" />
  <img
    data-dominant-color="8c7d58"
    data-has-transparency="false"
    fetchpriority="high"
    decoding="async"
    width="1024"
    height="668"
    src="http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668-jpg.webp"
    alt=""
    class="not-transparent wp-image-13"
    srcset="
      http://localhost:8888/wp-content/uploads/2024/06/bison1-1024x668-jpg.webp 1024w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-300x196-jpg.webp   300w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-768x501-jpg.webp   768w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-1536x1002.jpg     1536w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-2048x1336.jpg     2048w,
      http://localhost:8888/wp-content/uploads/2024/06/bison1-1568x1023.jpg     1568w
    "
    sizes="(max-width: 650px) 100vw, 650px"
/></picture>
```

This is still working. Interestingly, the result is `--dominant-color: #8c7d58;` appearing on the `PICTURE` tag whereas `data-dominant-color` and `data-has-transparency` remain on the `IMG` tag. This is because we added `style="display:contents;"` to the `PICTURE` in #1307, so Image Placeholders is accidentally amending the `style` attribute on the `PICTURE` tag as oppose to adding/updating the `style` attribute on the `IMG` tag:

https://github.com/WordPress/performance/blob/e7313851f39749886a4ae0bacbcd620a6effce3d/plugins/dominant-color-images/hooks.php#L143-L147

Fortunately this didn't break anything, but we just got lucky. We should update Image Placeholders to use the HTML Tag Processor too to be more reliable/consistent.

### PR DESCRIPTION
**Pull request by sagarnasit**
## Summary

Fixes #1475

- Use more robust HTML Tag Processor for Image Placeholder.

### CODE REVIEW

**Comment by sagarnasit** [comment]
Output for Image with picture element turned off:
```html
<img
  data-dominant-color="788d7e"
  data-has-transparency="false"
  style="--dominant-color: #788d7e;"
  fetchpriority="high"
  decoding="async"
  width="1024"
  height="711"
  src="http://localhost:8888/wp-content/uploads/2024/08/IMG-1-jpeg.webp"
  alt=""
  class="wp-image-13 not-transparent"
  srcset="
    http://localhost:8888/wp-content/uploads/2024/08/IMG-1-jpeg.webp 1024w,
    http://localhost:8888/wp-content/uploads/2024/08/IMG-1-300x208-jpeg.webp 300w,
    http://localhost:8888/wp-content/uploads/2024/08/IMG-1-768x533-jpeg.webp 768w"
  sizes="(max-width: 620px) 100vw, 620px"
>
```

With the picture element turned on:

```html
<picture
  class="wp-picture-13"
  style="display: contents;">
  <source
   type="image/webp"
   srcset="
    http://localhost:8888/wp-content/uploads/2024/08/IMG-1-jpeg.webp 1024w,
    http://localhost:8888/wp-content/uploads/2024/08/IMG-1-300x208-jpeg.webp 300w,
    http://localhost:8888/wp-content/uploads/2024/08/IMG-1-768x533-jpeg.webp 768w"
   sizes="(max-width: 620px) 100vw, 620px">
  <img
   data-dominant-color="788d7e"
   data-has-transparency="false"
   style="--dominant-color: #788d7e;"
   fetchpriority="high"
   decoding="async"
   width="1024"
   height="711"
   src="http://localhost:8888/wp-content/uploads/2024/08/IMG-1.jpeg"
   alt=""
   class="wp-image-13 not-transparent"
   srcset="
    http://localhost:8888/wp-content/uploads/2024/08/IMG-1.jpeg 1024w,
    http://localhost:8888/wp-content/uploads/2024/08/IMG-1-300x208.jpeg 300w,
    http://localhost:8888/wp-content/uploads/2024/08/IMG-1-768x533.jpeg 768w"
   sizes="(max-width: 620px) 100vw, 620px"
></picture>
```

After these changes style with `--dominant-color`  is now on the IMG tag instead of previously on the PICTURE tag.

File: plugins/dominant-color-images/hooks.php [hunk 1]
```diff
@@ -95,6 +95,12 @@ function dominant_color_img_tag_add_dominant_color( $filtered_image, string $con
 		$filtered_image = '';
 	}
 
+	$processor = new WP_HTML_Tag_Processor( $filtered_image );
+
+	if ( ! $processor->next_tag( array( 'tag_name' => 'IMG' ) ) ) {
+		return $filtered_image;
+	}
+
```
Comment (westonruter) [inline plugins/dominant-color-images/hooks.php:102]: This condition should be moved below the `if ( 'the_content' !== $context ) {` condition below.

File: plugins/dominant-color-images/hooks.php [hunk 2]
```diff
@@ -107,7 +113,7 @@ function dominant_color_img_tag_add_dominant_color( $filtered_image, string $con
 	}
```
Comment (westonruter) [inline plugins/dominant-color-images/hooks.php:112]: This condition should be updated to use the tag processor, using `$processor->getAttribute('src')` and if it is not a string, return.

File: plugins/dominant-color-images/hooks.php [hunk 3]
```diff
@@ -134,34 +140,23 @@ function dominant_color_img_tag_add_dominant_color( $filtered_image, string $con
...
-
 	if ( ! empty( $image_meta['dominant_color'] ) ) {
-		$data .= sprintf( 'data-dominant-color="%s" ', esc_attr( $image_meta['dominant_color'] ) );
+		$processor->set_attribute( 'data-dominant-color', esc_attr( $image_meta['dominant_color'] ) );
 
-		if ( str_contains( $filtered_image, ' style="' ) ) {
-			$filtered_image = str_replace( ' style="', ' style="--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . '; ', $filtered_image );
-		} else {
-			$filtered_image = str_replace( '<img ', '<img style="--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . ';" ', $filtered_image );
+		$style_attribute = '--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . '; ';
```
Comment (westonruter) [inline plugins/dominant-color-images/hooks.php]: No need to use `esc_attr()` with tag processor as this is handled for you.

File: plugins/dominant-color-images/hooks.php [hunk 4]
```diff
@@ -134,34 +140,23 @@ function dominant_color_img_tag_add_dominant_color( $filtered_image, string $con
 		return $filtered_image;
 	}
 
-	$data        = '';
-	$extra_class = '';
-
 	if ( ! empty( $image_meta['dominant_color'] ) ) {
-		$data .= sprintf( 'data-dominant-color="%s" ', esc_attr( $image_meta['dominant_color'] ) );
+		$processor->set_attribute( 'data-dominant-color', esc_attr( $image_meta['dominant_color'] ) );
```
Comment (westonruter) [inline plugins/dominant-color-images/hooks.php]:
```suggestion
		$processor->set_attribute( 'data-dominant-color', $image_meta['dominant_color'] );
```

File: plugins/dominant-color-images/hooks.php (hunk 3 above)
Comment (westonruter) [reply plugins/dominant-color-images/hooks.php]:
```suggestion
		$style_attribute = "--dominant-color: #{$image_meta['dominant_color']}; ";
```

File: plugins/dominant-color-images/hooks.php [hunk 5]
```diff
@@ -134,34 +140,23 @@ function dominant_color_img_tag_add_dominant_color( $filtered_image, string $con
...
 
-		if ( str_contains( $filtered_image, ' style="' ) ) {
-			$filtered_image = str_replace( ' style="', ' style="--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . '; ', $filtered_image );
-		} else {
-			$filtered_image = str_replace( '<img ', '<img style="--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . ';" ', $filtered_image );
+		$style_attribute = '--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . '; ';
+		if ( null !== $processor->get_attribute( 'style' ) ) {
+			$style_attribute .= $processor->get_attribute( 'style' );
```
Comment (westonruter) [inline plugins/dominant-color-images/hooks.php:146]: What if the existing style doesn't end in a semicolon?

Comment (sagarnasit) [reply plugins/dominant-color-images/hooks.php:146]: @westonruter `--dominant-color` CSS is being prepended to ensure it does not break existing styles.

Comment (westonruter) [reply plugins/dominant-color-images/hooks.php:146]: Oh, good point 😊

File: plugins/dominant-color-images/tests/test-dominant-color.php
Comment (sagarnasit) [inline plugins/dominant-color-images/tests/test-dominant-color.php:1]: Using an HTML Tag Processor allows including single quotes and escaped double quotes for the image placeholder.

File: plugins/dominant-color-images/hooks.php [hunk 6]
```diff
@@ -100,14 +100,18 @@ function dominant_color_img_tag_add_dominant_color( $filtered_image, string $con
...
-	// Only apply the dominant color to images that have a src attribute that
-	// starts with a double quote, ensuring escaped JSON is also excluded.
-	if ( ! str_contains( $filtered_image, ' src="' ) ) {
+	$processor = new WP_HTML_Tag_Processor( $filtered_image );
+	if ( ! $processor->next_tag( array( 'tag_name' => 'IMG' ) ) ) {
+		return $filtered_image;
+	}
+
+	// Only apply the dominant color to images that have a src attribute.
+	if ( null === $processor->get_attribute( 'src' ) || ! is_string( $processor->get_attribute( 'src' ) ) ) {
```
Comment (westonruter) [inline plugins/dominant-color-images/hooks.php]: This can be further simplified:

```suggestion
	if ( ! is_string( $processor->get_attribute( 'src' ) ) ) {
```

File: plugins/dominant-color-images/tests/test-dominant-color.php [hunk 7]
```diff
@@ -189,11 +189,11 @@ public function data_dominant_color_img_tag_add_dominant_color_requires_proper_q
...
 			'single quotes'         => array(
 				'image'    => "<img src='%s'>",
-				'expected' => false,
+				'expected' => true,
 			),
 			'escaped double quotes' => array(
 				'image'    => '<img src=\"%s\">',
-				'expected' => false,
+				'expected' => true,
 			),
```
Comment (westonruter) [inline plugins/dominant-color-images/tests/test-dominant-color.php]: This is a strange test case to begin with. If the string is ``, the HTML Tag Processor would parse the `src` as having the value of `\"http://example.com/foo.jpg\"`. I guess this doesn't even matter because we're not doing anything with the `src` anyway. I just wonder what value this test case has in the first place.

**Review by westonruter — APPROVED** [review]
LGTM!

File: plugins/dominant-color-images/tests/test-dominant-color.php (hunk 7 above)
Comment (felixarntz) [reply plugins/dominant-color-images/tests/test-dominant-color.php]: I think we should delete this test case, I agree it doesn't make sense.

**Review by felixarntz — APPROVED** [review]
LGTM, just I think it's worth deleting the one pointless test.

**Comment by sagarnasit** [comment]
@felixarntz I have removed the test case.
