### PR TITLE
Fix incorrect handling of `admin_email` and actual admin user's email when original `admin_email` user was deleted

### LINKED ISSUE #601: SQLite module: Wrong user details
## Bug Description

User information get wrong when SQLite is enabled.

## Steps to reproduce

1. Setup WordPress with an email `wordpress@example.com`
2. Go to Admin Panel > Users > Add New user with email `test@test.com` and First and Last name
3. Log out
4. Login with `test@test.com` user
5. Go to Admin Panel > Users and delete `wordpress@example.com` user
6. Now Activate SQLite module (Go to Admin Panel > Settings > Performance > SQLite Integration)
7. Check User details at Admin Panel > Users
8. The new WordPress installation uses the email address `wordpress@example.com` rather than `test@test.com` 
9. It should use the original user information instead of the old WP setup admin user details.

## Additional Context

 - PHP Version: 7.4.33
 - OS: Mac
 - Browser: chrome
 - Plugin Version: 1.7.0
 - Device: Macbook Pro
 - SQLite version: 3.34.1

### PR DESCRIPTION
**Pull request by felixarntz**
## Summary

Fixes #601

## Relevant technical choices

* This PR ensures the `admin_email` option and the admin user's email keep their original values even in case they were different (e.g. when the original admin user was deleted).
* See https://github.com/WordPress/performance/issues/601#issuecomment-1352012473 for additional context on the fix.
* The PR includes one additional (somewhat unrelated) safe guard of not running the automatic setup in a multisite. While it would be great to eventually cover that too, it is a lot more complicated; for now it's the safest option to let the user handle it for a multisite environment.

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

File: modules/database/sqlite/activate.php [hunk 1]
```diff
@@ -41,6 +41,12 @@
 		}
 	}
 
+	// Do not automatically set up SQLite DB on a multisite as that is notably
+	// more complex. Potentially it can be added in the future.
+	if ( is_multisite() ) {
+		return;
+	}
```
Comment (aristath) [inline modules/database/sqlite/activate.php:48]: Should we also add a check for `is_multisite` in the `can-load.php` file? 🤔

Comment (mukeshpanchal27) [reply modules/database/sqlite/activate.php:48]: If we add the `is_multisite` check in the `can-load.php` file, we don't need to add it to the `activate.php` file. WDYT?

**Review by mukeshpanchal27 — COMMENTED** [review]
Thanks @felixarntz The PR resolved the user email issue, but it still did not pull user details such as first name, last name, website, biographical information, and so on.

Can we fix this edge case issue in the next release? WDYT?

File: modules/database/sqlite/activate.php (hunk 1 above)
Comment (ankitrox) [reply modules/database/sqlite/activate.php:48]: Yes, I think this is better candidate to go in `can-load.php` as if site is multisite, then we should instruct not to load module at all rather than instructing to load module and then simply doing nothing!

**Comment by ankitrox** [comment]
Apart from [this comment](https://github.com/WordPress/performance/pull/603#discussion_r1049306164), everything else looks fine to me.

**Review by ankitrox — APPROVED** [review]

**Review by aristath — APPROVED** [review]
I'll go ahead and pre-approve this. Moving the `is_multisite` check to `can-load` is not a deal-breaker, I'm happy to merge this one as-is if we don't want to move the multisite check. cc @felixarntz

File: modules/database/sqlite/activate.php (hunk 1 above)
Comment (felixarntz) [reply modules/database/sqlite/activate.php:48]: @aristath @mukeshpanchal27 @ankitrox This shouldn't be necessary. It's not that the entire module doesn't work on multisite, it's just that the automatic installation doesn't work with multisite.

**Comment by felixarntz** [comment]
@mukeshpanchal27 
> The PR resolved the user email issue, but it still did not pull user details such as first name, last name, website, biographical information, and so on.

I think that's expected. We explicitly say that this setup is not a migration of data, we only set up the bare minimum WordPress SQLite database based on the data from the original database. User details like those you're saying are not essential to a WordPress install (i.e. they are not encompassed by `wp_install()`).

**Review by mukeshpanchal27 — APPROVED** [review]

**Comment by dianatupas** [comment]
This bug is still existing
