### PR TITLE
Add PHPCS ruleset from Plugin Check and fix issues

### LINKED ISSUE #2043: Address errors reported by Plugin Check
## Bug Description

Check whether the Performance Plugin fully complies with the [Plugin Check (PCP) plugin](https://wordpress.org/plugins/plugin-check/). If not, make it comply

## Steps to reproduce

1. Install and activate the Plugin Check (PCP) plugin from https://wordpress.org/plugins/plugin-check/.
2. Go to Admin Dashboard > Tools > Plugin Check.
3. Select the `Performance Lab` plugin.
4. Tick all Categories.
5. Click on the `Check it!` button.
6. See the warnings which can be resolved.

## Screenshots

Image

Image

### LINKED ISSUE #2049: Comply the Optimization Detective Plugin with the Plugin Check (PCP) Plugin
## Bug Description

Check whether the Optimization Detective Plugin fully complies with the [Plugin Check (PCP) plugin](https://wordpress.org/plugins/plugin-check/). If not, make it comply.

## Steps to reproduce

1. Install and activate the Plugin Check (PCP) plugin from https://wordpress.org/plugins/plugin-check/.
2. Go to Admin Dashboard > Tools > Plugin Check.
3. Select the `Optimization Detective` plugin.
4. Tick all Categories.
5. Click on the `Check it!` button.
6. See the warnings which can be resolved.

## Screenshots

Image

Image

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #2043
Fixes #2049

### CODE REVIEW

File: plugins/performance-lab/includes/admin/load.php [hunk 1]
```diff
@@ -305,7 +305,7 @@ function perflab_install_activate_plugin_callback(): void {
 		wp_die( esc_html__( 'Missing required parameter.', 'performance-lab' ) );
 	}
 
-	$plugin_slug = perflab_sanitize_plugin_slug( wp_unslash( $_GET['slug'] ) );
+	$plugin_slug = perflab_sanitize_plugin_slug( wp_unslash( $_GET['slug'] ) ); // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- perflab_sanitize_plugin_slug() is a sanitizing function.
```
Comment (westonruter) [inline plugins/performance-lab/includes/admin/load.php:308]: As an alternative to this, the function could be added to `customUnslashingSanitizingFunctions`, but then Plugin Check wouldn't know about it.

File: composer.json [hunk 2]
```diff
@@ -33,12 +46,14 @@
     "wp-phpunit/wp-phpunit": "^6.5",
     "yoast/phpunit-polyfills": "^4.0",
     "phpstan/php-8-stubs": "^0.4.0",
-    "phpstan/phpstan-strict-rules": "^1.6"
+    "phpstan/phpstan-strict-rules": "^1.6",
+    "wpackagist-plugin/plugin-check": "^1.5"
```
Comment (westonruter) [inline composer.json:54]: I wasn't entirely sure how to install the sniffs for PCP, so I installed them via WPackagist. @swissspidy is this right?

File: plugins/optimization-detective/storage/class-od-storage-lock.php [hunk 3]
```diff
@@ -86,7 +86,13 @@ public static function get_ttl(): int {
 	 * @return non-empty-string Transient key.
 	 */
 	public static function get_transient_key(): string {
-		$ip_address = $_SERVER['HTTP_X_FORWARDED_FOR'] ?? $_SERVER['REMOTE_ADDR'];
+		if ( isset( $_SERVER['HTTP_X_FORWARDED_FOR'] ) ) {
+			$ip_address = sanitize_text_field( wp_unslash( $_SERVER['HTTP_X_FORWARDED_FOR'] ) );
+		} elseif ( isset( $_SERVER['REMOTE_ADDR'] ) ) {
+			$ip_address = sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ) );
```
Comment (westonruter) [inline plugins/optimization-detective/storage/class-od-storage-lock.php:92]: This is unnecessary since it is sent into `wp_hash()`, but since that function technically is pluggable, it's better to ensure that `$ip_address` is safe.

Comment (westonruter) [reply plugins/optimization-detective/storage/class-od-storage-lock.php:92]: I guess `rest_is_ip_address()` could be included here as well, but that would be even more over the top, maybe.

File: plugins/performance-lab/includes/admin/load.php (hunk 1 above)
Comment (swissspidy) [reply plugins/performance-lab/includes/admin/load.php:308]: On the other hand, I don't think Plugin Check handles `phpcs:ignore` comments, so it won't have an effect there.

Related: https://github.com/WordPress/plugin-check/issues/901

File: composer.json [hunk 4]
```diff
@@ -20,6 +20,19 @@
     "ext-gd": "Required to use Modern Image Format's Dominant_Color_Image_Editor_GD class",
     "ext-zlib": "Required for compression of URL Metric data submitted to the REST API for storage in Optimization Detective"
   },
+  "repositories": [
+    {
+      "type": "composer",
+      "url": "https://wpackagist.org"
+    }
+  ],
```
Comment (swissspidy) [inline composer.json]: Looks like the documentation recommends:

```json
    "repositories":[
        {
            "type":"composer",
            "url":"https://wpackagist.org",
            "only": [
                "wpackagist-plugin/*",
                "wpackagist-theme/*"
            ]
        }
    ],
```

File: composer.json (hunk 2 above)
Comment (swissspidy) [reply composer.json:54]: Interesting! I suppose so 🙂 

When we added those custom sniffs we haven't really thought about making these available to others. But if it works, it works.

File: tools/phpcs/phpcs.ruleset.xml [hunk 5]
```diff
@@ -1,7 +1,10 @@
 <?xml version="1.0"?>
-<ruleset name="WPP-Base">
+<ruleset name="WPP-Base" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/squizlabs/PHP_CodeSniffer/master/phpcs.xsd">
 	<description>Sniffs for WordPress plugins</description>
 
+	<rule ref="../../vendor/wpackagist-plugin/plugin-check/vendor/plugin-check/phpcs-sniffs/PluginCheck/ruleset.xml" />
```
Comment (swissspidy) [inline tools/phpcs/phpcs.ruleset.xml:5]: Why the double vendor? 🤔  Is this from the composer installer-paths config?

File: tools/phpcs/plugin-check.ruleset.xml [hunk 6]
```diff
@@ -0,0 +1,152 @@
+<?xml version="1.0"?>
+<ruleset name="WPPluginCheck" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/squizlabs/PHP_CodeSniffer/master/phpcs.xsd">
+
+	<!-- For more information: https://make.wordpress.org/plugins/handbook/review/ -->
+	<description>Standards any plugin to be published on wordpress.org should comply with.</description>
+
+	<!-- The following rules have been copied from https://github.com/WordPress/plugin-check/blob/95c426228a23a3b290de7758a1708e95fd3c5345/phpcs-rulesets/plugin-review.xml#L33-L174 -->
```
Comment (swissspidy) [inline tools/phpcs/plugin-check.ruleset.xml:7]: Instead of copying the file, can we just reference it in `phpcs.ruleset.xml` from `vendor/[...]/plugin-check/phpcs-rulesets/plugin-review.xml`?

File: tools/phpcs/phpcs.ruleset.xml (hunk 5 above)
Comment (westonruter) [reply tools/phpcs/phpcs.ruleset.xml:5]: Because it's installed in `vendor` by composer for this project, and then the plugin is distributed with its own `vendor` directory.

File: plugins/performance-lab/includes/admin/load.php (hunk 1 above)
Comment (westonruter) [reply plugins/performance-lab/includes/admin/load.php:308]: I guess then it's still better to have these comments because if a plugin reviewer looks at the line they can at least see the explanatory comment.

File: tools/phpcs/phpcs.ruleset.xml (hunk 5 above)
Comment (swissspidy) [reply tools/phpcs/phpcs.ruleset.xml:5]: Ah 💡 Right. Inception!

File: tools/phpcs/plugin-check.ruleset.xml (hunk 6 above)
Comment (westonruter) [reply tools/phpcs/plugin-check.ruleset.xml:7]: Good question. I thought about this but I didn't try it because that ruleset includes other rules which we don't want, namely:

https://github.com/WordPress/plugin-check/blob/95c426228a23a3b290de7758a1708e95fd3c5345/phpcs-rulesets/plugin-review.xml#L7-L31

The config `<config name="testVersion" value="5.2-"/>` is causing a lot of failures in `PHPCompatibility`. I just tried.

It would be nice if there was a base ruleset in PCP which `plugin-review.xml` included that we could also include.

**Comment by swissspidy** [comment]
The changes here are nice for local development. For CI, it might be easier to just use https://github.com/WordPress/plugin-check-action

File: tools/phpcs/plugin-check.ruleset.xml (hunk 6 above)
Comment (swissspidy) [reply tools/phpcs/plugin-check.ruleset.xml:7]: I see, makes sense.

Yeah there might be ways to make that easier. Can't hurt to open an issue there with this suggestion 👍

Comment (westonruter) [reply tools/phpcs/plugin-check.ruleset.xml:7]: Good idea. Opened: https://github.com/WordPress/plugin-check/issues/966

**Comment by westonruter** [comment]
> For CI, it might be easier to just use https://github.com/WordPress/plugin-check-action

I thought about that, but the only concern there would be duplication in the failures, right? Also, if PCP ignores `phpcs:ignore` comments then this would be problematic, right?

**Comment by swissspidy** [comment]
> I thought about that, but the only concern there would be duplication in the failures, right?

Yes there would be duplication. So probably have to pick one or the other.

> Also, if PCP ignores `phpcs:ignore` comments then this would be problematic, right?

It depends. PCP Is the source of truth after all, as that's what's being run on dotorg for plugin submissions (and eventually updates)

**Review by ShyamGadde — APPROVED** [review]
LGTM - went through the diff and everything looks good to me, nothing further from my side. 👍

File: tools/phpcs/plugin-check.ruleset.xml (hunk 6 above)
Comment (westonruter) [reply tools/phpcs/plugin-check.ruleset.xml:7]: Since 1.6 is now released, I've opened https://github.com/WordPress/performance/pull/2099 to reuse the PCP ruleset.
