### PR TITLE
Fix incorrect usage of badge colors in all Site Health checks

### LINKED ISSUE #471: Fix incorrect usage of Site Health checks `color` field
## Bug Description

See https://github.com/WordPress/wordpress-develop/pull/2890#discussion_r939699786: Several of our current Site Health check modules set the `color` based on the status of the check. However, that is not how the color should be used. Instead, it should be based on what area it applies to (in our case probably always `Performance`, for which WordPress core uses `blue`).

cc @manuelRod @tillkruss

### PR DESCRIPTION
**Pull request by felixarntz**
## Summary

Fixes #471

## Relevant technical choices

* All badges should always be "Performance" and use the color `blue`.
* Setting the badge color based on check result status is incorrect.

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

File: modules/site-health/audit-autoloaded-options/load.php [hunk 1]
```diff
@@ -69,10 +69,9 @@ function perflab_aao_autoloaded_options_test() {
 		return $result;
 	}
 
-	$result['status']         = 'critical';
-	$result['badge']['color'] = 'red';
-	$result['label']          = esc_html__( 'Autoloaded options could affect performance', 'performance-lab' );
-	$result['description']    = sprintf(
+	$result['status']      = 'critical';
+	$result['label']       = esc_html__( 'Autoloaded options could affect performance', 'performance-lab' );
```
Comment (mukeshpanchal27) [inline modules/site-health/audit-autoloaded-options/load.php]:
```suggestion
	$result['label']       = __( 'Autoloaded options could affect performance', 'performance-lab' );
```

**Review by jjgrainger — APPROVED** [review]

**Review by mehulkaklotar — APPROVED** [review]
Looks good! 🚀

**Review by mukeshpanchal27 — APPROVED** [review]

**Review by ankitrox — APPROVED** [review]
LGTM

File: modules/site-health/audit-autoloaded-options/load.php [hunk 2]
```diff
@@ -40,15 +40,15 @@ function perflab_aao_autoloaded_options_test() {
 	$base_description = __( 'Autoloaded options are configuration settings for plugins and themes that are automatically loaded with every page load in WordPress. Having too many autoloaded options can slow down your site.', 'performance-lab' );
 
 	$result = array(
-		'label'       => esc_html__( 'Autoloaded options are acceptable', 'performance-lab' ),
```
Comment (adamsilverstein) [inline modules/site-health/audit-autoloaded-options/load.php:43]: I noticed we are applying `esc_html__` inconsistently to translations and that you removed a bunch in this PR. 

For core, we don't escape translations, however for plugins I generally recommend escaping (as 10up [recommends](https://10up.github.io/Engineering-Best-Practices/php/#:~:text=Translated%20text%20also%20often%20needs%20to%20be%20escaped%20on%20output.)). 

Maybe rather than changing here we can open a follow issue to use a uniform approach and change throughout the plugin?

Comment (felixarntz) [reply modules/site-health/audit-autoloaded-options/load.php:43]: While escaping is recommended for plugins more than core, the rules also say that escaping should happen at the output level. In all the places here though, we're only writing data into an array, so per those guidelines escaping here would not follow the best practice.

All escaping for Site Health check content should happen in WordPress core per that definition, since that's where the data is being output.
