### PR TITLE
Do not show admin pointer in multisite Network Admin

### LINKED ISSUE #387: Do not show admin pointer in multisite Network Admin
## Bug Description

The admin pointer for a new activation of the plugin currently shows in the Network Admin for multisite as well. This doesn't make sense since the plugin's admin screen is not available there.

## Steps to reproduce

1. Network activate the plugin for the first time on a multisite.
2. See the admin pointer in Network Admin UI.

## Screenshots

Screen Shot 2022-06-21 at 10 47 16 AM

## Proposed fix
An extra condition should be added before showing the admin pointer to ensure the current screen is not within the Network Admin (or User Admin) UI.

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
## Summary

PR includes the solution that does not show an admin pointer in the multisite Network Admin.

Fixes #387

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Review by jjgrainger — APPROVED** [review]
LGTM

**Review by eugene-manuilov — APPROVED** [review]
LGTM

**Review by akshitsethi — APPROVED** [review]
💯

File: admin/load.php [hunk 1]
```diff
@@ -353,6 +353,11 @@ function perflab_admin_pointer( $hook_suffix ) {
 		return;
 	}
 
+	// Do not show admin pointer in multisite Network Admin.
+	if ( is_network_admin() ) {
```
Comment (felixarntz) [inline admin/load.php]: While that's a separate problem, we should also ensure this pointer doesn't show in the User Admin. That's yet another separate admin area that exists in WordPress. I mentioned that (though a bit as a side note) on the issue description for #387.
```suggestion
	if ( is_network_admin() || is_user_admin() ) {
```

**Review by felixarntz — COMMENTED** [review]
@mukeshpanchal27 Looks good, just one additional request.

File: admin/load.php (hunk 1 above)
Comment (mukeshpanchal27) [reply admin/load.php]: Thanks, @felixarntz for the feedback. I missed that mentioned comment.

Suggested changes are updated in PR.

Comment (felixarntz) [reply admin/load.php]: @mukeshpanchal27 Excellent, thanks!

**Review by felixarntz — APPROVED** [review]
@mukeshpanchal27 Awesome, thanks!
