### PR TITLE
Use HTML Tag Processor to audit blocking scripts & styles in Site Health’s enqueued-assets test

### LINKED ISSUE #2030: Site Health tests for enqueued scripts and styles are inaccurate
## Bug Description

On [my blog](https://weston.ruter.net/), I have two enqueued scripts and one enqueued script module. For stylesheets, all of them are inlined except for one external stylesheet which I've moved to the footer. Nevertheless, Enqueued Scripts test is reporting an invalid number of scripts being enqueued and the Enqueued Styles test is not accounting for the inlining.

We've talked before about using a [loopback request](https://github.com/WordPress/plugin-check/pull/519#discussion_r1680495277) to fetch the HTML to look at what is actually printed to determine the external scripts and styles added to the page. We can easily analyze the HTML via the HTML Tag Processor. 

## Screenshots

Image

### PR DESCRIPTION
**Pull request by b1ink0**
## Summary

Fixes #2030 

## Relevant technical choices

This PR updates the Site Health "Enqueued Scripts" and "Enqueued Styles" tests by combining them into a single "Blocking Assets" Site Health test. It now accurately detects and reports only truly render-blocking scripts and styles. This is achieved by performing an unauthenticated loopback request to the home page and analyzing the resulting front-end HTML with the `WP_HTML_Tag_Processor`.

image

### CODE REVIEW

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 1]
```diff
@@ -13,107 +13,136 @@
...
-			);
+			$href = $processor->get_attribute( 'href' );
+			if ( ! is_string( $href ) || false !== strpos( $href, 'wp-includes' ) ) {
+				continue;
+			}
+
+			$path = perflab_aea_get_path_from_resource_url( $href );
+			if ( '' === $path ) {
+				continue;
+			}
```
Comment (b1ink0) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Currently, our audit only scans assets located in the WordPress content directory. This raises an question,
how should the audit treat scripts and styles served from a CDN? Should these third-party resources be included in the render-blocking report, excluded entirely, or perhaps flagged separately so we can distinguish external blocking assets from local ones?

I think we’ll also need to consider how to measure their sizes efficiently. One approach could be, sending an HTTP HEAD request to the CDN-hosted URL to check for a Content‑Length header.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 2]
```diff
@@ -13,107 +13,136 @@
...
 
-			$enqueued_styles[] = array(
-				'src'  => $style->src,
-				'size' => wp_filesize( $path ) + $inline_size,
-			);
+			$href = $processor->get_attribute( 'href' );
+			if ( ! is_string( $href ) || false !== strpos( $href, 'wp-includes' ) ) {
+				continue;
+			}
```
Comment (b1ink0) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: We currently skip any URL containing `wp-includes` (i.e. core assets). Since the goal is to surface all render-blocking resources, should we remove that exclusion and include core scripts and styles in the audit as well?

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 3]
```diff
@@ -13,107 +13,136 @@
...
-				$path = $style->extra['path'];
-			} else { // Fallback to getting the path from the style's src.
-				$path = perflab_aea_get_path_from_resource_url( $style->src );
+			// Process blocking inline scripts.
+			if ( ! is_string( $src ) ) {
+				$script_size = mb_strlen( $processor->get_modifiable_text(), '8bit' );
+				if ( false !== $script_size ) {
+					$assets['scripts'][] = array(
+						'src'  => 'inline',
+						'size' => $script_size,
```
Comment (b1ink0) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Currently each inline `SCRIPT` is reported as its own entry, do we want to continue treating every inline script separately, or would it make sense to aggregate inline scripts into a single summary?

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 1 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: cc: @westonruter

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: From a performance perspective, CDN-served assets could be even worse for performance since they require a new TCP connection, now that browsers don't reuse cached resources across origins. So we definitely should be including them in the render-blocking report.

Sending an HTTP `HEAD` request for all resources regardless of whether they are on the same origin or not makes sense to me. If the request returns in a 404 then this would be important to report as well.

Once we have the report, then a future enhancement would be digging in to find the theme/plugin responsible for the resource being added in the first place. The AMP plugin implements a lot of this, and it was getting extracted a separate package via https://github.com/GoogleChromeLabs/wp-origination but that effort got stalled and was abandoned. See also https://github.com/WordPress/performance/issues/1095.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 2 above)
Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: I think this exclusion should be removed, yes.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 3 above)
Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: I don't think inline scripts need to be counted since the render blocking is not significant compared to blocking external scripts.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 4]
```diff
@@ -307,3 +312,28 @@ function perflab_aea_get_path_from_resource_url( string $resource_url ): string
...
+		return false;
+	}
+
+	$content_length = wp_remote_retrieve_header( $head_response, 'content-length' );
+	if ( is_array( $content_length ) && 0 < count( $content_length ) ) {
+		$content_length = $content_length[0];
+	}
+	if ( ! is_string( $content_length ) || '' === $content_length || ! ctype_digit( $content_length ) || 0 === (int) $content_length ) {
+		return false;
+	}
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: If the function returns `null` on failure, then this could have a return type in PHP 7.2:

```suggestion
 * @return int|null Returns the content length in bytes or null if it cannot be determined.
 */
function perflab_aea_get_asset_content_length( string $resource_url ): ?int {
	$head_response = wp_remote_head( $resource_url, array( 'timeout' => 10 ) );
	if ( is_wp_error( $head_response ) || 200 !== wp_remote_retrieve_response_code( $head_response ) ) {
		return null;
	}

	$content_length = wp_remote_retrieve_header( $head_response, 'content-length' );
	if ( is_array( $content_length ) && 0 < count( $content_length ) ) {
		$content_length = $content_length[0];
	}
	if ( ! is_string( $content_length ) || '' === $content_length || ! ctype_digit( $content_length ) || 0 === (int) $content_length ) {
		return null;
	}
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 5]
```diff
@@ -13,107 +13,109 @@
...
-				'' !== $style->extra['path']
-			) {
-				$path = $style->extra['path'];
-			} else { // Fallback to getting the path from the style's src.
-				$path = perflab_aea_get_path_from_resource_url( $style->src );
-				if ( '' === $path ) {
-					continue;
-				}
+			$size = perflab_aea_get_asset_content_length( $src );
+			if ( false !== $size ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]:
```suggestion
			if ( null !== $size ) {
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 6]
```diff
@@ -13,107 +13,109 @@
...
+			if ( ! is_string( $href ) ) {
+				continue;
 			}
 
-			$enqueued_styles[] = array(
-				'src'  => $style->src,
-				'size' => wp_filesize( $path ) + $inline_size,
-			);
+			$size = perflab_aea_get_asset_content_length( $href );
+			if ( false !== $size ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]:
```suggestion
			if ( null !== $size ) {
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 7]
```diff
@@ -13,107 +13,109 @@
...
 		}
-		set_transient( 'aea_enqueued_front_page_styles', $enqueued_styles, 12 * HOUR_IN_SECONDS );
+	}
+
+	if ( 0 !== count( $assets['scripts'] ) ) {
+		set_transient( 'aea_enqueued_front_page_scripts', $assets['scripts'], 12 * HOUR_IN_SECONDS );
+	}
+	if ( 0 !== count( $assets['styles'] ) ) {
+		set_transient( 'aea_enqueued_front_page_styles', $assets['styles'], 12 * HOUR_IN_SECONDS );
 	}
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Shouldn't the transients always be set? Otherwise, if they expire or are not set then this will result in the logic in `perflab_aea_audit_blocking_assets()` being called with every admin page load.

```suggestion
	set_transient( 'aea_enqueued_front_page_scripts', $assets['scripts'], 12 * HOUR_IN_SECONDS );
	set_transient( 'aea_enqueued_front_page_styles', $assets['styles'], 12 * HOUR_IN_SECONDS );
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 8]
```diff
@@ -13,107 +13,109 @@
...
  */
-function perflab_aea_audit_enqueued_scripts(): void {
-	if ( ! is_admin() && is_front_page() && current_user_can( 'view_site_health_checks' ) && false === get_transient( 'aea_enqueued_front_page_scripts' ) ) {
-		global $wp_scripts;
-		$enqueued_scripts = array();
+function perflab_aea_audit_blocking_assets(): void {
+	if (
+		! is_admin() ||
+		! current_user_can( 'view_site_health_checks' ) ||
+		( false !== get_transient( 'aea_enqueued_front_page_scripts' ) && false !== get_transient( 'aea_enqueued_front_page_styles' ) )
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: I think it would make sense to combine these two transients into one `aea_blocking_assets`, or something like that

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 1 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Should we consider a case where a HEAD request does not return a content length due to server configuration? If so, should we then make a GET request?

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Perhaps, but that might be overkill.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 9]
```diff
@@ -293,6 +293,11 @@ function perflab_aea_get_path_from_resource_url( string $resource_url ): string
 		return '';
 	}
 
+	// Remove query string if present.
+	if ( false !== strpos( $resource_url, '?' ) ) {
+		$resource_url = substr( $resource_url, 0, strpos( $resource_url, '?' ) );
+	}
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]:
```suggestion
	$resource_url = preg_replace( '/\?.*/', '', $resource_url );
```

Nevertheless, the `perflab_aea_get_path_from_resource_url()` function isn't being used now anymore, right?

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 10]
```diff
@@ -307,3 +312,28 @@ function perflab_aea_get_path_from_resource_url( string $resource_url ): string
...
+ * @return int|null Returns the content length in bytes or null if it cannot be determined.
+ */
+function perflab_aea_get_asset_content_length( string $resource_url ): ?int {
+	$head_response = wp_remote_head( $resource_url, array( 'timeout' => 10 ) );
+	if ( is_wp_error( $head_response ) || 200 !== wp_remote_retrieve_response_code( $head_response ) ) {
+		return null;
+	}
+
+	$content_length = wp_remote_retrieve_header( $head_response, 'content-length' );
+	if ( is_array( $content_length ) && 0 < count( $content_length ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]:
```suggestion
	if ( is_array( $content_length ) && isset( $content_length[0] ) ) {
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 11]
```diff
@@ -307,3 +312,28 @@ function perflab_aea_get_path_from_resource_url( string $resource_url ): string
...
+		$content_length = $content_length[0];
+	}
+	if ( ! is_string( $content_length ) || '' === $content_length || ! ctype_digit( $content_length ) || 0 === (int) $content_length ) {
+		return null;
+	}
+
+	return (int) $content_length;
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Could this be simplified?

```suggestion
	$content_length = (int) $content_length;
	if ( $content_length <= 0 ) {
		return null;
	}
	return $content_length;
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 12]
```diff
@@ -293,6 +293,11 @@ function perflab_aea_get_path_from_resource_url( string $resource_url ): string
 		return '';
 	}
 
+	// Remove query string if present.
+	if ( false !== strpos( $resource_url, '?' ) ) {
+		$resource_url = substr( $resource_url, 0, strpos( $resource_url, '?' ) );
```
Comment (b1ink0) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Does it make sense to remove the function `perflab_aea_get_path_from_resource_url` entirely, as a HEAD request is now made for local assets as well?

https://github.com/WordPress/performance/blob/8856a14d271497ca3e223b52a99c9682179abf37/plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php#L281-L291

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 13]
```diff
@@ -13,107 +13,104 @@
...
+	}
+
+	$response = wp_remote_get(
+		home_url( '/' ),
+		array(
+			'timeout' => 10,
+			'headers' => array(
+				'Accept'        => 'text/html',
+				'Cache-Control' => 'no-cache',
+			),
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: If the site has HTTP Basic auth, then these can be copied in the request headers. This is done in core in the plugin/theme file editors.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php (hunk 9 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Yes its not being used anymore I just put comment about it here https://github.com/WordPress/performance/pull/2059#discussion_r2169768725.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 14]
```diff
@@ -13,107 +13,104 @@
...
-				'size' => wp_filesize( $path ) + $inline_size,
-			);
-
-		}
-		set_transient( 'aea_enqueued_front_page_scripts', $enqueued_scripts, 12 * HOUR_IN_SECONDS );
-	}
-}
-add_action( 'wp_footer', 'perflab_aea_audit_enqueued_scripts', PHP_INT_MAX );
+			// Skip external script with a "type" attribute set to "module" as they are deferred by default.
+			if ( is_string( $type ) && '' !== $type && 'module' === strtolower( $type ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Simpler:

```suggestion
			if ( 'module' === strtolower( (string) $type ) ) {
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 15]
```diff
@@ -13,107 +13,104 @@
...
-function perflab_aea_audit_enqueued_styles(): void {
-	if ( ! is_admin() && is_front_page() && current_user_can( 'view_site_health_checks' ) && false === get_transient( 'aea_enqueued_front_page_styles' ) ) {
-		global $wp_styles;
-		$enqueued_styles = array();
-		foreach ( $wp_styles->done as $handle ) {
-			$style = $wp_styles->registered[ $handle ];
-
-			if ( ! $style->src || false !== strpos( $style->src, 'wp-includes' ) ) {
+			// Skip external script with a "type" attribute that is not JavaScript.
+			if ( is_string( $type ) && '' !== $type && 'text/javascript' !== strtolower( $type ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]:
```suggestion
			if ( 'text/javascript' !== strtolower( (string) $type ) ) {
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 16]
```diff
@@ -13,107 +13,104 @@
...
+			$size = perflab_aea_get_asset_content_length( $src );
+			if ( null !== $size ) {
+				$assets['scripts'][] = array(
+					'src'  => $src,
+					'size' => $size,
+				);
+			}
+		} elseif ( 'LINK' === $tag ) {
+			$rel = $processor->get_attribute( 'rel' );
+			if ( ! is_string( $rel ) || 'stylesheet' !== strtolower( $rel ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]:
```suggestion
			if ( 'stylesheet' !== strtolower( (string) $rel ) ) {
```

Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: There is another special case to consider here, and that is a classic hack for non-blocking stylesheets. 

This is commonly implemented by adding `media="print"` and `onload="this.media = 'screen'"`:

https://www.filamentgroup.com/lab/load-css-simpler/
https://scottjehl.com/posts/async-css-already/

So this case can be accounted for as well. Namely, this can just skip considering any stylesheets which have a `media` attribute that begins with anything other than `all` or `screen`.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 15 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Here, it is necessary to keep `'' !== $type` since an empty string value for `type` is considered valid in JavaScript.

Then it can be done like this:
```suggestion
			if ( '' !== $type && 'text/javascript' !== strtolower( (string) $type ) ) {
```

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Okay, this change breaks things because the `get_attribute` method returns `null` when the attribute is not present. Therefore, a `null !== $type` check or the previous `is_string( $type )` check needs to be added explicitly.

which check would be better?

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: > Here, it is necessary to keep `'' !== $type` since an empty string value for `type` is considered valid in JavaScript.

Right, this is executed:

```html
<script type>document.write('hello');</script>
```

There's also this code in core which is relevant here:

https://github.com/WordPress/wordpress-develop/blob/27233a0a3b00cc5d683080722711bca15970fe8c/src/wp-includes/script-loader.php#L2948-L2958

With the HTML API, the tag would be JavaScript if:

1. The `type` attribute is absent (`$type === null`)
2. The `type` attribute is boolean and has no value (`$type === true`)
3. The `type` attribute is an empty string (`$type === ''`), but not if the value has whitespace in which case it is _not_ executed.
4. The `type` attribute contains `javascript`, `ecmascript`, `jscript`, or `livescript`.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php (hunk 12 above)
Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Yes, I think the function can be removed.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 15 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Done in https://github.com/WordPress/performance/pull/2059/commits/fc7a9a29995d9eb794a665683c28035d0b7e33f6.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php (hunk 12 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Done in https://github.com/WordPress/performance/pull/2059/commits/80e08efcbc017093f1b593c929e95ccb8a15a471.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 1 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: One thing I noticed is that most servers will send a gzipped response, and when the response is compressed, most servers will not add a Content-Length header. One solution I found for this is to add the header `Accept-Encoding: identity`, which tells the server not to compress the response.

I tested this on some site assets for WordPress.com ([https://s1.wp.com/wp-content/plugins/gutenberg-core/v20.6.0/build/block-library/style.css?m=1744959081i\&cssminify=yes](https://s1.wp.com/wp-content/plugins/gutenberg-core/v20.6.0/build/block-library/style.css?m=1744959081i&cssminify=yes)). It worked and returned a Content-Length header. However, for Kinsta.com ([https://kinsta.com/wp-content/themes/kinsta/dist/blocks.css](https://kinsta.com/wp-content/themes/kinsta/dist/blocks.css)), it did not work. It seems like its assets are served through Cloudflare, which could be the reason for not adding the Content-Length header.

So, actually, I think we do need to fetch the assets and measure their actual size as a fallback.

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: OK, sounds good. In that case, let's not do the `HEAD` request at all and only do `GET`. The assets should all be relatively small (a few hundred KB at maximum), so it shouldn't be a problem to just go ahead and download them to check the byte size of the body.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 16 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Done in https://github.com/WordPress/performance/pull/2059/commits/f582186c4bd0c8dc5a5281d400fc8c073f071e17.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 1 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Done in https://github.com/WordPress/performance/pull/2059/commits/aa50fe48043b1efc544efaaba98285580ef93c3b.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 13 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Done in https://github.com/WordPress/performance/pull/2059/commits/b19371ce9ec0cc1460d86edce5ea0a47b5e73754.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 17]
```diff
@@ -249,10 +249,10 @@ function perflab_aea_get_total_size_bytes_enqueued_scripts() {
  * @return int|false Number of total styles or false if transient hasn't been set.
  */
 function perflab_aea_get_total_enqueued_styles() {
-	$enqueued_styles      = false;
-	$list_enqueued_styles = get_transient( 'aea_enqueued_front_page_styles' );
-	if ( is_array( $list_enqueued_styles ) ) {
-		$enqueued_styles = count( $list_enqueued_styles );
+	$enqueued_styles = false;
+	$blocking_assets = get_transient( 'aea_blocking_assets' );
+	if ( is_array( $blocking_assets ) && isset( $blocking_assets['styles'] ) && is_array( $blocking_assets['styles'] ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Minor suggestion, I believe this can be simplified to:

```suggestion
	if ( isset( $blocking_assets['styles'] ) && is_array( $blocking_assets['styles'] ) ) {
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 18]
```diff
@@ -228,11 +228,11 @@ function perflab_aea_get_total_enqueued_scripts() {
  * @return int|false Byte Total size or false if transient hasn't been set.
  */
 function perflab_aea_get_total_size_bytes_enqueued_scripts() {
-	$total_size            = false;
-	$list_enqueued_scripts = get_transient( 'aea_enqueued_front_page_scripts' );
-	if ( is_array( $list_enqueued_scripts ) ) {
+	$total_size      = false;
+	$blocking_assets = get_transient( 'aea_blocking_assets' );
+	if ( is_array( $blocking_assets ) && isset( $blocking_assets['scripts'] ) && is_array( $blocking_assets['scripts'] ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]:
```suggestion
	if ( isset( $blocking_assets['scripts'] ) && is_array( $blocking_assets['scripts'] ) ) {
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 19]
```diff
@@ -265,11 +265,11 @@ function perflab_aea_get_total_enqueued_styles() {
  * @return int|false Byte Total size or false if transient hasn't been set.
  */
 function perflab_aea_get_total_size_bytes_enqueued_styles() {
-	$total_size           = false;
-	$list_enqueued_styles = get_transient( 'aea_enqueued_front_page_styles' );
-	if ( is_array( $list_enqueued_styles ) ) {
+	$total_size      = false;
+	$blocking_assets = get_transient( 'aea_blocking_assets' );
+	if ( is_array( $blocking_assets ) && isset( $blocking_assets['styles'] ) && is_array( $blocking_assets['styles'] ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]:
```suggestion
	if ( isset( $blocking_assets['styles'] ) && is_array( $blocking_assets['styles'] ) ) {
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 20]
```diff
@@ -279,31 +279,50 @@ function perflab_aea_get_total_size_bytes_enqueued_styles() {
...
+		return null;
 	}
 
-	// wp-content in a subdirectory. ex. /blog/wp-content/.
-	$site_url = untrailingslashit( site_url() );
-	if ( 0 === strpos( $resource_url, $site_url ) ) {
-		return untrailingslashit( ABSPATH ) . substr( $resource_url, strlen( $site_url ) );
+	$body = wp_remote_retrieve_body( $response );
+	if ( '' === $body ) {
+		return null;
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Could it be that the body length is actually zero in this case?

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 21]
```diff
@@ -279,31 +279,50 @@ function perflab_aea_get_total_size_bytes_enqueued_styles() {
...
+ * @since n.e.x.t
+ *
+ * @param array<string, mixed> $headers Headers to copy to.
+ * @return array<string, mixed> Headers with copied Basic auth headers.
+ */
+function perflab_aea_copy_basic_auth_headers( array $headers ): array {
+	$basic_auth_header = sanitize_text_field( wp_unslash( $_SERVER['HTTP_AUTHORIZATION'] ?? '' ) );
+	if ( str_starts_with( $basic_auth_header, 'Basic ' ) ) {
+		$headers['Authorization'] = $basic_auth_header;
+	} elseif ( isset( $_SERVER['PHP_AUTH_USER'] ) && isset( $_SERVER['PHP_AUTH_PW'] ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Is there a need for the `HTTP_AUTHORIZATION` here? I think [`wp_populate_basic_auth_from_authorization_header()`](https://github.com/WordPress/wordpress-develop/blob/972da8c86c7447c9a0571e020ec3e2ffdefdb00d/src/wp-includes/load.php#L97-L139) in core is ensuring that `$_SERVER['PHP_AUTH_USER']` and `$_SERVER['PHP_AUTH_PW']` are set 

Core is just using the [second condition](https://github.com/WordPress/wordpress-develop/blob/972da8c86c7447c9a0571e020ec3e2ffdefdb00d/src/wp-admin/includes/file.php#L545-L548) below, so this could be simplified as follows:

```suggestion
	if ( isset( $_SERVER['PHP_AUTH_USER'] ) && isset( $_SERVER['PHP_AUTH_PW'] ) ) {
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php (hunk 20 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: I’m not understanding what you’re trying to suggest. If you’re referring to cases when an asset has no content and the server returns an empty string, this will ignore such assets. Should these assets still be included in the asset count?

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Yes, but the issue is that a zero-size body would still be a blocking request. 

So I think this condition should be removed.

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Done in https://github.com/WordPress/performance/pull/2059/commits/0be6561da09ef9d04f66c8ed99d3daeb9ec38308.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 1 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: >Sending an HTTP HEAD request for all resources regardless of whether they are on the same origin or not makes sense to me. If the request returns in a 404 then this would be important to report as well.

Now that the GET request is sent, should only 404 errors be added to the report, or should any errors that occur during the request be added to the report?

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: >Once we have the report, then a future enhancement would be digging in to find the theme/plugin responsible for the resource being added in the first place. The AMP plugin implements a lot of this, and it was getting extracted a separate package via https://github.com/GoogleChromeLabs/wp-origination but that effort got stalled and was abandoned. See also https://github.com/WordPress/performance/issues/1095.

So does it make sense to add a table in the blocking scripts/styles site health test showing the origin of each blocking asset, or should this be part of Optimization Detective as you mentioned in #1095?

cc: @westonruter

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 22]
```diff
@@ -279,31 +279,42 @@ function perflab_aea_get_total_size_bytes_enqueued_styles() {
...
+			'timeout' => 10,
+			'headers' => perflab_aea_copy_basic_auth_headers( array() ),
+		)
+	);
 
-	// Different content folder ex. /content/.
-	if ( 0 === strpos( $resource_url, content_url() ) ) {
-		return WP_CONTENT_DIR . substr( $resource_url, strlen( content_url() ) );
+	if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) {
+		return null;
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: What if instead of returning `null` here, it instead returns the `WP_Error` instance if that's what `$response` is, or else to return a new `WP_Error` if the response code is not 200. This could be displayed in the UI then, instead of silently ignoring it. If there is a script on the page that is pointing to a 404, then this would be very important to capture since (1) it would still be a potentially blocking request, (2) a 404 would probably be served by WP which would be relatively very slow compared to serving a static asset.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 23]
```diff
@@ -279,31 +279,42 @@ function perflab_aea_get_total_size_bytes_enqueued_styles() {
...
+/**
+ * Copies HTTP Basic auth headers if present.
+ *
+ * @since n.e.x.t
+ *
+ * @param array<string, mixed> $headers Headers to copy to.
+ * @return array<string, mixed> Headers with copied Basic auth headers.
+ */
+function perflab_aea_copy_basic_auth_headers( array $headers ): array {
+	if ( isset( $_SERVER['PHP_AUTH_USER'] ) && isset( $_SERVER['PHP_AUTH_PW'] ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Shortcut:

```suggestion
	if ( isset( $_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW'] ) ) {
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 24]
```diff
@@ -13,107 +13,121 @@
...
+				)
+			),
+		)
+	);
 
-			if ( ! $script->src || false !== strpos( $script->src, 'wp-includes' ) ) {
-				continue;
-			}
+	if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) {
+		return;
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: A failure here should result in some message in the Site Health test, no?

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 25]
```diff
@@ -13,107 +13,121 @@
...
-				isset( $script->extra['after'] ) &&
-				is_array( $script->extra['after'] )
-			) {
-				foreach ( $script->extra['after'] as $extra ) {
-					$inline_size += ( is_string( $extra ) ) ? mb_strlen( $extra, '8bit' ) : 0;
-				}
-			}
+	$html = wp_remote_retrieve_body( $response );
+	if ( '' === $html ) {
+		return;
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Ditto. If the HTML response is empty, then this here would indicate a problem with the test that could be exposed.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 26]
```diff
@@ -13,107 +13,121 @@
...
 			}
 
-			// Check if we already have the style's path ( part of a refactor for block styles from 5.9 ).
+			// Skip external script with a "type" attribute that is not JavaScript.
 			if (
-				isset( $style->extra['path'] ) &&
-				is_string( $style->extra['path'] ) &&
-				'' !== $style->extra['path']
+				true !== $type &&
+				null !== $type &&
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]:
```suggestion
				is_string( $type ) &&
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 27]
```diff
@@ -13,107 +13,121 @@
...
+				);
+			}
+		} elseif ( 'LINK' === $tag ) {
+			$rel = $processor->get_attribute( 'rel' );
+			if ( 'stylesheet' !== strtolower( (string) $rel ) ) {
+				continue;
+			}
+
+			$media = $processor->get_attribute( 'media' );
+			if ( is_string( $media ) && ! (bool) preg_match( '/^(all|screen)\b/i', $media ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]:
```suggestion
			if ( is_string( $media ) && ! (bool) preg_match( '/^\s*(all|screen)\b/i', $media ) ) {
```

**Review by westonruter — COMMENTED** [review]
Sorry for the delay in reviewing.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 24 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: I have added a new Site Health test in https://github.com/WordPress/performance/pull/2059/commits/a77ab19606b5ce720b76bc8c4e60843e4f901684, which will be triggered when the response is a `WP_Error`, the response code is not equal to `200`, or the body is empty.

I think adding this new test and omitting the other tests is better, as it does not make sense to show two failed tests with the similar messages.

`WP_Error`:
image


Response code is not equal to `200`:
image


Response code is `200` but body is empty:
image

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 25 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: See https://github.com/WordPress/performance/pull/2059#discussion_r2190835160.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php (hunk 22 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: For this, does it make sense to show a table of failed requests with some info about them, or a general list saying there is an issue with the following assets?

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 24 above)
Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Why would this be a new test and not just a unique status for the existing test?

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php (hunk 22 above)
Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Yes, in fact I think it would be good to have a table listing out each blocking asset, including whether it is a script or stylesheet, the URL of the asset, and the size. When there is an error obtaining the asset, this can be indicated in the table for that row.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 1 above)
Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: I think this is related to https://github.com/WordPress/performance/pull/2059#discussion_r2191008174.

I think instead of just saying whether the sum of of the bytes for blocking assets is above a given threshold, that it would be better to list out the assets in a table with a sum at the end. It wouldn't necessarily be able to identify the theme/plugin responsible for adding the script or stylesheet, but in cases where the script/style is bundled with the theme/plugin then this would be obvious.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 24 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: There are two tests: one for styles and one for scripts. When the request to the home page fails, both of these tests will be omitted in the previous logic. There are two ways to display the error: one is to show the message on one of the existing tests, and the other is to show it in a different, new test. In my opinion, the second seems correct. I am open to any new suggestions for other approaches.

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Oh, I think the two test styles and scripts can be combined into one asset test, and the failure will be one of the cases in it.

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Ah, OK. Yes, what you have makes sense.

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Another option would be for there to be just one test for both scripts and styles. This test would be for the "blocking assets" rather than two separate tests for "blocking scripts" and "blocking styles". I don't feel strongly either way.

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Okay, combining them would work.

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Done in https://github.com/WordPress/performance/pull/2059/commits/93e30ac137e733c3213bf44f4aa95e05c0c2973b.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php (hunk 22 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Done in https://github.com/WordPress/performance/pull/2059/commits/6b238545e46d34166aec230d5b5c12a45d4589b2.

image

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Any suggestions on UI @westonruter ?

**Comment by westonruter** [comment]
@b1ink0 Sorry for the delay. Unfortunately, I'm going to be very short on time the next few weeks until WCUS. Hopefully another reviewer can finish providing feedback before I can get back to this. It's looking great though!

**Comment by westonruter** [comment]
I've made a change so that whenever there is an error loading a script/style that this causes the site health test to always be `recommended` even though the number of blocking assets is not above the limit. The reason is that a missing file likely won't be cached, so every page load will have a big penalty with that blocking resource not being in the HTTP cache:

image

Otherwise, in the Twenty Twenty-Five theme, here's what I'm seeing right now for a passing test:

image

When there the number of blocking stylesheets exceeds the threshold:

image

When the loopback request results in a `wp_die()`:

image

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 28]
```diff
@@ -13,40 +13,101 @@
...
+		( isset( $styles_result ) && 'good' !== $styles_result['status'] )
+	) {
+		$result['status']  = 'recommended';
+		$result['actions'] = sprintf(
+			/* translators: 1: HelpHub URL. 2: Link description. 3.URL to clean cache. 4. Clean Cache text. */
+			'<p><a target="_blank" href="%1$s">%2$s</a></p><p><a href="%3$s">%4$s</a></p>',
+			esc_url( __( 'https://wordpress.org/support/article/optimization/', 'performance-lab' ) ),
+			__( 'More info about performance optimization', 'performance-lab' ),
+			esc_url( add_query_arg( 'action', 'clean_aea_audit', wp_nonce_url( admin_url( 'site-health.php' ), 'clean_aea_audit' ) ) ),
+			__( 'Clean Test Cache', 'performance-lab' )
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: I wonder if this action shouldn't always be available? Why only have it available when there is a failure?

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php [hunk 29]
```diff
@@ -13,107 +13,121 @@
...
-		global $wp_scripts;
-		$enqueued_scripts = array();
+function perflab_aea_audit_blocking_assets(): void {
+	if (
+		! is_admin() ||
+		! current_user_can( 'view_site_health_checks' ) ||
+		false !== get_transient( 'aea_blocking_assets' )
+	) {
+		return;
+	}
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Since this request will involve a lot of HTTP requests, potentially, I think it should probably be done in WP Cron, and not just-in-time when a user accesses the admin after the transient has been deleted.

**Review by westonruter — COMMENTED** [review]
@b1ink0 This is so close. I think the main concern I have left is what I commented in https://github.com/WordPress/performance/pull/2059/files#r2249061093.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php (hunk 28 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: It was like this in old tests, but I think keeping it available at all times makes more sense. It provides a quick way to check for blocking assets if user changes something and wants to check, even if the previous test passed.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php (hunk 29 above)
Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Yeah, this could be done. I don’t see any adverse effects. We can use both `admin_init` and WP Cron.

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Shouldn't WP Cron be done only instead of `admin_init`? If `admin_init` is used, then sometimes when someone logs in there will potentially be a dozen or more HTTP requests being made which will slow down the response.

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: What about using the `async_direct_test` and running it only when a user visits the Site Health page?

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Yes, that would be a good alternative. Then there would be no need for the clear link, and there would be no need for the transient either.

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Was there any benefit to using transients in previous tests that we might be missing?

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: I assume the only reason for the transients was to allow for the test results to persist without having to continuously run the test. Maybe there was another reason.

Also, I'm not sure if the async test results factor into the Site Health dashboard widget. Do the async results get stored for the widget to display?

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: >Also, I'm not sure if the async test results factor into the Site Health dashboard widget. Do the async results get stored for the widget to display?

I tested it, and it looks like the async test does appear in the Site Health dashboard widget. However, if the test hasn’t run yet, it doesn’t show up once a user visits Site Health and waits for the async test to complete, it then appears in the widget.

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Good. So the async tests must get cached once they've all run client-side.

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Yes, the async tests are cached using this: https://github.com/WordPress/wordpress-develop/blob/76cfc041a4f5fa8993de52a3877f6028c52fb61a/src/wp-admin/includes/ajax-actions.php#L5454 by this script https://github.com/WordPress/wordpress-develop/blob/76cfc041a4f5fa8993de52a3877f6028c52fb61a/src/js/_enqueues/admin/site-health.js#L238 in core.

Also, the async test could be done using the REST API or Admin AJAX. Currently, core uses the REST API for core async Site Health tests, so should we use AJAX or the REST API? The only difference is that the REST API will require more scaffolding.

Comment (westonruter) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Admin Ajax is fine. I don't see a need to go with the purer approach.

Comment (b1ink0) [reply plugins/performance-lab/includes/site-health/audit-enqueued-assets/hooks.php]: Done in https://github.com/WordPress/performance/pull/2059/commits/69daacb1bf6888462261a8eb9a6661d6e99d70e0.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 30]
```diff
@@ -13,40 +13,212 @@
...
 			'label' => __( 'Performance', 'performance-lab' ),
 			'color' => 'blue',
 		),
+		'description' => '',
+		'actions'     => '',
+		'test'        => 'enqueued_blocking_assets',
+	);
+
+	$audit_result = perflab_aea_audit_blocking_assets();
+	if ( is_wp_error( $audit_result['response'] ) || is_array( $audit_result['response'] ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: It seems this `if` statement is not needed because `$audit_result['response']` is always an `array` or a `WP_Error`.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 31]
```diff
@@ -190,120 +355,285 @@ function perflab_aea_enqueued_css_assets_test(): array {
...
+/**
+ * Generates a table of blocking assets.
+ *
+ * @since n.e.x.t
+ *
+ * @param array{scripts: array<string, mixed>, styles: array<string, mixed>} $blocking_assets Array of blocking assets.
+ * @return string HTML table of blocking assets.
+ */
+function perflab_aea_generate_blocking_assets_table( array $blocking_assets ): string {
+	if ( 0 === count( $blocking_assets ) || ( isset( $blocking_assets['scripts'] ) && 0 === count( $blocking_assets['scripts'] ) && 0 === count( $blocking_assets['styles'] ) ) ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Given that the `scripts` and `styles` keys are always set, this seems it can be simplified down to:

```suggestion
	if ( 0 === count( $blocking_assets['scripts'] ) && 0 === count( $blocking_assets['styles'] ) ) {
```

**Review by westonruter — APPROVED** [review]
@b1ink0 Sorry for the delay in reviewing this. I've made another round of updates. Please review the additional changes, and if you approve, feel free to merge!

File: plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php [hunk 32]
```diff
@@ -6,105 +6,615 @@
...
+	 *
+	 * @covers ::perflab_aea_enqueued_ajax_blocking_assets_test
+	 */
+	public function test_perflab_aea_enqueued_ajax_blocking_assets_test_unauthenticated_with_nonce(): void {
+		$this->add_filter_to_mock_front_page_loopback_request();
+		$_GET['_wpnonce'] = wp_create_nonce( 'health-check-site-status' );
+		$this->expectException( WPAjaxDieContinueException::class );
+		$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
+		$response = json_decode( $this->_last_response, true );
+		$this->assertFalse( $response['success'] );
```
Comment (westonruter) [inline plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php:317]: Todo: verify this assertion is actually getting called, given the exception being thrown above. Do the same in the other tests for this function.

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 33]
```diff
@@ -13,40 +13,235 @@
...
+	$result['description'] .= perflab_aea_generate_blocking_assets_table( $audit_result['assets'] );
+
+	$result['description'] .= $scripts_result['description'];
+	$result['description'] .= $styles_result['description'];
+
+	if (
+		'good' !== $scripts_result['status'] ||
+		'good' !== $styles_result['status']
+	) {
+		$result['label']   = __( 'Your site has may have a problem with blocking assets', 'performance-lab' );
```
Comment (b1ink0) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]:
```suggestion
		$result['label']   = __( 'Your site may have a problem with blocking assets', 'performance-lab' );
```

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 34]
```diff
@@ -96,52 +289,52 @@ function perflab_aea_enqueued_js_assets_test(): array {
...
+ * @since n.e.x.t
  *
- * @return array{label: string, status: string, badge: array{label: string, color: string}, description: string, actions: string, test: string}|array{omitted: true} Result.
+ * @phpstan-param array{
+ *                    scripts: array<array{ src: string, size: int|null, error: WP_Error|null }>,
+ *                    styles: array<array{ src: string, size: int|null, error: WP_Error|null }>,
+ *                } $blocking_assets
+ *
+ * @param array<string, mixed> $blocking_assets Array of blocking assets.
+ * @return array{status: string, description: string} Result.
```
Comment (b1ink0) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]:
```suggestion
 * @return array{status: 'good'|'recommended', description: string} Result.
 ```

File: plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php (hunk 32 above)
Comment (b1ink0) [reply plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php:317]: After testing, I can confirm that everything after `this->_handleAjax` is not getting called it's exiting early. After some digging, I found that if we want to run some assertions afterward, we need to catch the exception manually. 

ref: https://infinum.com/handbook/wordpress/automated-testing-in-wordpress/basic-tests-using-phpunit/integration-testing#:~:text=or%2C%20if%20you%20need%20to%20run%20some%20assertions%20afterward%20you%27d%20catch%20the%20exception%20it%20manually

Like this:
```diff
diff --git a/plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php b/plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php
index 9f2eb1b0..12e88284 100644
--- a/plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php
+++ b/plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php
@@ -299,8 +299,11 @@ class Test_Audit_Enqueued_Assets_Helper extends WP_Ajax_UnitTestCase {
 	public function test_perflab_aea_enqueued_ajax_blocking_assets_test_unauthenticated_with_nonce(): void {
 		$this->add_filter_to_mock_front_page_loopback_request();
 		$_GET['_wpnonce'] = wp_create_nonce( 'health-check-site-status' );
-		$this->expectException( WPAjaxDieContinueException::class );
-		$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
+		try {
+			$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
+		} catch ( WPAjaxDieContinueException $e ) { // phpcs:ignore Generic.CodeAnalysis.EmptyStatement.DetectedCatch
+			// Expected exception for unauthenticated access.
+		}
 		$response = json_decode( $this->_last_response, true );
 		$this->assertFalse( $response['success'] );
 	}

```

File: plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php [hunk 35]
```diff
@@ -6,105 +6,615 @@
...
-	public function test_perflab_aea_get_total_size_bytes_enqueued_scripts(): void {
-		$size_enqueued_scripts = perflab_aea_get_total_size_bytes_enqueued_scripts();
-		$this->assertFalse( $size_enqueued_scripts );
+	public function test_perflab_aea_enqueued_ajax_blocking_assets_test_unauthenticated_without_nonce(): void {
+		$this->add_filter_to_mock_front_page_loopback_request();
+		$this->expectException( WPAjaxDieStopException::class );
+		$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
+		$response = json_decode( $this->_last_response, true );
+		$this->assertArrayHasKey( 'success', $response );
+		$this->assertFalse( $response['success'] );
```
Comment (b1ink0) [inline plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php]: Here, we need to check for `'-1'`, as it seems WordPress returns `'-1'` when no nonce is present. We also need to use `try` and `catch` to check the output see my comment https://github.com/WordPress/performance/pull/2059#discussion_r2281011145.

ref: https://github.com/WordPress/wordpress-develop/blob/197f0a71ad27d0688b6380c869aeaf92addd1451/src/wp-includes/pluggable.php#L1360-L1365

```suggestion
		try {
			$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
		} catch ( WPAjaxDieStopException $e ) {
			$this->assertEquals( '-1', $e->getMessage() );
		}
```

File: plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php [hunk 36]
```diff
@@ -6,105 +6,615 @@
...
+	/**
+	 * Tests perflab_aea_enqueued_ajax_blocking_assets_test
+	 *
+	 * @covers ::perflab_aea_enqueued_ajax_blocking_assets_test
+	 */
+	public function test_perflab_aea_enqueued_ajax_blocking_assets_test_unauthenticated_with_nonce(): void {
+		$this->add_filter_to_mock_front_page_loopback_request();
+		$_GET['_wpnonce'] = wp_create_nonce( 'health-check-site-status' );
+		$this->expectException( WPAjaxDieContinueException::class );
+		$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
```
Comment (b1ink0) [inline plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php]: See https://github.com/WordPress/performance/pull/2059/files#r2281011145.

```suggestion
		try {
			$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
		} catch ( WPAjaxDieContinueException $e ) { // phpcs:ignore Generic.CodeAnalysis.EmptyStatement.DetectedCatch
			// Expected exception for unauthenticated access.
		}
```

File: plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php [hunk 37]
```diff
@@ -6,105 +6,615 @@
...
 	 */
-	public function test_perflab_aea_get_total_enqueued_styles(): void {
-		$total_enqueued_styles = perflab_aea_get_total_enqueued_styles();
-		$this->assertEquals( 0, $total_enqueued_styles );
+	public function test_perflab_aea_enqueued_ajax_blocking_assets_test_unauthorized(): void {
+		$this->add_filter_to_mock_front_page_loopback_request();
+		wp_set_current_user( self::factory()->user->create( array( 'role' => 'subscriber' ) ) );
+		$_GET['_wpnonce'] = wp_create_nonce( 'health-check-site-status' );
+		$this->expectException( WPAjaxDieContinueException::class );
+		$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
```
Comment (b1ink0) [inline plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php]:
```suggestion
		try {
			$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
		} catch ( WPAjaxDieContinueException $e ) { // phpcs:ignore Generic.CodeAnalysis.EmptyStatement.DetectedCatch
			// Expected exception for unauthorized access.
		}
```

File: plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php [hunk 38]
```diff
@@ -6,105 +6,615 @@
...
+	 * Tests perflab_aea_enqueued_ajax_blocking_assets_test
+	 *
+	 * @covers ::perflab_aea_enqueued_ajax_blocking_assets_test
+	 */
+	public function test_perflab_aea_enqueued_ajax_blocking_assets_test_authorized(): void {
+		$this->add_filter_to_mock_front_page_loopback_request();
+		wp_set_current_user( self::factory()->user->create( array( 'role' => 'administrator' ) ) );
+		$_GET['_wpnonce'] = wp_create_nonce( 'health-check-site-status' );
+		$this->expectException( WPAjaxDieContinueException::class );
+		$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
```
Comment (b1ink0) [inline plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php]:
```suggestion
		try {
			$this->_handleAjax( 'health-check-enqueued-blocking-assets-test' );
		} catch ( WPAjaxDieContinueException $e ) { // phpcs:ignore Generic.CodeAnalysis.EmptyStatement.DetectedCatch
			// Expected exception for authorized access.
		}
```

File: plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php (hunk 32 above)
Comment (b1ink0) [reply plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php:317]: I have added fix suggestions for all the AJAX tests please verify them.

Comment (westonruter) [reply plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets-helper.php:317]: @b1ink0 Thanks for digging into that! I've iterated on your suggestions and came up with 46b4df48edd6cbc67878300bf642deb67711ae4c.

**Comment by westonruter** [comment]
Strange. Tests pass for me locally, but they fail on GHA with at `Test_Audit_Enqueued_Assets_Helper::test_perflab_aea_enqueued_ajax_blocking_assets_test_authorized`.

**Comment by b1ink0** [comment]
> Strange. Tests pass for me locally, but they fail on GHA with at `Test_Audit_Enqueued_Assets_Helper::test_perflab_aea_enqueued_ajax_blocking_assets_test_authorized`.

I tested locally, and the tests fail on the multisite test `test-php-multisite:performance-lab` locally as well.

**Comment by westonruter** [comment]
@b1ink0 Ah, so we would need to create a superadmin for the test to pass successfully I bet, since Site Health is not available except in the network admin, as I recall.

**Comment by westonruter** [comment]
These pains with Ajax testing make me realize that in the future we should go with using the REST API for Site Health tests instead 😅

**Comment by westonruter** [comment]
@b1ink0 Nice. And that fixed coverage to be 100% for that file.
