### PR TITLE
Do not show admin pointer on the Performance screen and dismiss the pointer when visited

### LINKED ISSUE #1135: Setting screen tooltip should go away after visiting the settings page
## Bug Description

The tool tip guiding users to the settings page shows even after they visit it. Instead, it should go away as if "Dismiss" was clicked.

This tooltip pops up when the user installs the plugin so they can more easily find the settings screen:

image

Once the user clicks the "Settings > Performance" link in the tooltip, or otherwise visits the settings page, we should no longer show the tooltip.

## Steps to reproduce

1. Install the plugin
2. Click "Settings > Performance" in the tooltip to visit the settings page
3. Go back and visit the Dashboard

Expected results: the tooltip should no longer show
Actual results: the tooltip is still showing

### PR DESCRIPTION
**Pull request by Ellusu**
## Summary

Fixes: #1135

## Relevant technical choices

I added the possibility to set the value of dismissed_wp_pointers at the beginning of the function if we are already in the plugin settings page.

I had to set $current_user at the beginning of the function

### CODE REVIEW

File: includes/admin/load.php [hunk 1]
```diff
@@ -77,7 +77,16 @@ function perflab_render_settings_page() {
  * @param string $hook_suffix The current admin page.
  */
 function perflab_admin_pointer( $hook_suffix ) {
+	$current_user = get_current_user_id();
+
 	if ( ! in_array( $hook_suffix, array( 'index.php', 'plugins.php' ), true ) ) {
+
+		// Do not show on the settings page and dismiss the pointer
```
Comment (mukeshpanchal27) [inline includes/admin/load.php]:
```suggestion
		// Do not show on the settings page and dismiss the pointer.
```

File: includes/admin/load.php [hunk 2]
```diff
@@ -77,7 +77,16 @@ function perflab_render_settings_page() {
...
+		if ( !empty( $_GET['page'] ) && $_GET['page'] === PERFLAB_SCREEN ) {
```
Comment (mukeshpanchal27) [inline includes/admin/load.php]:
```suggestion
		if ( ! empty( $_GET['page'] ) && PERFLAB_SCREEN === $_GET['page'] ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
```

File: includes/admin/load.php [hunk 3]
```diff
@@ -86,7 +95,6 @@ function perflab_admin_pointer( $hook_suffix ) {
 		return;
 	}
 
-	$current_user = get_current_user_id();
 	$dismissed    = explode( ',', (string) get_user_meta( $current_user, 'dismissed_wp_pointers', true ) );
```
Comment (mukeshpanchal27) [inline includes/admin/load.php]:
```suggestion
	$dismissed = explode( ',', (string) get_user_meta( $current_user, 'dismissed_wp_pointers', true ) );
```

**Review by mukeshpanchal27 — COMMENTED** [review]
Thanks @Ellusu, Left some initial feedback for PHPCS fix.

File: includes/admin/load.php [hunk 4]
```diff
@@ -77,7 +77,16 @@ function perflab_render_settings_page() {
...
  */
 function perflab_admin_pointer( $hook_suffix ) {
+	$current_user = get_current_user_id();
+
 	if ( ! in_array( $hook_suffix, array( 'index.php', 'plugins.php' ), true ) ) {
+
+		// Do not show on the settings page and dismiss the pointer.
+		if ( ! empty( $_GET['page'] ) && PERFLAB_SCREEN === $_GET['page'] ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
+			$dismissed[] = 'perflab-admin-pointer';
+			update_user_meta( $current_user, 'dismissed_wp_pointers', implode( ',', $dismissed ) );
```
Comment (adamsilverstein) [inline includes/admin/load.php:96]: wouldn't this overwrite existing dismissed pointers? This probably needs to get the existing list first and append this pointer if it doesn't exist. The core function `wp_ajax_dismiss_wp_pointer` has a good boilerplate for doing this.

File: includes/admin/load.php [hunk 5]
```diff
@@ -77,7 +77,16 @@ function perflab_render_settings_page() {
  * @param string $hook_suffix The current admin page.
  */
 function perflab_admin_pointer( $hook_suffix ) {
+	$current_user = get_current_user_id();
+
 	if ( ! in_array( $hook_suffix, array( 'index.php', 'plugins.php' ), true ) ) {
+
+		// Do not show on the settings page and dismiss the pointer.
```
Comment (adamsilverstein) [inline includes/admin/load.php:93]:
```suggestion
		// Dismiss the admin pointer once the user reaches the settings screen.
```
Docblock update suggestion

**Comment by adamsilverstein** [comment]
Thanks @Ellusu - left a couple of suggestions.

File: includes/admin/load.php (hunk 4 above)
Comment (westonruter) [reply includes/admin/load.php:96]: I think this would be the case if the `$dismissed` assignment line from below is also moved up after setting `$current_user`.

Comment (Ellusu) [reply includes/admin/load.php:96]: thanks @adamsilverstein, @mukeshpanchal27 e @westonruter, made a new commit

File: includes/admin/load.php [hunk 6]
```diff
@@ -77,7 +77,17 @@ function perflab_render_settings_page() {
  * @param string $hook_suffix The current admin page.
  */
 function perflab_admin_pointer( $hook_suffix ) {
+	$current_user = get_current_user_id();
+	$dismissed    = array_filter( explode( ',', (string) get_user_meta( get_current_user_id(), 'dismissed_wp_pointers', true ) ) );
+
 	if ( ! in_array( $hook_suffix, array( 'index.php', 'plugins.php' ), true ) ) {
+
+		// Do not show on the settings page and dismiss the pointer.
+		if ( ! empty( $_GET['page'] ) && PERFLAB_SCREEN === $_GET['page'] && ( ! in_array( 'perflab-admin-pointer', $dismissed, true ) ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
```
Comment (westonruter) [inline includes/admin/load.php]: Minor suggestion based on [prior feedback](https://github.com/WordPress/performance/pull/1091#discussion_r1543908524) to use `isset()` rather than `! empty()`:

```suggestion
		if ( isset( $_GET['page'] ) && PERFLAB_SCREEN === $_GET['page'] && ( ! in_array( 'perflab-admin-pointer', $dismissed, true ) ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
```

**Review by westonruter — APPROVED** [review]
Works for me!

Before:

[Screen recording 2024-04-17 14.32.10.webm](https://github.com/WordPress/performance/assets/134745/4672a1ba-322c-4b35-93f0-e15c782ad823)

After:

[Screen recording 2024-04-17 14.33.11.webm](https://github.com/WordPress/performance/assets/134745/38f7b87c-8b92-472e-afa9-5176817f0fc1)

File: includes/admin/load.php [hunk 7]
```diff
@@ -77,7 +77,17 @@ function perflab_render_settings_page() {
  * @param string $hook_suffix The current admin page.
  */
 function perflab_admin_pointer( $hook_suffix ) {
```
Comment (mukeshpanchal27) [inline includes/admin/load.php:79]:
```
// Do not show admin pointer in multisite Network admin or User admin UI.
if ( is_network_admin() || is_user_admin() ) {
	return;
}
```

Let's check this condition at the top of the function, as the changes do not need to run on multisite.

File: includes/admin/load.php [hunk 8]
```diff
@@ -86,9 +96,6 @@ function perflab_admin_pointer( $hook_suffix ) {
 		return;
 	}
 
-	$current_user = get_current_user_id();
-	$dismissed    = explode( ',', (string) get_user_meta( $current_user, 'dismissed_wp_pointers', true ) );
-
 	if ( in_array( 'perflab-admin-pointer', $dismissed, true ) ) {
 		return;
 	}
```
Comment (mukeshpanchal27) [inline includes/admin/load.php]: Move this check after line no 81 because the update-related condition is checked on all pages, so it is not needed if the pointer is already disabled.

**Review by mukeshpanchal27 — CHANGES_REQUESTED** [review]
Thanks, @Ellusu, for the update. I left some feedback for adjustments to the conditions. Other than that, it looks solid to me.

File: includes/admin/load.php (hunk 7 above)
Comment (Ellusu) [reply includes/admin/load.php:79]: Edit thanks :)

File: includes/admin/load.php (hunk 8 above)
Comment (Ellusu) [reply includes/admin/load.php]: Edit thanks :)

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @Ellusu for the updates. The changes look good to me.
