### PR TITLE
Skip stylesheets with empty href attributes in Site Health audit

### LINKED ISSUE #2278: Enqueued Assets Site Health test not fully accounting for async CSS
See [support topic](https://wordpress.org/support/topic/false-positive-error-in-enqueued-assets-health-check/).

Given a site with the following HTML:

```html
<link rel='stylesheet' id='companion-bundle-css' href="" data-href='http://example.com/style.css' type='text/css' media='all' />
```

This is showing up as an error:

Image

Note that the audit currently is accounting for async CSS whereby the `media` is set to something other than `screen` or `all`:

https://github.com/WordPress/performance/blob/f7846e4d3d11c0ae3bac04926c71904e8d299c76/plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php#L110-L132

Normally this is accompanied by an `onload` attribute on the `LINK` tag to rewrite the `media` to `screen` from something like `print` when the stylesheet has loaded.

We should also account for this case where the `href` is empty.

### PR DESCRIPTION
**Pull request by theaminulai**
### What:
Skip stylesheet link elements that have empty `href` attributes during the Enqueued Assets Health Check audit.

### Why:
Some themes and plugins (like Mesmerize Companion) intentionally use empty `href` attributes with `data-href` attributes as a performance optimization technique to defer CSS loading. These stylesheets are non-render-blocking by design, but were being incorrectly flagged as errors ("A valid URL was not provided") in the Site Health Status, negatively impacting site scores.

### How:
Added a check for empty string `href` values in `perflab_aea_audit_blocking_assets()`. The condition now reads:
```php
if ( ! is_string( $href ) ) {
	continue;
}
$href = trim( $href );
if ( '' === $href ) {
	continue;
}
```

This skips stylesheets with href="" from being audited, similar to how async CSS with non-standard media attributes is already excluded.

### Files changed:

[helper.php](https://github.com/WordPress/performance/tree/trunk/plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php)

### Fixes #2278

### CODE REVIEW

File: plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php [hunk 1]
```diff
@@ -119,7 +119,7 @@ function perflab_aea_audit_blocking_assets(): array {
 			}
 
 			$href = $processor->get_attribute( 'href' );
-			if ( ! is_string( $href ) ) {
+			if ( ! is_string( $href ) || '' === $href ) {
```
Comment (westonruter) [inline plugins/performance-lab/includes/site-health/audit-enqueued-assets/helper.php]: Maybe worthwhile to remove whitespace:

```suggestion
			if ( ! is_string( $href ) || '' === trim( $href ) ) {
```

**Comment by westonruter** [comment]
Thank you for the PR. Let's also update [the unit test](https://github.com/WordPress/performance/blob/b353ecb080bdb0c35062cfe8b300e4ae63a825b2/plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets.php#L153-L245) to add an assertion for this change.

**Comment by theaminulai** [comment]
## Test Added

I've added test coverage for the empty `href` attribute fix in the `test_perflab_aea_audit_enqueued_styles()` test method.

### What the test does:
- Enqueues a stylesheet with `style-empty-href` handle
- Verifies that this stylesheet is properly skipped from the audit and doesn't appear in the results

### Test assertion:
```php
$empty_href_style = array_filter(
	$assets['styles'],
	static function ( $item ) {
		return 'https://empty-href-style.com' === $item['src'];
	}
);
$this->assertEmpty( $empty_href_style );
```
This ensures that themes/plugins using performance optimization techniques with href="" won't trigger false positives in Site Health checks.

Thanks to @westonruter for the valuable feedback on implementing this test case! 

### Files changed: 
[test-audit-enqueued-assets.php](https://github.com/WordPress/performance/blob/trunk/plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets.php)

File: plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets.php [hunk 2]
```diff
@@ -176,6 +182,14 @@ static function ( $tag, $handle ) {
 				if ( 'style-no-href' === $handle ) {
 					$tag = str_replace( 'href=\'https://no-href-style.com\'', ' ', $tag );
 				}
+
+				if ( 'style-empty-href' === $handle ) {
+					$tag = str_replace(
+						'href=\'https://empty-href-style.com\'',
+						"href=''",
+						$tag
+					);
```
Comment (westonruter) [inline plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets.php:181]: Let's use the HTML Tag Processor for this as it is more robust than doing a replacement.

Comment (westonruter) [reply plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets.php:181]: Done in 65b274652246acc467d702f44cf59aa9b65d1f41

File: plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets.php [hunk 3]
```diff
@@ -168,13 +168,29 @@ public function test_perflab_aea_audit_enqueued_styles(): void {
...
+					$tag = $processor->get_updated_html();
+				} elseif ( 'style-empty-href' === $handle ) {
+					$processor = new WP_HTML_Tag_Processor( $tag );
+					$this->assertTrue( $processor->next_tag( 'LINK' ), 'Expected a LINK to be present.' );
+					$this->assertSame( 'stylesheet', $processor->get_attribute( 'rel' ), 'Expected LINK to be a stylesheet.' );
+					$processor->set_attribute( 'href', '' );
+					$tag = $processor->get_updated_html();
 				}
 				return $tag;
 			},
```
[the remark this answers is not in the document]
Comment (westonruter) [reply plugins/performance-lab/tests/includes/site-health/audit-enqueued-assets/test-audit-enqueued-assets.php:185]: No, thanks.

**Review by westonruter — APPROVED** [review]
