### PR TITLE
Prevent URL in `Link` header from including invalid characters

### LINKED ISSUE #1775: Optimization detective can return non-ascii characters in the Link header, breaking some reverse proxies and HTTP standards.
## Bug Description

Optimization detective can return non-ascii characters in the Link header, breaking some reverse proxies and HTTP standards.

## Steps to reproduce

Example link with Hebrew chars: `https://testsite.com/wp-content/uploads/2025/01/חנות-scaled.avif`
If this is added to optimization detection, for example via image prioritizer, it will cause the response header of the page to include:
```
Link: <https://testsite.com/wp-json/>; rel="https://api.w.org/", <https://testsite.com/wp-json/wp/v2/pages/1234>; rel="alternate"; title="JSON"; type="application/json", <https://testsite.com/wp-content/uploads/2025/01/חנות-scaled.avif>; rel="preload"; fetchpriority="high"; as="image"; media="screen and (max-width: 480px)"
```

HTTP headers should contain only  ISO-8859-1 chars and this breaks it, the url path should be encoded.

### PR DESCRIPTION
**Pull request by AhmarZaidi**
## Summary

This PR addresses an issue where non-ASCII characters in URL filenames caused HTTP headers to break reverse proxies and violate standards. The solution encodes only the filename part of URLs, ensuring compliance with ISO-8859-1 character requirements. This change maintains URL integrity while preventing potential issues with reverse proxies.

Example URL   : `https://testsite.com/wp-content/uploads/2025/01/חנות-scaled.avif`
Corrected URL: `https://testsite.com/wp-content/uploads/2025/01/%D7%97%D7%A0%D7%95%D7%AA-scaled.avif`

Fixes #1775 

## Relevant technical choices

- Implemented a solution to address the issue where non-ASCII characters in URLs, such as Hebrew characters in filenames, were causing HTTP headers to break reverse proxies and violate HTTP standards.
- Updated the URL encoding logic to use a regular expression that matches any character not allowed by RFC 3986, ensuring that all non-ASCII and disallowed ASCII characters are percent-encoded.
- Implemented preg_replace_callback() with a static closure to dynamically encode characters using rawurlencode(). This ensures that only characters outside the allowed set are encoded.
- Add test cases to include international domain names, non-ASCII paths, and URLs with special characters.

### CODE REVIEW

File: plugins/optimization-detective/class-od-link-collection.php [hunk 1]
```diff
@@ -248,9 +248,33 @@ public function get_response_header(): ?string {
...
-			// The about:blank is present since a Link without a reference-uri is invalid so any imagesrcset would otherwise not get downloaded.
-			$link['href'] = isset( $link['href'] ) ? esc_url_raw( $link['href'] ) : 'about:blank';
-			$link_header  = '<' . $link['href'] . '>';
+			// Encode only the filename part of the URL to ensure it contains only ASCII characters.
+			if ( isset( $link['href'] ) ) {
+				$parsed_url = wp_parse_url( $link['href'] );
+				if ( isset( $parsed_url['path'] ) ) {
+					$path_segments        = explode( '/', $parsed_url['path'] );
+					$last_segment         = array_pop( $path_segments );
+					$encoded_last_segment = rawurlencode( $last_segment );
```
Comment (westonruter) [inline plugins/optimization-detective/class-od-link-collection.php]: Should this conditionally only encode the `$last_segment` if it contains any characters which are not ASCII?

File: plugins/optimization-detective/class-od-link-collection.php [hunk 2]
```diff
@@ -248,9 +248,33 @@ public function get_response_header(): ?string {
...
+					$host   = isset( $parsed_url['host'] ) ? $parsed_url['host'] : '';
+
+					$link['href'] = esc_url_raw( $scheme . '://' . $host . $encoded_path );
+
+					// Append query and fragment if they exist.
+					$link['href'] .= isset( $parsed_url['query'] ) ? '?' . $parsed_url['query'] : '';
+					$link['href'] .= isset( $parsed_url['fragment'] ) ? '#' . $parsed_url['fragment'] : '';
+				} else {
+					$link['href'] = esc_url_raw( $link['href'] );
+				}
```
Comment (westonruter) [inline plugins/optimization-detective/class-od-link-collection.php]: Instead of parsing the URL and then re-constructing it, what if you just check if the `href` has any non-ASCII chars and then encode the entire URL?

```suggestion
				if ( 1 === preg_match( '/[^\x20-\x7E]/', $link['href'] ) ) {
					$link['href'] = rawurlencode( urldecode( $link['href'] ) );
				} else {
					$link['href'] = esc_url_raw( $link['href'] );
				}
```

The regular expression range there is to match everything from a space to a tilde. This might not be the right range.

**Review by westonruter — COMMENTED** [review]
Thanks for the PR! I left a couple alternative suggestions.

Please add some test coverage for the lines not covered be tests.

**Comment by westonruter** [comment]
> The solution encodes only the filename part of URLs

What about when an internationalized domain name is used? Couldn't this also cause problems with encoding?

**Comment by westonruter** [comment]
Additionally, on multisite subdirectory installs, in theory the path before `wp-content` could also include non-ASCII chars:

```
https://testsite.com/חנות/wp-content/uploads/2025/01/example-scaled.avif
```

**Comment by westonruter** [comment]
@AhmarZaidi Hey, are you intending to pick this up again?

**Comment by AhmarZaidi** [comment]
@westonruter Yes, I'll be working on the changes right away.

**Comment by AhmarZaidi** [comment]
> Instead of parsing the URL and then re-constructing it, what if you just check if the href has any non-ASCII chars and then encode the entire URL

@westonruter I've implemented the changes: If the path contains any non-ascii characters then we encode the whole URL.

However we can use `preg_replace_callback` to encode only the non-ascii characters in the URL. Let me know if that approach will be better.

File: plugins/optimization-detective/class-od-link-collection.php (hunk 2 above)
Comment (AhmarZaidi) [reply plugins/optimization-detective/class-od-link-collection.php]: Changed the regex to match any non-ascii characters

**Comment by westonruter** [comment]
What you did looks good. Could you add some test cases for international domain names and non-ASCII paths to ensure the expected output?

**Comment by AhmarZaidi** [comment]
@westonruter The old solution was encoding the `://` part also, so I've update the code slightly.
**Current solution:** Encode complete url after `://` part.

**Potential Issue:** This solution converts the slashes (`/`) to `%2F` so the file path would be incorrect.
For example `https://xn--fsq.com/תמונה.jpg` will be encoded to `https://xn--fsq.com%2F%D7%AA%D7%9E%D7%95%D7%A0%D7%94.jpg`
Note: I've written the tests according to the above output.

---

If we use something like:
```
$decoded_url = urldecode( $link['href'] );
$encoded_url = preg_replace_callback(
        '/[^\x00-\x7F]/',
        fn( $matches ) => rawurlencode( $matches[0] ),
        $decoded_url
);
```
Then `https://xn--fsq.com/תמונה.jpg` will be encoded to `https://xn--fsq.com/%D7%AA%D7%9E%D7%95%D7%A0%D7%94.jpg`

Please feel free to let me know if we should do any further changes to the approach.

**Comment by westonruter** [comment]
> If we use something like:

That looks good!

**Comment by AhmarZaidi** [comment]
Implemented the changes.

**Comment by westonruter** [comment]
So this is no longer a draft and is ready for review, correct?

File: plugins/optimization-detective/class-od-link-collection.php [hunk 3]
```diff
@@ -255,9 +255,24 @@ public function get_response_header(): ?string {
 		$link_headers = array();
 
 		foreach ( $this->get_prepared_links() as $link ) {
-			// The about:blank is present since a Link without a reference-uri is invalid so any imagesrcset would otherwise not get downloaded.
-			$link['href'] = isset( $link['href'] ) ? esc_url_raw( $link['href'] ) : 'about:blank';
-			$link_header  = '<' . $link['href'] . '>';
+			if ( isset( $link['href'] ) ) {
+				$decoded_url = urldecode( $link['href'] );
```
Comment (westonruter) [inline plugins/optimization-detective/class-od-link-collection.php:259]: Questioning whether `rawurldecode()` should be used here, but I think it makes sense. The `urldecode()` function will decode `+` as a space in addition to any percent-encoded chars. Then below it re-encodes using `rawurlencode()` to ensure only percent-encoding is used according to RFC 3986.

File: plugins/optimization-detective/class-od-link-collection.php [hunk 4]
```diff
@@ -255,9 +255,24 @@ public function get_response_header(): ?string {
...
+
+				// Encode only non-ASCII characters.
+				$encoded_url  = preg_replace_callback(
+					'/[^\x00-\x7F]/',
```
Comment (westonruter) [inline plugins/optimization-detective/class-od-link-collection.php]: It looks like this isn't the right range. For example, there are ASCII characters which are not allowed in URLs, for example `NULL` bytes (`\x00`) or `ESC` (`\x27`). 

See the [reserved characters](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) and [unreserved characters](https://datatracker.ietf.org/doc/html/rfc3986#section-2.3).

So it seems that any character not among the following set specifically should be percent-encoded:

```
gen-delims = ":" / "/" / "?" / "#" / "[" / "]" / "@"
sub-delims = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
```

File: plugins/optimization-detective/tests/test-class-od-link-collection.php [hunk 5]
```diff
@@ -335,6 +335,57 @@ public function data_provider_to_test_add_link(): array {
 				'expected_count'  => 0,
 				'error'           => 'Maximum width must be greater than zero and greater than the minimum width.',
 			),
+			'international_domain_name'                  => array(
+				'links_args'      => array(
+					array(
+						array(
+							'rel'  => 'preload',
+							'href' => 'https://xn--fsq.com/תמונה.jpg',
```
Comment (westonruter) [inline plugins/optimization-detective/tests/test-class-od-link-collection.php]: Can you add a non-punycode example as well? So instead of `https://xn--fsq.com/תמונה.jpg` this could be:

```suggestion
							'href' => 'https://例.com/תמונה.jpg',
```

But also, let's use IDN subdomains for canonical subdomains. So all the `xn--fsq.com` domains being tested here can be replaced with `xn--fsq.example.com`

File: plugins/optimization-detective/tests/test-class-od-link-collection.php [hunk 6]
```diff
@@ -335,6 +335,57 @@ public function data_provider_to_test_add_link(): array {
...
+				'expected_header' => 'Link: <https://example.com/%D7%97%D7%A0%D7%95%D7%AA/%D7%AA%D7%9E%D7%95%D7%A0%D7%94.jpg>; rel="preload"; as="image"',
+				'expected_count'  => 1,
+				'error'           => '',
+			),
+			'multisite_subdirectory_non_ascii'           => array(
+				'links_args'      => array(
+					array(
+						array(
+							'rel'  => 'preload',
+							'href' => 'https://example.com/חנות/wp-content/uploads/2025/01/example.jpg',
```
Comment (westonruter) [inline plugins/optimization-detective/tests/test-class-od-link-collection.php]: Let's add some tests for other characters in the URL to make sure they are re-encoded as expected, for example:

```suggestion
							'href' => 'https://example.com/חנות/wp-content/uploads/2025/01/example.jpg?ver=1+2',
```

**Review by westonruter — CHANGES_REQUESTED** [review]

**Comment by westonruter** [comment]
> Relevant technical choices

Could you update the description based on the latest revisions?

File: plugins/optimization-detective/class-od-link-collection.php (hunk 3 above)
Comment (AhmarZaidi) [reply plugins/optimization-detective/class-od-link-collection.php:259]: I also feel that using urldecode() is appropriate because it converts percent-encoded characters back to their original form, ensuring consistent URL processing. It also interprets + as a space, aligning with query string encoding, before re-encoding with rawurlencode().

File: plugins/optimization-detective/class-od-link-collection.php (hunk 4 above)
Comment (AhmarZaidi) [reply plugins/optimization-detective/class-od-link-collection.php]: I've changed it to a negation set like this: `'/[^A-Za-z0-9\-._~:\/?#\[\]@!$&\'()*+,;=%]/'`
```
- [^...]: Negated character class.

- A-Za-z0-9: Uppercase or lowercase English letter and any digit.

- \-._~: Unreserved characters: hyphen -, period ., underscore _, and tilde ~. 

- :\/?#\[\]@: Gen-delims: colon :, forward slash /, question mark ?, hash #, square brackets [ and ], and at symbol @.

- !$&\'()*+,;=: Sub-delims: exclamation mark !, dollar sign $, ampersand &, single quote ', parentheses ( and ), asterisk *, plus +, comma ,, semicolon ;, and equals sign =.

- %: Percent sign %, used in percent-encoded characters in URLs.
```

File: plugins/optimization-detective/tests/test-class-od-link-collection.php (hunk 6 above)
Comment (AhmarZaidi) [reply plugins/optimization-detective/tests/test-class-od-link-collection.php]: Added

File: plugins/optimization-detective/tests/test-class-od-link-collection.php (hunk 5 above)
Comment (AhmarZaidi) [reply plugins/optimization-detective/tests/test-class-od-link-collection.php]: Updated

File: plugins/optimization-detective/class-od-link-collection.php [hunk 7]
```diff
@@ -255,9 +255,24 @@ public function get_response_header(): ?string {
...
 		foreach ( $this->get_prepared_links() as $link ) {
-			// The about:blank is present since a Link without a reference-uri is invalid so any imagesrcset would otherwise not get downloaded.
-			$link['href'] = isset( $link['href'] ) ? esc_url_raw( $link['href'] ) : 'about:blank';
-			$link_header  = '<' . $link['href'] . '>';
+			if ( isset( $link['href'] ) ) {
+				$decoded_url = urldecode( $link['href'] );
+
+				// Encode characters not allowed in a URL per RFC 3986 (anything that is not among the reserved and unreserved characters).
+				$encoded_url  = preg_replace_callback(
+					'/[^A-Za-z0-9\-._~:\/?#\[\]@!$&\'()*+,;=%]/',
```
Comment (westonruter) [inline plugins/optimization-detective/class-od-link-collection.php]:
```suggestion
					'/[^A-Za-z0-9\-._~:\/?#\[\]@!$&\'()*+,;=]/',
```

> - %: Percent sign %, used in percent-encoded characters in URLs.

Is a `%` correct here? The use of `urldecode()` should have already eliminated any % signs. Therefore, any remaining percent characters would be part of strings that aren't in an encoding, right? I added a failing test case that shows what should be expected but isn't currently the result: b1ed4c1cc77c7f7f3d9c3e75bdc8010e6fea8ce7

If the `%` is removed from this pattern, then the test is fixed.

Comment (AhmarZaidi) [reply plugins/optimization-detective/class-od-link-collection.php]: Right, completely missed that 😅

I've removed the % from the regex since urldecode() should handle any encoded characters.

**Review by westonruter — APPROVED** [review]
Thank you!

@felixarntz Anything we missed here?

**Review by felixarntz — APPROVED** [review]
Thank you for the PR @AhmarZaidi, LGTM!

**Comment by westonruter** [comment]
We forgot about the URLs in the `imagesrcset`. I've opened https://github.com/WordPress/performance/pull/1866 to fix that.

**Comment by westonruter** [comment]
Follow-up issue: https://github.com/WordPress/performance/issues/1906
