### PR TITLE
Replace the featured image with WebP version when available

### LINKED ISSUE #288: Background images does not uses the `*.webp` version in the content if present
## Bug Description
Some time ago i developed a small simple website with gutenberg & generatepress. i tried to use as many default blocks as possible.
Now i tried the performance plugin to support the great initiative to move to webp as also other platforms are doing the same as shopify and wix...

webps are generated correctly which i checked based on this request: https://wordpress.slack.com/archives/C02KGN5K076/p1649596392220539?thread_ts=1648893985.315499&cid=C02KGN5K076

It though seems that still the regular jpg images get used instead of the webp version of the images. see here:
image

## Steps to reproduce

1. Upload jpeg images - implement them as background images or regular images in gutenberg blocks
2. install performance plugin, activate webp
3. use Regenerate Thumbnails plugin to generate the webp
4. See on frontend if they got used

## Additional Context

 - PHP Version: 8.0
 - OS: Windows
 - Browser: MS Edge
 - Plugin Version: RC1

### PR DESCRIPTION
**Pull request by mitogh**
## Summary

When a modern format is available to render the featured image make sure that the replacement image uses the same logic used to replace the images in the content in order to be consistent
with the rest of rendered format.

Fixes #288

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Comment by masteradhoc** [comment]
Thanks for the PR @mitogh!

**Review by adamsilverstein — APPROVED** [review]
Looks good, nice work!

File: modules/images/webp-uploads/load.php [hunk 1]
```diff
@@ -502,3 +502,20 @@ function webp_uploads_img_tag_update_mime_type( $image, $context, $attachment_id
...
+ * @param string $html          The current HTML markup of the featured image.
+ * @param int    $post_id       The current post ID where the featured image is requested.
+ * @param int    $attachment_id The ID of the attachment image.
+ * @return string The updated HTML markup.
+ */
+function webp_uploads_update_featured_image( $html, $post_id, $attachment_id ) {
+	return webp_uploads_img_tag_update_mime_type( $html, 'post_thumbnail_html', $attachment_id );
+}
+
+add_filter( 'post_thumbnail_html', 'webp_uploads_update_featured_image', 10, 3 );
```
Comment (felixarntz) [inline modules/images/webp-uploads/load.php]: Nit-pick:
```suggestion
}
add_filter( 'post_thumbnail_html', 'webp_uploads_update_featured_image', 10, 3 );
```

**Review by felixarntz — APPROVED** [review]
@mitogh Great work!
