### PR TITLE
Fix `WordPress.DB.DirectDatabaseQuery.DirectQuery` warning for Autoloaded Options Health Check

### LINKED ISSUE #919: Plugin Check: Report `WordPress.DB.DirectDatabaseQuery.DirectQuery` warning for Autoloaded Options Health Check
## Bug Description

The [Plugin Check](https://github.com/WordPress/plugin-check) tool now shows warning for use of direct database call in Autoloaded Options Health Check.

## Steps to reproduce

1. Install Plugin Checker tool from https://github.com/WordPress/plugin-check repo
2. Go to `Tools > Plugin Check`
3. Select `Performance Lab` in Check the Plugin and click on `Check it!` button

## Screenshots

Screenshot 2024-01-04 at 1 58 38 PM

### PR DESCRIPTION
**Pull request by Ellusu**
Fixes #919

## Summary

Fix to reduce direct database call as suggested by Plugin Check

OLD:
old
NEW:
new

### CODE REVIEW

File: includes/site-health/audit-autoloaded-options/helper.php [hunk 1]
```diff
@@ -125,33 +123,26 @@ function perflab_aao_autoloaded_options_size() {
...
+			$large_options[] = (object) array(
+				'option_name'         => $option_name,
+				'option_value_length' => strlen( $option_value ),
+			);
+		}
+	}
+
+	usort( $large_options, static function ( $a, $b ) {
+		return $b->option_value_length - $a->option_value_length;
+	});
```
Comment (mukeshpanchal27) [inline includes/site-health/audit-autoloaded-options/helper.php]:
```suggestion
	usort(
		$large_options,
		static function ( $a, $b ) {
			return $b->option_value_length - $a->option_value_length;
		}
	);
```

Fix PHPCS

File: includes/site-health/audit-autoloaded-options/helper.php [hunk 2]
```diff
@@ -100,19 +100,17 @@ function perflab_aao_autoloaded_options_test() {
...
-			sprintf(
-				"SELECT SUM(LENGTH(option_value)) FROM $wpdb->options WHERE autoload IN (%s)",
-				implode( ',', array_fill( 0, count( $autoload_values ), '%s' ) )
-			),
-			$autoload_values
-		)
-	);
+	wp_load_alloptions();
+
+	$all_options = wp_cache_get( 'alloptions', 'options' );
```
Comment (joemcgill) [inline includes/site-health/audit-autoloaded-options/helper.php]: Why not take the return value directly from `wp_load_alloptions();` here?

File: includes/site-health/audit-autoloaded-options/helper.php [hunk 3]
```diff
@@ -202,23 +196,24 @@ function perflab_aao_get_autoloaded_options_table() {
...
-				"SELECT option_name, LENGTH(option_value) AS option_value_length FROM $wpdb->options WHERE option_name IN (%s) ORDER BY option_value_length DESC",
-				implode( ',', array_fill( 0, count( $disabled_options ), '%s' ) )
-			),
-			$disabled_options
-		)
-	);
+	$disabled_options_summary = array();
+
+	foreach ( $disabled_options as $option_name ) {
+		$option_value = get_option( $option_name );
```
Comment (joemcgill) [inline includes/site-health/audit-autoloaded-options/helper.php:217]: Prior to making so many calls to `get_option()` we could run all of the disabled options through `wp_prime_option_caches()` to avoid multiple DB queries.

**Review by joemcgill — CHANGES_REQUESTED** [review]
Thanks for working on this @Ellusu! Left a couple questions/suggestions.

File: includes/site-health/audit-autoloaded-options/helper.php (hunk 2 above)
Comment (Ellusu) [reply includes/site-health/audit-autoloaded-options/helper.php]: thanks, commit done

File: includes/site-health/audit-autoloaded-options/helper.php (hunk 3 above)
Comment (Ellusu) [reply includes/site-health/audit-autoloaded-options/helper.php:217]: thanks, commit done

**Review by joemcgill — APPROVED** [review]
Thanks, @Ellusu. Looks good to me.

**Review by joemcgill — CHANGES_REQUESTED** [review]
I tried resolving conflicts to this branch following some of the upstream PHPStan changes were applied, and looks like it's caught that the return value is slightly changed following this change. Would be good to review and see if the docblock just needs to be updated, or if something in the function needs to be updated.

**Comment by westonruter** [comment]
> I tried resolving conflicts to this branch following some of the upstream PHPStan changes were applied, and looks like it's caught that the return value is slightly changed following this change. Would be good to review and see if the docblock just needs to be updated, or if something in the function needs to be updated.

Ah, my bad. I got the typing wrong here: https://github.com/WordPress/performance/pull/1188/files#r1591653385

Fixed in 6f89a5409c7d255e8f08453e2c366b96397dda21.

File: includes/site-health/audit-autoloaded-options/helper.php [hunk 4]
```diff
@@ -100,19 +100,15 @@ function perflab_aao_autoloaded_options_test(): array {
  * @return int autoloaded data in bytes.
  */
 function perflab_aao_autoloaded_options_size(): int {
```
Comment (mukeshpanchal27) [inline includes/site-health/audit-autoloaded-options/helper.php:100]: Remove `@global wpdb $wpdb` document.

File: includes/site-health/audit-autoloaded-options/helper.php [hunk 5]
```diff
@@ -122,10 +118,9 @@ function perflab_aao_autoloaded_options_size(): int {
  *
  * @global wpdb $wpdb WordPress database abstraction object.
  *
```
Comment (mukeshpanchal27) [inline includes/site-health/audit-autoloaded-options/helper.php]:
```suggestion
```

Remove document.

File: includes/site-health/audit-autoloaded-options/helper.php [hunk 6]
```diff
@@ -202,23 +207,25 @@ function perflab_aao_get_autoloaded_options_table(): string {
  * @return string HTML formatted table.
  */
 function perflab_aao_get_disabled_autoloaded_options_table(): string {
```
Comment (mukeshpanchal27) [inline includes/site-health/audit-autoloaded-options/helper.php:203]: Remove `@global wpdb $wpdb` document.

**Review by mukeshpanchal27 — COMMENTED** [review]
Thanks for the update.

Left some nit-pick. Can we update `test_perflab_aao_autoloaded_options_size` tests to remove the query?

File: includes/site-health/audit-autoloaded-options/helper.php (hunk 6 above)
Comment (Ellusu) [reply includes/site-health/audit-autoloaded-options/helper.php:203]: commited, thanks

File: includes/site-health/audit-autoloaded-options/helper.php (hunk 5 above)
Comment (Ellusu) [reply includes/site-health/audit-autoloaded-options/helper.php]: commited, thanks

File: includes/site-health/audit-autoloaded-options/helper.php (hunk 4 above)
Comment (Ellusu) [reply includes/site-health/audit-autoloaded-options/helper.php:100]: commited, thanks

**Review by joemcgill — APPROVED** [review]
Looks good to me.

**Review by westonruter — APPROVED** [review]
LGTM. Let's merge once @mukeshpanchal27 approves.

File: includes/site-health/audit-autoloaded-options/helper.php [hunk 7]
```diff
@@ -229,21 +237,23 @@ function perflab_aao_get_disabled_autoloaded_options_table(): string {
...
-					'option_name' => $value->option_name,
+					'option_name' => $option_name,
 					'autoload'    => 'true',
 				),
 				admin_url( 'site-health.php' )
 			)
 		);
 		$disable_button = sprintf( '<a class="button" href="%s">%s</a>', esc_url( $url ), esc_html__( 'Revert to Autoload', 'performance-lab' ) );
-		$html_table    .= sprintf( '<tr><td>%s</td><td>%s</td><td>%s</td></tr>', esc_html( $value->option_name ), size_format( $value->option_value_length, 2 ), $disable_button );
+		$html_table    .= sprintf( '<tr><td>%s</td><td>%s</td><td>%s</td></tr>', esc_html( $option_name ), size_format( $option_length, 2 ), $disable_button );
```
Comment (westonruter) [inline includes/site-health/audit-autoloaded-options/helper.php:254]: With the PHPStan level updates, this line was now giving an error about `$option_name` potentially not being a string. In normal plugin operation this would always be a string. But since any other plugin can manipulate options as well, there's no guarantee that it will be an array of strings. So I've added these checks in 3dd2f695379fde4006b84b1bfcd61c3e97c0dfca.

File: includes/site-health/audit-autoloaded-options/helper.php [hunk 8]
```diff
@@ -197,28 +198,35 @@ function perflab_aao_get_autoloaded_options_table(): string {
...
+
+		if ( false !== $option_value ) {
+			$option_length                            = strlen( maybe_serialize( $option_value ) );
+			$disabled_options_summary[ $option_name ] = $option_length;
+		}
+	}
+
+	if ( count( $disabled_options_summary ) === 0 ) {
+		return '';
+	}
```
Comment (westonruter) [inline includes/site-health/audit-autoloaded-options/helper.php:227]: I realized that with the refactor here, it is possible for `$disabled_options_summary` to be an empty array at this point, if none of the options are in the database anymore. This is quite unlikely, but to account for this I've added e6f8650889d585f28e29972e0214aa540764b7ae.

**Review by mukeshpanchal27 — APPROVED** [review]
