### PR TITLE
Correct docblock for `wp_get_attachment_file_path()`

### LINKED ISSUE #499: Correct docblock for wp_get_attachment_file_path()
## Bug Description
The inline document specifies that `thumbnail` is the default size instead of `medium`
Ref: https://github.com/WordPress/performance/blob/trunk/modules/images/dominant-color/load.php#L322

### PR DESCRIPTION
**Pull request by dilipbheda**
Fixes #499
## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

File: modules/images/dominant-color/load.php [hunk 1]
```diff
@@ -319,7 +319,7 @@ function _dominant_color_get_dominant_color_data( $attachment_id ) {
  * @param string $size          Optional. Image size. Default 'thumbnail'.
  * @return false|string Path to an image or false if not found.
  */
-function wp_get_attachment_file_path( $attachment_id, $size = 'medium' ) {
+function wp_get_attachment_file_path( $attachment_id, $size = 'thumbnail' ) {
```
Comment (mukeshpanchal27) [inline modules/images/dominant-color/load.php]: Why you want to update the size to `thumbnail`?

**Review by mukeshpanchal27 — COMMENTED** [review]
@dilipbheda There are no size restrictions that we require in order to function.

The size changes break the unit tests, so if you have a strong response to this update, then you have to update the unit tests.

File: modules/images/dominant-color/load.php (hunk 1 above)
Comment (dilipbheda) [reply modules/images/dominant-color/load.php]: > `@param` string $size          Optional. Image size. Default 'thumbnail'.


@mukeshpanchal27 In inline document mentioned `thumbnail` default image size.
should I update the inline document instead of changing the image size?

Comment (mukeshpanchal27) [reply modules/images/dominant-color/load.php]: Yes that make sense. Update the document only as there is no need to update size in function.

Comment (dilipbheda) [reply modules/images/dominant-color/load.php]: @mukeshpanchal27 Done!

**Review by mukeshpanchal27 — APPROVED** [review]
@dilipbheda Thanks for the update. LGTM.

**Review by pbearne — APPROVED** [review]

**Review by mehulkaklotar — APPROVED** [review]
