### PR TITLE
Fixes palette-based PNG uploads failing original full-size AVIF/WebP conversion under GD

### LINKED ISSUE #1561: Fatal error: Paletter image not supported by webp
## Bug Description

I just tried to convert a existing site to webp with performance lab + modern image.

## Steps to reproduce

1. Install and enable both plugins
2. Change setting to "webp"
3. Use wp-cli to regenerate all images: [wp media regenerate](https://developer.wordpress.org/cli/commands/media/regenerate/)
4. After a few images it stops with the error

> Fatal error: Paletter image not supported by webp in /usr/www/users/xxxxxx/staging-xxxxxx-com/releases/20240924131521/wp-includes/class-wp-image-editor.php on line 592

## Screenshots

image

## Additional Context

 - PHP Version: 8.1
 - OS: Linux
 - Browser: chromium
 - Plugin Version: 3.4.1 / 2.2.0
 - Device: Desktop

It seems the fix is to convert the image to RGB if it isn't already: https://stackoverflow.com/questions/39292617/fatal-error-paletter-image-not-supported-by-webp

### LINKED ISSUE #1864: Transparent .pngs with colour type Palette cannot be converted
## Bug Description

When uploading images, with the color type "Palette" or "PaletteAlpha", the plugin generates the full size-webp versions as an empty files (0 bytes). The resized versions are converted correctly. This results in images not being displayed to site visitors, as the .webp file is invalid.
## Steps to Reproduce

    Upload an image with the color type "Palette" or "PaletteAlpha" to the WordPress media library.
    Navigate to the directory where the image is stored (e.g., /wp-content/uploads/2025/02/).
    Observe that the corresponding .webp version of the image has a file size of 0 bytes.
    As a result, the image is not displayed to site visitors.

## Additional Notes

Converting the image to a different color type to sRGB before uploading resolves the issue for me.

## Example
```-rw-r--r-- 1 someuser someuser 13412 2025-02-07 08:18 image-name-1024x576.webp
-rw-r--r-- 1 someuser someuser   858 2025-02-07 08:18 image-name-150x150.webp
-rw-r--r-- 1 someuser someuser 25160 2025-02-07 08:18 image-name-1536x864.webp
-rw-r--r-- 1 someuser someuser  2052 2025-02-07 08:18 image-name-300x169.webp
-rw-r--r-- 1 someuser someuser  9086 2025-02-07 08:18 image-name-768x432.webp
-rw-r--r-- 1 someuser someuser 33812 2025-02-07 08:18 image-name.png
-rw-r--r-- 1 someuser someuser     0 2025-02-07 08:18 image-name-png.webp

### LINKED ISSUE #2018: Original Full-Size AVIF/WEBP Conversion Fails on Palette-Based PNGs When GD is Used
## Bug Description

When uploading a PNG that was compressed using https://imageresizer.com/image-compressor, I encountered following PHP warnings during AVIF and WebP conversion.

AVIF conversion warning:
```
Warning: imageavif(): avif error - avif doesn't support palette images in /var/www/html/wp-includes/class-wp-image-editor.php on line 585
```
WebP conversion warning:
```
 Warning: imagewebp(): Palette image not supported by webp in /var/www/html/wp-includes/class-wp-image-editor.php on line 585
```

Based on inspection of the PHP GD source:
* [`gdImageAvifCtx()` (imageavif) source](https://github.com/php/php-src/blob/a3fa5ae57b8b49566f8efdae700beb7236227be5/ext/gd/libgd/gd_avif.c#L506)
* [`gdImageWebp()` (imagewebp) source](https://github.com/php/php-src/blob/a3fa5ae57b8b49566f8efdae700beb7236227be5/ext/gd/libgd/gd_webp.c#L116)

Both `imageavif()` and `imagewebp()` functions fail when passed a **palette-based image**, because GD requires **truecolor images** for these conversions.

It appears these compression tools convert standard PNGs into palette-based (indexed color) PNGs. Due to this when uploading a palette-based (indexed color) PNG to WordPress media library, the original full-size AVIF/WebP file fails to convert and ends up as a 0-byte file.

However, resized sub-sizes are unaffected. Upon reviewing the GD editor code in WordPress core, I noticed that the [`_resize()` method](https://github.com/WordPress/wordpress-develop/blob/8e88f4c4a76b9d43d29031919785fca225c33734/src/wp-includes/class-wp-image-editor-gd.php#L232) in `WP_Image_Editor_GD` always converts the source image to **truecolor** before any further processing hence, sub-sizes convert without issue.

References:
* [libpng – Chapter 8: Indexed color](https://www.libpng.org/pub/png/book/chapter08.html?utm_source=chatgpt.com#png.ch08.div.5.1)
* [Indexed color overview – Drububu](https://www.drububu.com/tutorial/image-types.html)

## Steps to reproduce

1. Force GD as the default image editor:
```php
add_filter( 'wp_image_editors', function () {
  return [ 'WP_Image_Editor_GD' ];
} );
```
2. Ensure the Modern Image Formats plugin is installed and activated.
3. Upload a palette-based PNG image (created or optimized by an online compressor like imageresizer.com).

Sample palette PNG image:
Image
Sample transparent palette PNG image:
Image

## Screenshots

AVIF conversion warning:

Image

WebP conversion warning:
Image

## Additional Context

 - GD Version: bundled (2.1.0 compatible)

### PR DESCRIPTION
**Pull request by b1ink0**
## Summary

Fixes #2018, #1561, #1864

## Relevant technical choices

This change hooks into both `wp_handle_upload_prefilter` and `wp_handle_sideload_prefilter` to detect palette-based (indexed-color) PNGs and convert them in-place to truecolor while preserving transparency before any AVIF/WebP encoding takes place. It preserves all existing upload metadata and only affects PNGs handled by the GD image editor.

### CODE REVIEW

File: plugins/webp-uploads/hooks.php [hunk 1]
```diff
@@ -803,3 +803,62 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+	// Convert the palette to truecolor.
+	if ( imagepalettetotruecolor( $image ) ) {
+		// Overwrite the upload with the new truecolor PNG.
+		imagepng( $image, $file['tmp_name'] );
+	}
+	imagedestroy( $image );
+
+	return $file;
+}
+add_filter( 'wp_handle_upload_prefilter', 'webp_uploads_convert_palette_png_to_truecolor' );
```
Comment (felixarntz) [inline plugins/webp-uploads/hooks.php:964]: You're already using this in the test, but wouldn't it make sense to also add the same function as a hook callback to `wp_handle_sideload_prefilter`?

**Review by felixarntz — COMMENTED** [review]
@b1ink0 Thank you, this looks great to me so far, just one comment.

It would be great to get @adamsilverstein's review on this as well.

File: plugins/webp-uploads/hooks.php (hunk 1 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php:964]: Yes, it makes sense. At first, I thought `wp_handle_sideload` and `media_handle_sideload`, which trigger the `wp_handle_sideload_prefilter`, were not used in core, but after some digging, I found that core does trigger this filter.

Comment (b1ink0) [reply plugins/webp-uploads/hooks.php:964]: Done in https://github.com/WordPress/performance/pull/2024/commits/8ad675ca451b3bc5f49fa96b332c1868b9739fca

File: plugins/webp-uploads/hooks.php [hunk 2]
```diff
@@ -803,3 +803,63 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+ *
+ * GD cannot convert palette-based PNG to WebP/AVIF formats, causing conversion failures.
+ * This function detects and converts palette PNG to truecolor during upload.
+ *
+ * @since n.e.x.t
+ *
+ * @param array<string, mixed> $file The uploaded file data.
+ * @return array<string, mixed> The modified file data.
+ */
+function webp_uploads_convert_palette_png_to_truecolor( array $file ): array {
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]: Since WordPress plugins can supply any kind of value in filters, this should have better safeguards to prevent a PHP fatal error:

```suggestion
 * @param array<string, mixed>|mixed $file The uploaded file data.
 * @return array<string, mixed> The modified file data.
 */
function webp_uploads_convert_palette_png_to_truecolor( $file ): array {
	if ( ! is_array( $file ) ) {
		$file = array();
	}
```

File: plugins/webp-uploads/hooks.php [hunk 3]
```diff
@@ -803,3 +803,63 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+	if ( ! isset( $file['tmp_name'], $file['name'] ) ) {
+		return $file;
+	}
+
+	if ( 'png' !== strtolower( pathinfo( $file['name'], PATHINFO_EXTENSION ) ) ) {
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]: Should this look at the attachment metadata instead to see if the MIME type is `image/png`?

Comment (b1ink0) [reply plugins/webp-uploads/hooks.php]: Yes, we can just check if `$file['type']` is `image/png`.

Comment (b1ink0) [reply plugins/webp-uploads/hooks.php]: Done in https://github.com/WordPress/performance/pull/2024/commits/7443e686a89f6c15b8eab396e3184d6d2dab4fcc.

**Comment by adamsilverstein** [comment]
Hi @b1ink0 and thanks for the PR.

> detect palette-based (indexed-color) PNGs and convert them in-place to truecolor while preserving transparency before any AVIF/WebP encoding takes place

Good catch! I understand the technical requirement for GD here and agree we need to address them to resolve this issue.  

My only concern is that by converting a palette image (up to 8 bit) to truecolor (eg. 24 bit), we might inadvertently bloat the image size. We tried to address this for Imagick in https://core.trac.wordpress.org/ticket/36477.   I'd love to see some before/after size numbers for indexed PNG uploads converted to WebP and AVIF to confirm that isn't the case. I suspect we are ok given the lossy compression of WebP/AVIF vs the lossless PNG compression, but it would be worth checking and perhaps adding a unit test for this aspect.

File: plugins/webp-uploads/hooks.php [hunk 4]
```diff
@@ -803,3 +803,69 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
 	return $allowed_sizes;
 }
 add_filter( 'webp_uploads_image_sizes_with_additional_mime_type_support', 'webp_uploads_enable_additional_mime_type_support_for_all_sizes' );
+
+/**
+ * Converts palette PNG images to true color PNG images.
```
Comment (adamsilverstein) [inline plugins/webp-uploads/hooks.php]:
```suggestion
 * Converts palette PNG images to truecolor PNG images.
```

for whatever reason, PNG calls these "truecolor" - one word.

File: plugins/webp-uploads/hooks.php [hunk 5]
```diff
@@ -803,3 +803,69 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+ *
+ * GD cannot convert palette-based PNG to WebP/AVIF formats, causing conversion failures.
```
Comment (adamsilverstein) [inline plugins/webp-uploads/hooks.php:908]: I wonder if this fix belongs in core itself sice we inherently support this type of conversion with a simple filter. If we don't fix automatically, at the very least, we should inform the user why the upload failed and how to fix it.

File: plugins/webp-uploads/hooks.php [hunk 6]
```diff
@@ -803,3 +803,69 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+
+	$editor = wp_get_image_editor( $file['tmp_name'] );
+
+	if ( is_wp_error( $editor ) || ! $editor instanceof WP_Image_Editor_GD ) {
+		return $file;
+	}
+
+	// Check if required GD functions exist.
+	if (
+		! function_exists( 'imagecreatefrompng' ) ||
```
Comment (adamsilverstein) [inline plugins/webp-uploads/hooks.php]: +1 to defensive programming; however all of these functions have been around since PHP4/5 as as far as I know should be available to all WordPress installs with GD. So maybe we can remove this check?

File: plugins/webp-uploads/hooks.php [hunk 7]
```diff
@@ -803,3 +803,69 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+		! function_exists( 'imagesavealpha' ) ||
+		! function_exists( 'imagepalettetotruecolor' ) ||
+		! function_exists( 'imagepng' ) ||
+		! function_exists( 'imagedestroy' )
+	) {
+		return $file;
+	}
+
+	$image = imagecreatefrompng( $file['tmp_name'] );
+	if ( false === $image || imageistruecolor( $image ) ) {
```
Comment (adamsilverstein) [inline plugins/webp-uploads/hooks.php]: I'm confused by this check. If $image is false, the conversion failed. In that case, don't we want to continue to the processing below?

File: plugins/webp-uploads/hooks.php [hunk 8]
```diff
@@ -803,3 +803,69 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+	imagesavealpha( $image, true );
+
+	// Convert the palette to truecolor.
+	if ( imagepalettetotruecolor( $image ) ) {
+		// Overwrite the upload with the new truecolor PNG.
+		imagepng( $image, $file['tmp_name'] );
+	}
+	imagedestroy( $image );
+
+	return $file;
```
Comment (adamsilverstein) [inline plugins/webp-uploads/hooks.php:962]: Should we set $file['name'] to the new file name before returning $file?

File: plugins/webp-uploads/tests/test-load.php [hunk 9]
```diff
@@ -1116,4 +1116,136 @@ public function test_that_it_should_convert_webp_to_avif_on_upload(): void {
...
+				$this->assertNotSame( $original_file_hash, $modified_file_hash );
+				$img = imagecreatefrompng( $path );
+				$this->assertTrue( imageistruecolor( $img ) );
+				imagedestroy( $img );
+
+				// Make sure the image converted to modern image format is not 0 bytes.
+				$modern_image_format_path = get_attached_file( $attachment_id );
+				$this->assertNotFalse( $modern_image_format_path );
+				$this->assertFileExists( $modern_image_format_path );
+				$this->assertGreaterThan( 0, (int) filesize( $modern_image_format_path ) );
```
Comment (adamsilverstein) [inline plugins/webp-uploads/tests/test-load.php]: can we also add an assertion that the new image filesize isn't larger than the original image?

File: plugins/webp-uploads/tests/test-load.php [hunk 10]
```diff
@@ -1116,4 +1116,136 @@ public function test_that_it_should_convert_webp_to_avif_on_upload(): void {
...
+				'image_path'       => $test_jpg,
+				'expected_changed' => false,
+				'set_up'           => null,
+				'tear_down'        => null,
+			),
+			'non_palette_png' => array(
+				'image_path'       => $non_palette_png,
+				'expected_changed' => false,
+				'set_up'           => function (): void {
+					add_filter( 'wp_image_editors', array( $this, 'use_gd_image_editor' ) );
```
Comment (adamsilverstein) [inline plugins/webp-uploads/tests/test-load.php]: can the test just add this filter always, without needing a "set_up" attribute?

File: plugins/webp-uploads/tests/test-load.php [hunk 11]
```diff
@@ -1116,4 +1116,136 @@ public function test_that_it_should_convert_webp_to_avif_on_upload(): void {
...
+				},
+				'tear_down'        => function (): void {
```
Comment (adamsilverstein) [inline plugins/webp-uploads/tests/test-load.php]: tear_down should not be required as all hooks should be reset between test runs as far as I know. Can you try removing?

File: plugins/webp-uploads/hooks.php (hunk 6 above)
Comment (westonruter) [reply plugins/webp-uploads/hooks.php]: That would address the code coverage issue as well, if it is impossible to create a scenario where any of these functions don't exist.

Comment (westonruter) [reply plugins/webp-uploads/hooks.php]: Oh, but actually will these functions be available if GD is not [installed](https://www.php.net/manual/en/image.installation.php)? If PHP is not compiled with `--with-gd` then I don't think they will.

Comment (b1ink0) [reply plugins/webp-uploads/hooks.php]: If PHP is not compiled with GD, then these functions will not be available. I compiled PHP with and without GD and tested it; the version without GD did not have these functions.
Screenshot 2025-06-10 at 8 33 05 PM

File: plugins/webp-uploads/hooks.php (hunk 7 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php]: When `imagecreatefrompng()` returns false, it means the creation of the PNG failed. In that case, we can't convert it to truecolor because we need a valid GDImage resource for `imagepalettetotruecolor()` to work properly. Returning early in this scenario is the best choice since there's no valid image resource to operate on.

I also combined two different checks in that condition, which I realize makes the logic less clear. Separate those out in https://github.com/WordPress/performance/pull/2024/commits/7f757c729547b8445450d84d672183f322cbf3b6 to improve readability.

File: plugins/webp-uploads/hooks.php (hunk 8 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php:962]: If you're asking whether the conversion has changed the name of the file, it has not - we simply overwrote the same file with the converted version.

However, if you're suggesting that users should see a different filename when an image is converted to truecolor, we could add a suffix like `-truecolor` to the filename. But I'm not sure whether we should do that, since this conversion is meant to be a transparent internal optimization rather than a user-visible change.

File: plugins/webp-uploads/tests/test-load.php (hunk 11 above)
Comment (b1ink0) [reply plugins/webp-uploads/tests/test-load.php]: Yeah, we can remove this. I had added them because I was also testing using the ImageMagick editor, and since filters don't get removed between iterations of the data provider, I had to add setup and teardown.

But I removed the test for ImageMagick as I noticed ImageMagick wasn't working correctly when I ran the tests. When I tried to log `Imagick::queryFormats()`, it returned an empty array. I'm not sure why - I tried running `php -r "print_r(Imagick::queryFormats());"` in the `wp-env` created `tests-wordpress` container and it gave an array with all supported formats, but when I ran the same command in `tests-cli` it gave an empty array. I'm not sure - do tests run in the `tests-cli` container and not the `tests-wordpress` container?

**Comment by b1ink0** [comment]
> I'd love to see some before/after size numbers for indexed PNG uploads converted to WebP and AVIF to confirm that isn't the case. I suspect we are ok given the lossy compression of WebP/AVIF vs the lossless PNG compression, but it would be worth checking and perhaps adding a unit test for this aspect.

I ran some tests on a few indexed PNGs. As expected, converting them to truecolor PNGs increased the file size up to 2.5x in some cases. However, when these converted truecolor PNGs were then encoded to AVIF or WebP, the resulting file sizes were consistently smaller than the original indexed PNGs encoded directly to AVIF/WebP.


Sample Image | Indexed PNG Size | Truecolor PNG Size | AVIF Size (from Truecolor PNG) | WebP Size (from Truecolor PNG)
-- | -- | -- | -- | --
 | 7 KB | 15 KB | 3 KB | 2 KB
 | 65 KB | 116 KB | 4 KB | 3 KB
 | 41 KB | 87 KB | 26 KB | 16 KB
 | 1.4 MB | 3.8 MB | 674 KB | 628 KB
 | 177 KB | 426 KB | 149 KB | 107 KB

cc: @adamsilverstein

File: plugins/webp-uploads/tests/test-load.php (hunk 10 above)
Comment (b1ink0) [reply plugins/webp-uploads/tests/test-load.php]: Done in https://github.com/WordPress/performance/pull/2024/commits/e64694188c9d7b4eb7350e66ddd472704bc90788.

File: plugins/webp-uploads/tests/test-load.php (hunk 11 above)
Comment (b1ink0) [reply plugins/webp-uploads/tests/test-load.php]: Done in https://github.com/WordPress/performance/pull/2024/commits/e64694188c9d7b4eb7350e66ddd472704bc90788.

File: plugins/webp-uploads/tests/test-load.php (hunk 9 above)
Comment (b1ink0) [reply plugins/webp-uploads/tests/test-load.php]: Done in https://github.com/WordPress/performance/pull/2024/commits/56e8dacbeb7c98d60ca8be9d95df560b84e0267e.

File: plugins/webp-uploads/hooks.php (hunk 5 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php:908]: I located the Trac ticket: [#59339](https://core.trac.wordpress.org/ticket/59339?utm_source=chatgpt.com) "Conversion to webp causes fatal error when original image is a palette image (as opposed to truecolor)"

Should we post an update there and start the discussion on where to go next?

File: plugins/webp-uploads/hooks.php (hunk 8 above)
Comment (adamsilverstein) [reply plugins/webp-uploads/hooks.php:962]: Ok, that makes sense. I'll give this a test to verify.

File: plugins/webp-uploads/hooks.php (hunk 7 above)
Comment (adamsilverstein) [reply plugins/webp-uploads/hooks.php]: thanks for clarifying

File: plugins/webp-uploads/hooks.php (hunk 5 above)
Comment (adamsilverstein) [reply plugins/webp-uploads/hooks.php:908]: I updated the ticket with a link to this PR.

File: plugins/webp-uploads/hooks.php (hunk 6 above)
Comment (adamsilverstein) [reply plugins/webp-uploads/hooks.php]: > If PHP is not compiled with GD,

Just to clarify for my own understanding - is GD bundled by default and would need to be disabled for the build?

**Comment by adamsilverstein** [comment]
Thanks for the PR and all the work here @b1ink0. I will try testing with the Bedrock container you linked to earlier.

File: plugins/webp-uploads/hooks.php [hunk 12]
```diff
@@ -803,3 +803,77 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+ *
+ * GD cannot convert palette-based PNG to WebP/AVIF formats, causing conversion failures.
+ * This function detects and converts palette PNG to truecolor during upload.
+ *
+ * @since n.e.x.t
+ *
+ * @param array<string, mixed>|mixed $file The uploaded file data.
+ * @return array<string, mixed> The modified file data.
+ */
+function webp_uploads_convert_palette_png_to_truecolor( $file ): array {
```
Comment (adamsilverstein) [inline plugins/webp-uploads/hooks.php:818]: we should probably build this into core which will have the same issue if users try the output filter to output AVIFs, are using GD and upload indexed PNGs.

**Comment by adamsilverstein** [comment]
I was able to verify the issue with the Bedrock container and some code to force using GD. I also verified the PR fixes the issue. This should be good to go. 

We should probably port this fix to WordPress core since this will also affect anyone using the core output filter directly with the same configuration.

File: plugins/webp-uploads/hooks.php [hunk 13]
```diff
@@ -803,3 +803,77 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+	if ( ! is_array( $file ) ) {
+		$file = array();
```
Comment (adamsilverstein) [inline plugins/webp-uploads/hooks.php:919]: can we just return here instead of continuing?


```suggestion
		return $file;
```

File: plugins/webp-uploads/hooks.php [hunk 14]
```diff
@@ -803,3 +803,77 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+	}
+	if ( ! isset( $file['tmp_name'], $file['name'] ) ) {
+		return $file;
+	}
+	if ( isset( $file['type'] ) && is_string( $file['type'] ) ) {
+		if ( 'image/png' !== strtolower( $file['type'] ) ) {
```
Comment (adamsilverstein) [inline plugins/webp-uploads/hooks.php:925]: do we need this check? it seems duplicated by the following check with `wp_check_filetype`

File: plugins/webp-uploads/hooks.php [hunk 15]
```diff
@@ -803,3 +803,77 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+			return $file;
+		}
+	} elseif ( 'image/png' !== wp_check_filetype( $file['name'] )['type'] ) {
+		return $file;
+	}
+
+	$editor = wp_get_image_editor( $file['tmp_name'] );
+
+	if ( is_wp_error( $editor ) || ! $editor instanceof WP_Image_Editor_GD ) {
```
Comment (adamsilverstein) [inline plugins/webp-uploads/hooks.php:934]: If this check passes and GD is the image editor returned from `wp_get_image_editor` I expect we can skip all of the conditional checks. That is - if PHP is compiled without GD, WordPress won't choose GD as the editor. See https://github.com/WordPress/WordPress/blob/ead6495be56c3c6dd7819350258ce3bea9430a83/wp-includes/class-wp-image-editor-gd.php#L39-L53

If PHP could be built with only some required methods enabled, we can also pass a list of required method names to `wp_get_image_editor` to ensure they are availailable (see https://github.com/WordPress/WordPress/blob/ead6495be56c3c6dd7819350258ce3bea9430a83/wp-includes/media.php#L4298-L4303).

File: plugins/webp-uploads/hooks.php (hunk 6 above)
Comment (adamsilverstein) [reply plugins/webp-uploads/hooks.php]: I still think we can remove these - if GD is the chosen image editor we can be confident PHP supports GD. See https://github.com/WordPress/performance/pull/2024/files#r2217413978

**Comment by adamsilverstein** [comment]
@b1ink0 - this looks very close, thanks! I left a few additional comments, let me know what you think.

File: plugins/webp-uploads/hooks.php (hunk 15 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php:934]: You're right, after looking at the core logic, these checks are unnecessary. GD will have all the core functions available when compiled, so we don't need to check each of them individually.

I'll remove these redundant function checks.

File: plugins/webp-uploads/hooks.php (hunk 6 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php]: > > If PHP is not compiled with GD,
> 
> Just to clarify for my own understanding - is GD bundled by default and would need to be disabled for the build?

GD is bundled with PHP source code by default, but it must be explicitly enabled during compilation and can be omitted from the final build.

https://www.php.net/manual/en/image.installation.php

---

>I still think we can remove these - if GD is the chosen image editor we can be confident PHP supports GD. See https://github.com/WordPress/performance/pull/2024/files#r2217413978

You're right, I'll remove these redundant function checks.

File: plugins/webp-uploads/hooks.php (hunk 13 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php:919]: Here https://github.com/WordPress/performance/pull/2024#discussion_r2127464876 Weston suggested this:
> Since WordPress plugins can supply any kind of value in filters, this should have better safeguards to prevent a PHP fatal error:

https://github.com/WordPress/performance/pull/2024/commits/ef9a9f912619a9d2c1c5150633fc76bca92e09a1
```diff
diff --git a/plugins/webp-uploads/hooks.php b/plugins/webp-uploads/hooks.php
index 059c09fe..c9c6755f 100644
--- a/plugins/webp-uploads/hooks.php
+++ b/plugins/webp-uploads/hooks.php
@@ -812,10 +812,13 @@ add_filter( 'webp_uploads_image_sizes_with_additional_mime_type_support', 'webp_
  *
  * @since n.e.x.t
  *
- * @param array<string, mixed> $file The uploaded file data.
+ * @param array<string, mixed>|mixed $file The uploaded file data.
  * @return array<string, mixed> The modified file data.
  */
-function webp_uploads_convert_palette_png_to_truecolor( array $file ): array {
+function webp_uploads_convert_palette_png_to_truecolor( $file ): array {
+	if ( ! is_array( $file ) ) {
+		$file = array();
+	}
 	if ( ! isset( $file['tmp_name'], $file['name'] ) ) {
 		return $file;
 	}
```

I think returning an empty array makes sense here, or should we not change anything and return the `$file` as it is?

```suggestion
		return array();
```

File: plugins/webp-uploads/hooks.php (hunk 14 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php:925]: The checks aren't duplicated they handle different scenarios. I added the first check for `$file['type']` per this https://github.com/WordPress/performance/pull/2024#discussion_r2127465929 feedback to use the MIME type from attachment metadata (this is available when the file is uploaded and present in `$_FILES` for [ref](https://github.com/WordPress/wordpress-develop/blob/e41e2d20755687e52f0176e1016d239646f6517a/src/wp-admin/includes/media.php#L295-L306).) instead of just relying on the file extension. The `elseif` ensures we fall back to `wp_check_filetype()` when `$file['type']` isn't available.

File: plugins/webp-uploads/hooks.php (hunk 6 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php]: Done in https://github.com/WordPress/performance/pull/2024/commits/ca8599c36f33a5f52839c6b10a5970f6a5f457c6.

File: plugins/webp-uploads/hooks.php (hunk 14 above)
Comment (adamsilverstein) [reply plugins/webp-uploads/hooks.php:925]: Ok, makes sense. We also have `wp_check_filetype_and_ext` in core that might be useful here.

File: plugins/webp-uploads/hooks.php (hunk 13 above)
Comment (adamsilverstein) [reply plugins/webp-uploads/hooks.php:919]: just return $file as it is should be fine.

File: plugins/webp-uploads/hooks.php (hunk 14 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php:925]: Done in https://github.com/WordPress/performance/pull/2024/commits/e39b2c73889071a07eaf85d27244eb4d4768274c.

**Review by adamsilverstein — APPROVED** [review]
Looks good, nice work!

**Comment by adamsilverstein** [comment]
I opened a ticket to move this fix upstream to core since I expect it is a bug there: https://core.trac.wordpress.org/ticket/63773#ticket

**Comment by adamsilverstein** [comment]
@b1ink0 if you have a moment, can you please review my fix and test for core: https://github.com/WordPress/wordpress-develop/pull/9368. The tests would benefit from being expanded to be more through, I wanted to capture the simplest case first to validate the test fails before and is fixed after the change.

**Comment by b1ink0** [comment]
@adamsilverstein Yes, the patch looks good and is working all tests pass with your patch. When the logic for `imagepalettetotruecolor` is commented out, the test fails with the `imagewebp(): Palette image not supported by webp` message.

I think also adding a test to ensure the size of the converted WebP from truecolor is smaller than the palette PNG would be good, as you suggested in this PR.

Also tested Modern Image Formats version 2.5.1 installed through the WordPress plugin directory with the core patched there is no error when uploading a palette-based PNG.

File: plugins/webp-uploads/hooks.php [hunk 16]
```diff
@@ -803,3 +803,64 @@ function webp_uploads_enable_additional_mime_type_support_for_all_sizes( array $
...
+ *
+ * @since n.e.x.t
+ *
+ * @param array<string, mixed>|mixed $file The uploaded file data.
+ * @return array<string, mixed>|mixed The modified file data.
+ */
+function webp_uploads_convert_palette_png_to_truecolor( $file ) {
+	if ( ! is_array( $file ) ) {
+		return $file;
+	}
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]: I think it's slightly better to fix up the type of the filtered argument rather than passing through the bad value type.

```suggestion
 * @return array<string, mixed> The modified file data.
 */
function webp_uploads_convert_palette_png_to_truecolor( $file ): array {
	// Because plugins do bad things.
	if ( ! is_array( $file ) ) {
		$file = array();
	}
```

**Review by westonruter — COMMENTED** [review]
Just a couple tiny suggestions.

File: plugins/webp-uploads/tests/test-load.php [hunk 17]
```diff
@@ -1116,4 +1116,153 @@ public function test_that_it_should_convert_webp_to_avif_on_upload(): void {
...
+	}
+
+	/**
+	 * Tests the webp_uploads_convert_palette_png_to_truecolor function with various conditions.
+	 *
+	 * @covers ::webp_uploads_convert_palette_png_to_truecolor
+	 */
+	public function test_webp_uploads_convert_palette_png_to_truecolor_conditions(): void {
+		$invalid_file = 'test';
+		$this->assertSame( $invalid_file, webp_uploads_convert_palette_png_to_truecolor( $invalid_file ) );
```
Comment (westonruter) [inline plugins/webp-uploads/tests/test-load.php]: If my other suggestion is accepted:

```suggestion
		$this->assertSame( array(), webp_uploads_convert_palette_png_to_truecolor( 'test' ) );
```

**Comment by westonruter** [comment]
Here's a build of the plugin in this branch's current state: [webp-uploads.zip](https://github.com/user-attachments/files/21804314/webp-uploads.zip)

File: plugins/webp-uploads/hooks.php (hunk 16 above)
Comment (b1ink0) [reply plugins/webp-uploads/hooks.php]: I'm not sure about this there are conflicting reviews. 😅
See: https://github.com/WordPress/performance/pull/2024#discussion_r2217410708.

Comment (westonruter) [reply plugins/webp-uploads/hooks.php]: I think you'll see my suggestion is used elsewhere in the PL plugins, and it has the benefit of being able to specify the `array` type as the return value, rather than `mixed`.

**Comment by westonruter** [comment]
Fix confirmed: https://github.com/WordPress/performance/issues/1576#issuecomment-3195503777

**Review by westonruter — APPROVED** [review]
