### PR TITLE
Remove `no-cache` and `max-age=0` from bfcache failure conditions

### LINKED ISSUE #1825: Test for bfcache compatibility incorrectly flags use of `no-cache` and `max-age=0`
The bfcache Site Health test (#1692 fixed via #1807) is currently checking for `no-cache` and `max-age=0` when in reality it shouldn't be.

From [Back/forward cache](https://web.dev/articles/bfcache#:~:text=For%20pages%20that,page%27s%20bfcache%20eligibility.) on Web.dev:

<blockquote><p>For pages that need to always serve up-to-date content—and that content does not contain sensitive information—use <code translate="no" dir="ltr">Cache-Control: no-cache</code> or <code translate="no" dir="ltr">Cache-Control: max-age=0</code>. These directives instruct the browser to revalidate the content before serving it, and they don't affect a page's bfcache eligibility.</p><p>Note that when a page is restored from bfcache, it is restored from memory, not from the HTTP cache. As a result, directives like <code translate="no" dir="ltr">Cache-Control: no-cache</code> or <code translate="no" dir="ltr">Cache-Control: max-age=0</code> are not taken into account, and no revalidation occurs before the content is displayed to the user.</p></blockquote>

This [article from Nitropack](https://nitropack.io/blog/post/back-forward-cache#:~:text=3.%20Use%20Cache%2DControl%3A%20no%2Dstore%20only%20with%20information%2Dsensitive%20pages):

> ## 3. Use Cache-Control: no-store only with information-sensitive pages
> If a page contains sensitive information and caching is inappropriate, then Cache-Control: no-store should be used to prevent it from being eligible for bfcache. On the other hand, if a page doesn't contain sensitive information and always requires up-to-date content, Cache-Control: no-cache or Cache-Control: max-age=0 can be used. These directives prompt the browser to revalidate the content before serving it and don't impact a page's eligibility for bfcache.

And in [Monitoring bfcache blocking reasons](https://developer.mozilla.org/en-US/docs/Web/API/Performance_API/Monitoring_bfcache_blocking_reasons#response-cache-control-no-store) on MDN, the only blocking reason for `Cache-Control` is the `no-store` directive:

<blockquote><dl><dt id="response-cache-control-no-store"><a href="#response-cache-control-no-store"><code>"response-cache-control-no-store"</code></a></dt><dd>
<p>The page uses <code>no-store</code> as a <a href="/en-US/docs/Web/HTTP/Headers/Cache-Control"><code>Cache-Control</code></a> header value.</p>
</dd></dl></blockquote>

And the Lighthouse audit strings:

https://github.com/GoogleChrome/lighthouse/blob/af88b935e3669601cef2d6adf7186a6624731446/core/lib/bf-cache-strings.js#L172-L175
https://github.com/GoogleChrome/lighthouse/blob/af88b935e3669601cef2d6adf7186a6624731446/core/lib/bf-cache-strings.js#L196-L200

Also, I tested serving pages with `Cache-Control: no-cache, max-age=0` and the DevTools check showed it was successfully served from bfcache:

> Image

However, if I instead serve `Cache-Control: no-store` then I get a failure:

> Image

So the `no-cache` and `max-age=0` checks should be removed from the test.

### PR DESCRIPTION
**Pull request by westonruter**
## Summary

Fixes #1825

### CODE REVIEW

File: plugins/performance-lab/includes/site-health/bfcache-compatibility-headers/helper.php [hunk 1]
```diff
@@ -66,41 +66,15 @@ function perflab_bfcache_compatibility_headers_check(): array {
...
-							', ',
-							array_map(
-								static function ( $header ) {
-									return "<code>$header</code>";
-								},
-								$found_directives
-							)
-						)
-					),
+					__( "The <code>Cache-Control</code> response header for an unauthenticated request to the home page includes the <code>no-store</code> directive. This can affect the performance of your site by preventing fast back/forward navigations (via the browser's bfcache).", 'performance-lab' ),
```
Comment (felixarntz) [inline plugins/performance-lab/includes/site-health/bfcache-compatibility-headers/helper.php]: Not a blocker, but for the code constructs using placeholders would be nice, since they shouldn't be translatable - plus it avoids the need for translators to deal with HTML in the string, which is always good if it can be avoided.
```suggestion
					sprintf(
						/* translators: 1: header name, 2: problematic directive */
						__( "The %1$s response header for an unauthenticated request to the home page includes the %2$s directive. This can affect the performance of your site by preventing fast back/forward navigations (via the browser's bfcache).", 'performance-lab' ),
						'<code>Cache-Control</code>',
						'<code>no-store</code>'
					),
```

**Review by felixarntz — APPROVED** [review]
@westonruter Great catch, LGTM! Just one non-blocking feedback.

File: plugins/performance-lab/includes/site-health/bfcache-compatibility-headers/helper.php (hunk 1 above)
Comment (westonruter) [reply plugins/performance-lab/includes/site-health/bfcache-compatibility-headers/helper.php]: That works: ffa9c2576 (with a couple tweaks)

image
