### PR TITLE
Handle missing Web Crypto API in non-HTTPS contexts when generating the already-submitted `sessionStorage` key

### LINKED ISSUE #1904: Optimization Detective not working on non-HTTPS site
## Bug Description

The detection script uses `crypto.subtle.digest`, but the crypto API is only available in secure (HTTPS) contexts.

I noticed by accident as I was accessing my local site without HTTPS.

Then I got a JS error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
```

While most sites are using HTTPS nowadays anyway, I think this potential error should be caught to avoid errors.

It can then log to the console that detection is not possible or so.

## Steps to reproduce

1. Install on HTTPS site
2. View site
3. See unhandled JS error

## Additional Context

 - PHP Version: 
 - Browser: [e.g. chrome, safari]
 - Plugin Version: [e.g. 22]

### PR DESCRIPTION
**Pull request by ShyamGadde**
## Summary

Fixes #1904 

## Relevant technical choices

- Returns `null` instead of blocking detection when the Web Crypto API is unavailable, allowing the script to continue running while still tracking session data when possible.  
- Logs a warning when the Web Crypto API is unavailable, advising users to use HTTPS or localhost for testing.
- Catches errors during hashing and logs them instead of failing outright.
- Ensures sessionStorage is only accessed if a valid key is generated.

### CODE REVIEW

File: plugins/optimization-detective/detect.js [hunk 1]
```diff
@@ -161,6 +161,17 @@ async function getAlreadySubmittedSessionStorageKey(
...
 ) {
+	// Check if crypto.subtle is available.
+	if ( ! window.crypto || ! window.crypto.subtle ) {
+		// eslint-disable-next-line no-console
+		console.warn(
+			'[Optimization Detective] Web Crypto API is not available. This API is only available in secure contexts (HTTPS). Detection cannot proceed. If you are testing locally, ensure you use HTTPS or run on localhost.'
+		);
+		throw new Error(
+			'Web Crypto API is unavailable in this context. Try using HTTPS or localhost.'
+		);
```
Comment (westonruter) [inline plugins/optimization-detective/detect.js]: Shouldn't this reuse the logger?

```suggestion
		error(
			'[Optimization Detective] Web Crypto API is not available. This API is only available in secure contexts (HTTPS). Detection cannot proceed. If you are testing locally, ensure you use HTTPS or run on localhost.'
		);
		return;
```

File: plugins/optimization-detective/detect.js [hunk 2]
```diff
@@ -391,27 +402,33 @@ export default async function detect( {
...
-			sessionStorage.getItem( alreadySubmittedSessionStorageKey ),
-			10
-		);
-		if (
-			! isNaN( previousVisitTime ) &&
-			( getCurrentTime() - previousVisitTime ) / 1000 < freshnessTTL
-		) {
-			log(
-				'The current client session already submitted a fresh URL Metric for this URL so a new one will not be collected now.'
+	let alreadySubmittedSessionStorageKey;
```
Comment (westonruter) [inline plugins/optimization-detective/detect.js]: Is this change needed? The above check for `crypto.subtle` should mean this change won't be needed, right?

Comment (westonruter) [reply plugins/optimization-detective/detect.js]: For example, if I go to http://httpforever.com/ then I see that `crypto.subtle` is `undefined` in the console.

Comment (ShyamGadde) [reply plugins/optimization-detective/detect.js]: Yes, although we check for `crypto.subtle`, I think the try/catch is still necessary.

If we were to just return early from `getAlreadySubmittedSessionStorageKey` when `crypto.subtle` is unavailable (instead of throwing an error), the function would return `undefined` and the key would be `undefined` for all URLs the user visits. This could lead to misleading messages like "The current client session already submitted a fresh URL Metric..." before the freshnessTTL expires.

Comment (ShyamGadde) [reply plugins/optimization-detective/detect.js]: Another option would be to just throw a simple error when Web Crypto API is not available in the `getAlreadySubmittedSessionStorageKey` function (without logging):
```js
throw new Error( 'Web Crypto API is unavailable' );
```

And then handle the detailed messaging in the catch block inside `detect`:
```js
catch (err) {
  if ( err.message === 'Web Crypto API is unavailable' ) {
    error(
      'Unable to create session storage key: Web Crypto API is not available. This API is only available in secure contexts (HTTPS). Detection cannot proceed. If you are testing locally, ensure you use HTTPS or run on localhost.'
    );
  } else {
    error('Unable to create session storage key: ' + err.message);
  }
  return;
}
```
This approach also avoids duplicate error messages.

Comment (westonruter) [reply plugins/optimization-detective/detect.js]: Ok, but why would `crypto.subtle` need the try/catch?

Comment (westonruter) [reply plugins/optimization-detective/detect.js]: Looks like if SHA-1 isn't available: https://g.co/gemini/share/465d60ae25b7

Comment (ShyamGadde) [reply plugins/optimization-detective/detect.js]: > Ok, but why would crypto.subtle need the try/catch?

I'm sorry for not being clear. I wasn't suggesting adding a try/catch in the `getAlreadySubmittedSessionStorageKey` function itself. Instead, I was referring to the try/catch block I added in the detect function where we call `await getAlreadySubmittedSessionStorageKey()`. 

The check for `crypto.subtle` is in the `getAlreadySubmittedSessionStorageKey` function, which throws an error when it's not available. Then, that error is caught in the `detect` function's try/catch block.

Comment (ShyamGadde) [reply plugins/optimization-detective/detect.js]: I've implemented this approach in a66325a to illustrate what I was describing.

File: plugins/optimization-detective/detect.js [hunk 3]
```diff
@@ -161,6 +161,10 @@ async function getAlreadySubmittedSessionStorageKey(
 	currentUrl,
 	urlMetricGroupStatus
 ) {
+	if ( ! window.crypto || ! window.crypto.subtle ) {
+		throw new Error( 'Web Crypto API is unavailable' );
+	}
+
```
Comment (westonruter) [inline plugins/optimization-detective/detect.js]:
```suggestion
```

File: plugins/optimization-detective/detect.js [hunk 4]
```diff
@@ -392,12 +396,25 @@ export default async function detect( {
...
+			);
+	} catch ( err ) {
+		if ( err.message === 'Web Crypto API is unavailable' ) {
+			error(
+				'Unable to create session storage key: Web Crypto API is not available. This API is only available in secure contexts (HTTPS). Detection cannot proceed. If you are testing locally, ensure you use HTTPS or run on localhost.'
+			);
+		} else {
+			error( 'Unable to create session storage key: ' + err.message );
+		}
+		return;
```
Comment (westonruter) [inline plugins/optimization-detective/detect.js]:
```suggestion
		alreadySubmittedSessionStorageKey =
			await getAlreadySubmittedSessionStorageKey(
				currentETag,
				currentUrl,
				urlMetricGroupStatus
			);
	} catch ( err ) {
		alreadySubmittedSessionStorageKey = 'odSubmitted';
		error( 'Unable to create session storage key. This may be due to not running on HTTPS. Error: ' + err.message );
```

Comment (westonruter) [reply plugins/optimization-detective/detect.js]: Or, instead of this, maybe this `try`/`catch` would make sense inside of the `getAlreadySubmittedSessionStorageKey` function?

File: plugins/optimization-detective/detect.js (hunk 3 above)
Comment (westonruter) [reply plugins/optimization-detective/detect.js]: Alternatively:

```suggestion
	if ( ! window.crypto || ! window.crypto.subtle ) {
		warn( 'Unable to create session storage key: Web Crypto API is not available. This API is only available in secure contexts (HTTPS). Detection cannot proceed. If you are testing locally, ensure you use HTTPS or run on localhost.' );
		return 'odSubmitted';
	}

```

And then the rest of this function can be wrapped in a `try`/`catch` where in the `catch` block it returns `'odSubmitted'` after emitting a warning.

File: plugins/optimization-detective/detect.js (hunk 2 above)
Comment (westonruter) [reply plugins/optimization-detective/detect.js]: Thanks for that. Here's another iteration on top of your suggestion: what if we have it so that the function just returns a constant string in the case of an error? This would essentially be bringing the functionality back to how it behaved before the URL hashing was introduced. Oh wait, actually that functionality is still in place:

https://github.com/WordPress/performance/blob/a66325a28775fb1ad4d3459671e8c48c05b6f5e6/plugins/optimization-detective/detect.js#L475-L478

So how about it just return `null` to indicate that this isn't available? There is already storage locking going on with a session storage key, so this is basically a secondary (redundant?) lock.

File: plugins/optimization-detective/detect.js (hunk 3 above)
Comment (westonruter) [reply plugins/optimization-detective/detect.js]: But no, see https://github.com/WordPress/performance/pull/1911#discussion_r1989754696. It can just return `null` then.

File: plugins/optimization-detective/detect.js (hunk 2 above)
Comment (westonruter) [reply plugins/optimization-detective/detect.js]: Here's what I have in mind: d5679ec87

This will ensure that URL Metrics can continue to be collected on HTTP sites. The already-submitted "lock" is just intended to increase the diversity of the URL Metrics being collected, so if it's not available it's not a big deal. Better to skip it altogether in favor of collecting URL Metrics as opposed to doing nothing.

Comment (ShyamGadde) [reply plugins/optimization-detective/detect.js]: Thanks for iterating on this! That approach makes a lot of sense—returning `null` instead of blocking detection entirely keeps things functional while still maintaining some level of session tracking. I hadn't fully considered that before.

**Review by westonruter — APPROVED** [review]
Thank you for iterating on this with me!

File: plugins/optimization-detective/detect.js [hunk 5]
```diff
@@ -154,35 +154,52 @@ function getGroupForViewportWidth( viewportWidth, urlMetricGroupStatuses ) {
...
+	urlMetricGroupStatus,
+	{ warn, error }
 ) {
-	const message = [
-		currentETag,
-		currentUrl,
-		urlMetricGroupStatus.minimumViewportWidth,
-		urlMetricGroupStatus.maximumViewportWidth || '',
-	].join( '-' );
+	if ( ! window.crypto || ! window.crypto.subtle ) {
```
Comment (swissspidy) [inline plugins/optimization-detective/detect.js:166]: Nit: only checking `window.crypto` should suffice. There's no combination where the former is available but the latter isn't.

File: plugins/optimization-detective/detect.js [hunk 6]
```diff
@@ -154,35 +154,52 @@ function getGroupForViewportWidth( viewportWidth, urlMetricGroupStatuses ) {
...
+		 *
+		 * The SHA-1 algorithm is chosen since it is the fastest and there is no need for cryptographic security.
+		 */
+		const msgBuffer = new TextEncoder().encode( message );
+		const hashBuffer = await crypto.subtle.digest( 'SHA-1', msgBuffer );
+		const hashHex = Array.from( new Uint8Array( hashBuffer ) )
+			.map( ( b ) => b.toString( 16 ).padStart( 2, '0' ) )
+			.join( '' );
+		return `odSubmitted-${ hashHex }`;
+	} catch ( err ) {
```
Comment (swissspidy) [inline plugins/optimization-detective/detect.js:196]: What possible error is this catching now? The function returns early if crypto isn't available.

Comment (westonruter) [reply plugins/optimization-detective/detect.js:196]: I had wondered the same, but turns out this can throw errors like if the algorithm isn't available, at least according to Gemini: https://g.co/gemini/share/465d60ae25b7

File: plugins/optimization-detective/detect.js (hunk 5 above)
Comment (westonruter) [reply plugins/optimization-detective/detect.js:166]: So like so?

```suggestion
	if ( ! window.crypto ) {
```

Comment (westonruter) [reply plugins/optimization-detective/detect.js:166]: Nevertheless someone could try to polyfill `crypto.getRandomValues()` but not define `crypto.subtle`.

Comment (swissspidy) [reply plugins/optimization-detective/detect.js:166]: > So like so?

Yes that's what I meant.

> Nevertheless someone could try to polyfill `crypto.getRandomValues()` but not define `crypto.subtle`.

Sounds unlikely to me but if we are concerned about that then we should keep the check.

**Review by swissspidy — APPROVED** [review]
