### PR TITLE
Fix SQLite notices related to undefined properties

### LINKED ISSUE #599: sqlite module: Notices thrown during WordPress import
## Bug Description ##

Notices thrown when using the WordPress post / page / media importer 

## Steps to reproduce

1. Make sure WP_DEBUG and WP_DEBUG_LOG are on.
1. On some working site with with a few posts or pages, do Tools > Export to get an XML file.
2. Go to a site with the sqlite module enabled, that is, one that's using the sqlite database.
3. Do Tools > Import, then download the WordPress importer.
4. Import your XML file.
5. Observe all the notices. 

I'm trying to track this down. Will keep you posted.

## Notices from debug.log

A lot of notices looking like this

```
[13-Dec-2022 15:42:18 UTC] PHP Notice:  Trying to get property 'ID' of non-object in /var/www/sqlite.lan.plumislandmedia.net/wp-includes/post.php on line 5405
[13-Dec-2022 15:42:18 UTC] PHP Stack trace:
[13-Dec-2022 15:42:18 UTC] PHP   1. {main}() /var/www/sqlite.lan.plumislandmedia.net/wp-admin/admin.php:0
[13-Dec-2022 15:42:18 UTC] PHP   2. WP_Import->dispatch() /var/www/sqlite.lan.plumislandmedia.net/wp-admin/admin.php:364
[13-Dec-2022 15:42:18 UTC] PHP   3. WP_Import->import() /var/www/sqlite.lan.plumislandmedia.net/wp-content/plugins/wordpress-importer/class-wp-import.php:65
[13-Dec-2022 15:42:18 UTC] PHP   4. WP_Import->process_posts() /var/www/sqlite.lan.plumislandmedia.net/wp-content/plugins/wordpress-importer/class-wp-import.php:89
[13-Dec-2022 15:42:18 UTC] PHP   5. wp_insert_post() /var/www/sqlite.lan.plumislandmedia.net/wp-content/plugins/wordpress-importer/class-wp-import.php:746
[13-Dec-2022 15:42:18 UTC] PHP   6. wp_transition_post_status() /var/www/sqlite.lan.plumislandmedia.net/wp-includes/post.php:4607

[13-Dec-2022 15:42:18 UTC] PHP Notice:  Trying to get property 'post_type' of non-object in /var/www/sqlite.lan.plumislandmedia.net/wp-includes/post.php on line 4706
[13-Dec-2022 15:42:18 UTC] PHP Stack trace:
[13-Dec-2022 15:42:18 UTC] PHP   1. {main}() /var/www/sqlite.lan.plumislandmedia.net/wp-admin/admin.php:0
[13-Dec-2022 15:42:18 UTC] PHP   2. WP_Import->dispatch() /var/www/sqlite.lan.plumislandmedia.net/wp-admin/admin.php:364
[13-Dec-2022 15:42:18 UTC] PHP   3. WP_Import->import() /var/www/sqlite.lan.plumislandmedia.net/wp-content/plugins/wordpress-importer/class-wp-import.php:65
[13-Dec-2022 15:42:18 UTC] PHP   4. WP_Import->process_posts() /var/www/sqlite.lan.plumislandmedia.net/wp-content/plugins/wordpress-importer/class-wp-import.php:89
[13-Dec-2022 15:42:18 UTC] PHP   5. wp_insert_post() /var/www/sqlite.lan.plumislandmedia.net/wp-content/plugins/wordpress-importer/class-wp-import.php:746
```

## Additional Context

 - PHP Version: 7.4.3
 - OS: Ubuntu 20.04
 - Browser: Firefox, Chrome
 - Plugin Version: 1.7.0
 - Device: Windows laptop with Ubuntu VM.
 - SQLite: 3.31.1

### PR DESCRIPTION
**Pull request by aristath**
## Summary

Fixes #599 

In addition to the above fix, I encountered some other notices when testing various plugins:
```
PHP Notice:  Undefined property: stdClass::$name in class-perflab-sqlite-pdo-engine.php on line 1338
PHP Notice:  Undefined property: stdClass::$type in class-perflab-sqlite-pdo-engine.php on line 1339
PHP Notice:  Undefined property: stdClass::$notnull in class-perflab-sqlite-pdo-engine.php on line 1340
PHP Notice:  Undefined property: stdClass::$pk in class-perflab-sqlite-pdo-engine.php on line 1341
PHP Notice:  Undefined property: stdClass::$dflt_value in class-perflab-sqlite-pdo-engine.php on line 1342
```

This PR adds some additional checks to ensure that `$row` is an object, and the properties exist before using them.

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

File: modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-db.php [hunk 1]
```diff
@@ -81,7 +81,7 @@ public function select( $db, $dbh = null ) {
 	 * @return string escaped
 	 */
 	function _real_escape( $str ) {
-		return SQLite3::escapeString( $str );
+		return addslashes( $str );
```
Comment (aristath) [inline modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-db.php:84]: This is the line that fixes #599

File: modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-engine.php [hunk 2]
```diff
@@ -1335,12 +1335,25 @@ private function convert_to_columns_object() {
...
+				if ( property_exists( $row, 'notnull' ) ) {
+					$_columns['Null'] = $row->notnull ? 'NO' : 'YES';
+				}
+				if ( property_exists( $row, 'pk' ) ) {
+					$_columns['Key'] = $row->pk ? 'PRI' : '';
+				}
+				if ( property_exists( $row, 'dflt_value' ) ) {
+					$_columns['Default'] = $row->dflt_value;
+				}
+				$_results[] = new Perflab_SQLite_Object_Array( $_columns );
```
Comment (aristath) [inline modules/database/sqlite/wp-includes/sqlite/class-perflab-sqlite-pdo-engine.php:1356]: This is some additional defensive coding to ensure there are no errors.

**Review by felixarntz — APPROVED** [review]
@aristath Great work!

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @aristath Now everything is good with import.
