### PR TITLE
Fix Modern Image Format not cropping image if crop is an array

### LINKED ISSUE #1881: Modern Image Format no crop, if crop is array
Hi, I just discover bug, if you have array in crop

```php
    add_image_size( 'custom-size', 220, 220, array( 'left', 'top' ) );
```

or

```php
    add_filter( 'pre_option_medium_crop', function() { return array( 'center', 'center' ); } );
```

bug is in function `webp_uploads_generate_image_size()`

```php
    if ( isset( $sizes[ $size ]['crop'] ) ) {
        $size_data['crop'] = (bool) $sizes[ $size ]['crop'];
```

wp image editor accept array or bool
https://developer.wordpress.org/reference/classes/wp_image_editor/resize/

Thank you

### PR DESCRIPTION
**Pull request by b1ink0**
## Summary

Fixes #1881 

## Relevant technical choices

This PR fixes the issue of Modern Image Format not cropping image if crop is an array.

Below is the code snippet to reproduce the bug:
```php
add_filter( 'pre_option_medium_crop', function() { return array( 'right', 'right' ); } );
```

### CODE REVIEW

File: plugins/webp-uploads/helper.php [hunk 1]
```diff
@@ -240,8 +240,21 @@ function webp_uploads_generate_image_size( int $attachment_id, string $size, str
...
+				count( $sizes[ $size ]['crop'] ) === 2 &&
+				isset( $sizes[ $size ]['crop'][0] ) &&
+				isset( $sizes[ $size ]['crop'][1] ) &&
+				is_string( $sizes[ $size ]['crop'][0] ) &&
+				is_string( $sizes[ $size ]['crop'][1] )
+			) ||
+			is_bool( $sizes[ $size ]['crop'] )
+		)
+	) {
+		$size_data['crop'] = $sizes[ $size ]['crop'];
```
Comment (felixarntz) [inline plugins/webp-uploads/helper.php]: I don't think we need to do all this granular validation on the `crop` key. WordPress Core doesn't do it and lets everything through. It only ensures at the very last point when it's actually used (in the `image_resize_dimensions()` function) that it has the correct format.

I think allowing any value here to pass through makes more sense as it makes our code aligned with Core and more future-proof, in case Core would later add support for other types for the `crop` key. It's also in line with `width` and `height` above, where we don't verify the type.
```suggestion
	if ( isset( $sizes[ $size ]['crop'] ) ) {
		$size_data['crop'] = $sizes[ $size ]['crop'];
```

**Review by felixarntz — COMMENTED** [review]
@b1ink0 This looks great! Just one recommendation to simplify the implementation and make it more future-proof.

Another point of feedback: It would be great if you could add a unit test to verify the fix. You could write a test that calls `webp_uploads_generate_additional_image_source()` with `$size_data['crop']` set to an array and verify the output is correct.

File: plugins/webp-uploads/helper.php (hunk 1 above)
Comment (b1ink0) [reply plugins/webp-uploads/helper.php]: I added granular checks to ensure that the Modern Image Formats code does not produce errors on invalid input. However, to future-proof code, as you suggested, simplifying the condition makes more sense. Fixed in https://github.com/WordPress/performance/pull/1887/commits/af35deb7a85af0b90e6823eec9dbc36fc3e65ebc.

**Review by westonruter — APPROVED** [review]
The changes look good to me!

**Review by felixarntz — APPROVED** [review]
@b1ink0 This looks excellent, thank you for the iterations and the unit test!
