### PR TITLE
Fix image focal point bug when dominant color is enabled by not overriding `style` attribute

### LINKED ISSUE #562: With Dominant Color enabled, loses focal point settings
## Bug Description

When the Dominant Color is enabled in the performance plug-in the image looses its focal point

## Steps to reproduce

1. make sure Dominant Color is enabled in performance plug-in
2. Go to a page or post
3. add a cover to the post/page
4. set a focal point
5. update image and see the image just centering
6. disable Dominant Color and reload page/post
7. the focal point set in admin is used

## Additional Context

 - PHP Version: 7.4.32 
 - OS: MacOS
 - Browser: Chrome
 - Plugin Version: 1.6.0
 - Device: MacBook pro m1 pro

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
## Summary

Fixes #562

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Review by pbearne — APPROVED** [review]

**Review by mehulkaklotar — APPROVED** [review]
@mukeshpanchal27 LGTM 🚀

File: modules/images/dominant-color/load.php [hunk 1]
```diff
@@ -112,12 +112,15 @@ function dominant_color_img_tag_add_dominant_color( $filtered_image, $context, $
...
 	$extra_class = '';
 
 	if ( ! empty( $image_meta['dominant_color'] ) ) {
 		$data .= sprintf( 'data-dominant-color="%s" ', esc_attr( $image_meta['dominant_color'] ) );
-		$style = 'style="--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . ';" ';
+		if ( str_contains( $filtered_image, ' style="' ) ) {
+			$filtered_image = str_replace( ' style="', ' style="--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . ';', $filtered_image );
+		} else {
+			$filtered_image = str_replace( '<img ', '<img style="--dominant-color: #' . esc_attr( $image_meta['dominant_color'] ) . ';" ', $filtered_image );
+		}
```
Comment (felixarntz) [inline modules/images/dominant-color/load.php:123]: Can you please add a unit test for this change?

You could call `dominant_color_img_tag_add_dominant_color()` with an `img` tag that already has a `style` attribute to make sure it is combined correctly.

File: modules/images/dominant-color/load.php [hunk 2]
```diff
@@ -126,9 +129,10 @@ function dominant_color_img_tag_add_dominant_color( $filtered_image, $context, $
 		$extra_class  = $image_meta['has_transparency'] ? 'has-transparency' : 'not-transparent';
 	}
 
-	if ( ! empty( $data ) || ! empty( $style ) ) {
-		$filtered_image = str_replace( '<img ', '<img ' . $data . $style, $filtered_image );
+	if ( ! empty( $data ) ) {
+		$filtered_image = str_replace( '<img ', '<img ' . $data, $filtered_image );
 	}
+
```
Comment (felixarntz) [inline modules/images/dominant-color/load.php:135]: Nice, I like a lot how this PR separates the logic for adding `$data` from adding `$style` to the image tag. This makes it much easier to follow the code here.

**Review by felixarntz — COMMENTED** [review]
@mukeshpanchal27 Production code implementation looks good, could you please add a unit test to cover that the change works correctly though?

File: modules/images/dominant-color/load.php (hunk 2 above)
Comment (mukeshpanchal27) [reply modules/images/dominant-color/load.php:135]: 👍

File: modules/images/dominant-color/load.php (hunk 1 above)
Comment (mukeshpanchal27) [reply modules/images/dominant-color/load.php:123]: I appreciate the comments. I have included unit tests that validate the most recent update at https://github.com/WordPress/performance/pull/582/commits/1d8ecf3e626221fe899f5047f96518e1acac509d.

File: tests/modules/images/dominant-color/dominant-color-test.php [hunk 3]
```diff
@@ -108,6 +108,25 @@ public function test_tag_add_adjust_to_image_attributes( $image_path, $expected_
 		$this->assertEquals( $filtered_image_mock_lazy_load, $filtered_image_tags_not_added );
 	}
 
+	/**
+	 * Tests dominant_color_img_tag_add_dominant_color() do not override the style attribute.
+	 *
+	 * @covers ::dominant_color_img_tag_add_dominant_color
+	 */
+	public function test_dominant_color_do_not_override_the_style_attribute_in_img_tag() {
```
Comment (costdev) [inline tests/modules/images/dominant-color/dominant-color-test.php]:
```suggestion
	public function test_dominant_color_should_not_replace_existing_inline_styles() {
```

Also suggest that the test method description is changed to:

> Tests that dominant_color_img_tag_add_dominant_color() does not replace existing inline styles.

Comment (mukeshpanchal27) [reply tests/modules/images/dominant-color/dominant-color-test.php]: Thanks for the review.

File: tests/modules/images/dominant-color/dominant-color-test.php [hunk 4]
```diff
@@ -108,6 +108,25 @@ public function test_tag_add_adjust_to_image_attributes( $image_path, $expected_
...
+
+		list( $src, $width, $height ) = wp_get_attachment_image_src( $attachment_id );
+
+		$filtered_image = sprintf( '<img src="%s" width="%d" height="%d" />', $src, $width, $height );
+
+		$this->assertStringContainsString( 'style="--dominant-color: #fe0000;"', dominant_color_img_tag_add_dominant_color( $filtered_image, 'the_content', $attachment_id ) );
+
+		$filtered_image_with_style_tag = sprintf( '<img style="color: #ffffff;" src="%s" width="%d" height="%d" />', $src, $width, $height );
+
+		$this->assertStringContainsString( 'style="--dominant-color: #fe0000; color: #ffffff;"', dominant_color_img_tag_add_dominant_color( $filtered_image_with_style_tag, 'the_content', $attachment_id ) );
```
Comment (costdev) [inline tests/modules/images/dominant-color/dominant-color-test.php]: The first assertion appears to be testing the expected behaviour of `dominant_color_img_tag_add_dominant_color()` when there are no existing inline styles.

Should this test method actually be two different test methods?

- `test_dominant_color_img_tag_add_dominant_color_should_add_dominant_color_inline_style()`
- `test_dominant_color_img_tag_add_dominant_color_should_not_replace_existing_inline_styles()`

Comment (costdev) [reply tests/modules/images/dominant-color/dominant-color-test.php]: Alternatively, you could use a data provider, passing `$filtered_image` and `$expected` to the test method.

The test method itself could be called `test_dominant_color_img_tag_add_dominant_color_should_add_dominant_color_inline_style()`.

i.e.
```php
public function test_dominant_color_img_tag_add_dominant_color_should_add_dominant_color_inline_style( $filtered_image, $expected ) {
	$attachment_id = self::factory()->attachment->create_upload_object( TESTS_PLUGIN_DIR . '/tests/testdata/modules/images/dominant-color/red.jpg' );
	wp_maybe_generate_attachment_metadata( get_post( $attachment_id ) );

	list( $src, $width, $height ) = wp_get_attachment_image_src( $attachment_id );

	$filtered_image = sprintf( $filtered_image, $src, $width, $height );

	$this->assertStringContainsString(
		$expected,
		dominant_color_img_tag_add_dominant_color( $filtered_image, 'the_content', $attachment_id )
	);
}
```

With the datasets:
```php
return array(
	'no existing inline styles' => array(
		'filtered_image' => '<img src="%s" width="%d" height="%d" />',
		'expected'       => 'style="--dominant-color: #fe0000;"',
	),
	'existing inline styles'    => array(
		'filtered_image' => '<img style="color: #ffffff;" src="%s" width="%d" height="%d" />',
		'expected'       => 'style="--dominant-color: #fe0000; color: #ffffff;"',
	),
);
```

Comment (mukeshpanchal27) [reply tests/modules/images/dominant-color/dominant-color-test.php]: Thank you Colin for the feedback. Unit test updated in [1dc7a4e](https://github.com/WordPress/performance/pull/582/commits/1dc7a4e84a416e77c0fb171d1be2cc1603d1e5f7)

File: tests/modules/images/dominant-color/dominant-color-test.php [hunk 5]
```diff
@@ -108,6 +108,44 @@ public function test_tag_add_adjust_to_image_attributes( $image_path, $expected_
 		$this->assertEquals( $filtered_image_mock_lazy_load, $filtered_image_tags_not_added );
 	}
 
+	/**
+	 * Tests that dominant_color_img_tag_add_dominant_color() does not replace existing inline styles.
+	 *
+	 * @dataProvider data_provider_dominant_color_check_inline_style
+	 *
+	 * @covers ::dominant_color_img_tag_add_dominant_color
```
Comment (costdev) [inline tests/modules/images/dominant-color/dominant-color-test.php:116]:
```suggestion
	 * @covers ::dominant_color_img_tag_add_dominant_color
	 *
	 * @param string $filtered_image The filtered image markup.
	 *                               Must include `src="%s" width="%d" height="%d"`.
	 * @param string $expected       The expected style attribute and value.
```
Add `@param` annotations so that other contributors know exactly what should be passed to this test method.

Comment (mukeshpanchal27) [reply tests/modules/images/dominant-color/dominant-color-test.php:116]: Sorry missed it.

**Review by costdev — APPROVED** [review]
Thanks for addressing the feedback! LGTM now 👍

File: modules/images/dominant-color/load.php (hunk 1 above)
Comment (felixarntz) [reply modules/images/dominant-color/load.php:123]: @mukeshpanchal27 Excellent, thanks!

**Review by felixarntz — APPROVED** [review]
@mukeshpanchal27 Great, tests looks solid too!
