### PR TITLE
Omit element node index in XPaths up to children of `BODY`

### LINKED ISSUE #1787: XPaths for elements in URL Metrics can omit index for children of BODY to avoid needing to vary URL Metrics by whether a user is logged-in
Discussed initially at https://github.com/WordPress/performance/pull/1759#discussion_r1896188052

URL Metrics currently are varied by whether or not a user is logged-in. This is all of the XPaths used on the page differ based on whether or not the admin bar is present, since the element index is included with each element reference. For example, the following is the XPath for the first `IMG` in post content when logged-out vs logged-in:

```diff
- /*[1][self::HTML]/*[2][self::BODY]/*[1][self::DIV]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::DIV]/*[1][self::ARTICLE]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::FIGURE]/*[1][self::PICTURE]/*[2][self::IMG]
+ /*[1][self::HTML]/*[2][self::BODY]/*[3][self::DIV]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::DIV]/*[1][self::ARTICLE]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::FIGURE]/*[1][self::PICTURE]/*[2][self::IMG]
```

The difference is that when logged-in, two new elements appear at the beginning of the `BODY`:

1. A `SCRIPT` coming from `wp_customize_support_script()` (for admin users).
2. A `DIV#wpadminbar` for the admin bar.

These result in the page wrapper `DIV`'s XPath going `*[1][self::DIV]` to `*[3][self::DIV]`.

The purpose of the element index in the XPath is to differentiate one element from another. If there are 3 `IMG` tags appearing next to each other in a post, and only the first is LCP, then it's important to be able to uniquely reference that `IMG`. Nevertheless, at the root level of a page (when directly under the `BODY`) it is highly unlikely for there to be any such ambiguity. This is because themes almost always wrap the content between `wp_body_open()` and `wp_footer()`. Classic themes typically wrap the content in a `DIV#page` element, whereas Block Themes _always_ wrap the content in a `DIV.wp-site-blocks` element. The only exception in core is that the Twenty Twenty theme which does not have one root wrapper but instead has a `HEADER`, `MAIN`, and `FOOTER` at the root. In this case too there is no possibility for ambiguity since these three are unique.

So I suggest we do the following:

1. Eliminate this logic from `od_get_normalized_query_vars()`:

https://github.com/WordPress/performance/blob/b6e5c5a4c79234229ce061ce275c5b31af4ad7e8/plugins/optimization-detective/storage/data.php#L80-L83

2. Omit the element index from the `HTML`, `BODY`, and children directly under the `BODY`. So the XPaths above would become the following:

```
/HTML/BODY/DIV/*[2][self::DIV]/*[1][self::DIV]/*[1][self::DIV]/*[1][self::ARTICLE]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::FIGURE]/*[1][self::PICTURE]/*[2][self::IMG]
```

3. Eliminate the restriction that Optimization Detective be disabled for admins. This was put in place because additional scripts often get added at `wp_body_open()`  (e.g. the `wp_customize_support_script()`). With the presence/absence of such elements printed at `wp_body_open` (and `wp_footer`) eliminated, we can eliminate this code from `od_can_optimize_response()` which would resolve #1425:

https://github.com/WordPress/performance/blob/b6e5c5a4c79234229ce061ce275c5b31af4ad7e8/plugins/optimization-detective/optimization.php#L121-L126

4. During this transitionary period in which old URL Metrics still contain the old XPaths, we can patch `OD_Element` to convert to this new format so existing optimizations will continue to apply based on old URL Metrics:

```diff
--- a/plugins/optimization-detective/class-od-element.php
+++ b/plugins/optimization-detective/class-od-element.php
@@ -52,6 +52,17 @@ class OD_Element implements ArrayAccess, JsonSerializable {
 	 */
 	public function __construct( array $data, OD_URL_Metric $url_metric ) {
 		$this->data       = $data;
+
+		// Convert old XPath scheme.
+		$xpath = preg_replace(
+			'#^/\*\[1\]\[self::HTML\]/\*\[2\]\[self::BODY\]/\*\[\d+\]\[self::(DIV)\]#',
+			'/HTML/BODY/$1',
+			$this->data['xpath']
+		);
+		if ( is_string( $xpath ) && '' !== $xpath ) {
+			$this->data['xpath'] = $xpath;
+		}
+
 		$this->url_metric = $url_metric;
 	}
```

Then in the next release or two we can eliminate this code since the old URL Metrics should have all been purged by then.

### PR DESCRIPTION
**Pull request by westonruter**
## Summary

This is the last PR to address #1787. 

Instead of an XPath like:

```
/*[1][self::HTML]/*[2][self::BODY]/*[1][self::DIV]/*[1][self::FIGURE]
```

This PR now results in the first three levels of XPaths for elements in the body to not have the node index specified:

```
/HTML/BODY/DIV/*[1][self::FIGURE]
```

This will allow for variation in the content printed at `wp_body_open` from impacting the XPaths for the rest of the document.

Note that nodes inside the `HEAD` will retain node indexes since there is no singular wrapper element in `HEAD`. 

The changes located in `tests` directories are almost all attributable to a simple search-and-replace.

Fixes #1787.

### CODE REVIEW

File: plugins/optimization-detective/class-od-html-tag-processor.php [hunk 1]
```diff
@@ -551,8 +564,12 @@ private function is_foreign_element(): bool {
...
 		if ( null === $this->current_xpath ) {
 			$this->current_xpath = '';
-			foreach ( $this->get_indexed_breadcrumbs() as list( $tag_name, $index ) ) {
-				$this->current_xpath .= sprintf( '/*[%d][self::%s]', $index + 1, $tag_name );
+			foreach ( $this->get_indexed_breadcrumbs() as $i => list( $tag_name, $index ) ) {
+				if ( $i < 2 || ( 2 === $i && '/HTML/BODY' === $this->current_xpath ) ) {
+					$this->current_xpath .= "/$tag_name";
+				} else {
+					$this->current_xpath .= sprintf( '/*[%d][self::%s]', $index + 1, $tag_name );
+				}
```
Comment (westonruter) [inline plugins/optimization-detective/class-od-html-tag-processor.php:582]: All of the changes in this PR are a consequence of this change here.

File: plugins/optimization-detective/class-od-html-tag-processor.php [hunk 2]
```diff
@@ -98,11 +98,22 @@ final class OD_HTML_Tag_Processor extends WP_HTML_Tag_Processor {
...
 	 *
+	 * The pattern for matching a tag /[a-zA-Z0-9:_-]+/ used here is informed by the characters found in tag names in
+	 * HTTP Archive as {@link https://docs.google.com/spreadsheets/d/1grkd2_1xSV3jvNK6ucRQ0OL1HmGTsScHuwA8GZuRLHU/edit?gid=2057119066#gid=2057119066 seen}
+	 * in Web Almanac 2022, with the only exception being the very malformed tag name `script="async"`. Note that XPaths
+	 * begin with `/HTML/BODY` followed by an index-free reference to an element which is a direct child of the BODY,
+	 * for example `/HTML/BODY/DIV`. Below this point, all tags must then have indices to disambiguate the XPaths among
+	 * siblings. For example: `/HTML/BODY/DIV/*[2][self::MAIN]/*[1][self::FIGURE]/*[2][self::IMG]`. There is no need
+	 * for there to be an index added to the `DIV` directly under the `BODY` because WordPress themes almost always use
+	 * a wrapper element: Block Themes always wrap the page in a `DIV.wp-site-blocks` element, and classic themes either
+	 * wrap the content in a `DIV#page` or else use `HEADER`, `MAIN`, and `FOOTER`.
```
Comment (felixarntz) [inline plugins/optimization-detective/class-od-html-tag-processor.php]: Omitting the index on the direct body children is a bit risky, now that I think about it. You're already covering in this doc block why it should be fine, but this is based on an assumption. It should work for sure for `html` and `body`, but there could certainly be multiple body children of the same tag. That said, since there's also the remainder of the xpath, it's unlikely there would ever be a conflict.

Given that the original rationale was specifically about direct body children and the risk of an xpath conflict being low, I think this is fine. Still, I wanted to flag this as being not 100% reliable.

Maybe it would be good to expand the comment to also mention the chance of exact matches in those direct body child xpaths to be low? In other words, even for themes that don't follow one of the two patterns described here, the chance for duplicate xpaths is very low.

**Review by felixarntz — COMMENTED** [review]
@westonruter Overall looks good to me, just one thought.

File: plugins/optimization-detective/class-od-html-tag-processor.php (hunk 2 above)
Comment (westonruter) [reply plugins/optimization-detective/class-od-html-tag-processor.php]: Yes, there can certainly be multiple children of `BODY` but in looking at themes, the children used will result in unique ancestor paths (e.g. `/HTML/BODY/DIV`, `/HTML/BODY/HEADER`). The one case where I see there being a potential conflict is:

1. A theme uses a `DIV` for header and footer, `<div id="header" role="banner">` and `<div id="footer" role="contentinfo">`, which are direct children of the `BODY`.
2. There is an element of the same tag name in the exact same relative position in both of these `DIV`:

```html
<html>
  <body>
    <div id="header" role="banner">
      <img src="header-image.jpg">
    </div>
    <div id="footer" role="contentinfo">
      <img src="footer-logo.png">
    </div>
  </body>
</html>
```

In this case, both of the `IMG` tags here will have the same XPath: `/HTML/BODY/DIV/*[1][self::IMG]`.

I did a [search](https://wpdirectory.net/search/01JHGCESJ5XTBJFRJW7ZMYNJ28) for `<div[^>]*role=["']?banner` in WPDirectory and the only example I could find with a header and footer being direct children of `BODY` is the [Prose theme](https://wordpress.org/themes/prose/) (2,000 active installs and not updated in 12 years): https://themes.trac.wordpress.org/browser/prose/1.1/header.php

```html
	<body <?php body_class(); ?>>
		<div id="site-navigation" class="navbar navbar-default navbar-static-top site-navigation" role="navigation">
...
		<!-- #site-navigation --></div>

		<div id="site-header" class="container site-header" role="banner">
...
		<!-- #site-header --></div>

		<div id="main" class="site-main">
...
```

Granted, this search assumes that a theme is using the right ARIA roles. It wouldn't account for someone using `<div id="header">`. 

How about this:

```suggestion
	 * in Web Almanac 2022, with the only exception being the very malformed tag name `script="async"`. Note that XPaths
	 * begin with `/HTML/BODY` followed by an index-free reference to an element which is a direct child of the BODY,
	 * for example `/HTML/BODY/DIV`. Below this point, all tags must then have indices to disambiguate the XPaths among
	 * siblings. For example: `/HTML/BODY/DIV/*[2][self::MAIN]/*[1][self::FIGURE]/*[2][self::IMG]`. There is little need
	 * for there to be an index added to the `DIV` directly under the `BODY` because WordPress themes almost always use
	 * a wrapper element: Block Themes always wrap the page in a `DIV.wp-site-blocks` element, and classic themes either
	 * wrap the content in a `DIV#page` or else use `HEADER`, `MAIN`, and `FOOTER`.
	 *
	 * The benefit of omitting the node index from direct children of the BODY allows for variations in content output
	 * at `wp_body_open()` without impacting the computed XPaths for subsequent tags. Omitting the node index at this
	 * level, however, does incur a slight risk of duplicate XPaths being computed. For example, if a theme has a
	 * `<div id="header" role="banner">` and a `<div id="footer" role="contentinfo">` which are both direct descendants
	 * of `BODY`, then it is possible for an XPath like `/HTML/BODY/DIV/*[1][self::IMG]` to be duplicated if both of
	 * these `DIV` elements has an `IMG` as the first child. The conflict could arise for any tags of the same name in
	 * the same relative position, which does not seem likely. Additionally, as noted above, themes almost always wrap
	 * the page content in an overall `DIV` or else they use semantic HTML tags like `HEADER` and `FOOTER`, so the risk
	 * is low.
```

Comment (felixarntz) [reply plugins/optimization-detective/class-od-html-tag-processor.php]: That sounds good to me.

If we later get reports of this actually happening, we can still consider reverting. But for now I would agree with the assessment that the risk is low enough.

**Review by felixarntz — APPROVED** [review]
@westonruter Approving, pending your code suggestion to expand the comment.

File: plugins/optimization-detective/class-od-html-tag-processor.php (hunk 2 above)
Comment (westonruter) [reply plugins/optimization-detective/class-od-html-tag-processor.php]: If that does happen, we could instead look at other ways to disambiguate children of the `BODY`, such as to capture the `id`, `class`, and `role` attributes to include with the XPath for that level alone.

Comment (westonruter) [reply plugins/optimization-detective/class-od-html-tag-processor.php]: Here's a proposal to disambiguate the XPaths if we find it necessary: https://github.com/WordPress/performance/pull/1797
