### PR TITLE
Replace the full size image in `the_content` with additional MIME type if available

### LINKED ISSUE #174: When generating WebPs, ensure full size is generated(`-scaled` for large images)
## Bug Description

After #152 "Full"" sized images inserted by users will still use the original jpeg image or (`-scaled` version for larger images) because the WebP version is not being generated. See https://github.com/WordPress/performance/pull/152#issuecomment-1051118813.

Proposal to fix:
* Always generate a full sized WebP version when WebP output is active
* For larger images (over `big_image_size_threshold`), generate a `-scaled.webp` file

## Steps to reproduce

1. Enable webp-uploads
2. Upload and insert an image, select full size in the image properties sidebar
3. view the post and check the image source

#### Expected:
* All image references are to `.webp` files

#### Actual 
* some references are to a `.jpg` file.

## Screenshots

image
image
image

### PR DESCRIPTION
**Pull request by mitogh**
## Summary

Fixes #174

This PR requires:

- #152 
- #194 

## Relevant technical choices

This PR updates the changes introduced by #152 and #194 in order to replace the `full` size image if present in the new format, (in this case WebP) making sure all images served to the client are in the same format when a new image is uploaded into WordPress. 

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

**Review by adamsilverstein — APPROVED** [review]
Excellent!

File: modules/images/webp-uploads/load.php [hunk 1]
```diff
@@ -529,17 +529,18 @@ function webp_uploads_img_tag_update_mime_type( $image, $context, $attachment_id
 
 	$basename = wp_basename( $metadata['file'] );
```
Comment (felixarntz) [inline modules/images/webp-uploads/load.php:545]: I'm realizing now that the `isset` check below actually needs to be around this, otherwise this code may raise a PHP notice if `file` is not set.

It's not a problem of this PR but was already introduced in the previous implementation, I just discovered it now.
```suggestion
	$basename = isset( $metadata['file'] ) ? wp_basename( $metadata['file'] ) : null;
```

File: modules/images/webp-uploads/load.php [hunk 2]
```diff
@@ -529,17 +529,18 @@ function webp_uploads_img_tag_update_mime_type( $image, $context, $attachment_id
...
 	foreach ( $urls as $url ) {
-		if ( isset( $metadata['file'] ) && strpos( $url, $basename ) !== false ) {
-			// TODO: we don't have a replacement for full image yet, issue. See: https://github.com/WordPress/performance/issues/174.
-			continue;
+		$src_filename = wp_basename( $url );
+
+		// Replace the full size image if present.
+		if ( isset( $metadata['file'], $metadata['sources'][ $target_mime ]['file'] ) && strpos( $url, $basename ) !== false ) {
```
Comment (felixarntz) [inline modules/images/webp-uploads/load.php]: Based on the above comment:
```suggestion
		if ( isset( $basename, $metadata['sources'][ $target_mime ]['file'] ) && strpos( $url, $basename ) !== false ) {
```

File: modules/images/webp-uploads/load.php [hunk 3]
```diff
@@ -529,17 +529,18 @@ function webp_uploads_img_tag_update_mime_type( $image, $context, $attachment_id
...
+			$image = str_replace( $src_filename, $metadata['sources'][ $target_mime ]['file'], $image );
```
Comment (felixarntz) [inline modules/images/webp-uploads/load.php:551]: I think this is missing a `continue` statement? If we replaced the full image, we already took care of this URL, so we should skip the rest of this code block to proceed with the next URL.
```suggestion
			$image = str_replace( $src_filename, $metadata['sources'][ $target_mime ]['file'], $image );
			continue;
```

Also, please review the related line 565 below (I can't comment there since it wasn't changed here): I believe we should put a `break;` right after the image replacement, otherwise we'll always run through all sizes even if we already made a successful replacement, which would be pointless. This is also something which we should have caught before, but better now than never :)

**Review by felixarntz — COMMENTED** [review]
@mitogh The new code overall looks solid, I found a few small issues that mostly relate to the already existing code, but we had missed them before.

File: modules/images/webp-uploads/load.php (hunk 1 above)
Comment (mitogh) [reply modules/images/webp-uploads/load.php:545]: Actually, there's a conditional at the top of this function: 

https://github.com/WordPress/performance/blob/76f9392cb7dad591be273cc541ae90137297baf4/modules/images/webp-uploads/load.php#L510

This would prevent the execution of the code if the key is not present.

File: modules/images/webp-uploads/load.php (hunk 2 above)
Comment (mitogh) [reply modules/images/webp-uploads/load.php]: Same as above as well.

File: modules/images/webp-uploads/load.php (hunk 3 above)
Comment (mitogh) [reply modules/images/webp-uploads/load.php:551]: Good catch :+1:

File: modules/images/webp-uploads/load.php (hunk 1 above)
Comment (felixarntz) [reply modules/images/webp-uploads/load.php:545]: Ah right, in that case the code below still needs to be updated though, see other comment.

File: modules/images/webp-uploads/load.php (hunk 2 above)
Comment (felixarntz) [reply modules/images/webp-uploads/load.php]: Per your comment in https://github.com/WordPress/performance/pull/195#discussion_r822179813 this is already checked before though, so the check here should be removed entirely as it's redundant.
```suggestion
		if ( isset( $metadata['sources'][ $target_mime ]['file'] ) && strpos( $url, $basename ) !== false ) {
```

File: modules/images/webp-uploads/load.php (hunk 3 above)
Comment (felixarntz) [reply modules/images/webp-uploads/load.php:551]: Note the second part of my comment as well. Your change https://github.com/WordPress/performance/pull/195/commits/7e1b5298b22f784feabde43b66e8191bafa5d6a1 adds the `continue` here, but not the `break` further down in the code.

Comment (mitogh) [reply modules/images/webp-uploads/load.php:551]: Right, let me update that one.

**Review by felixarntz — APPROVED** [review]
LGTM!

Let's wait with merging this though until #194 is ready, since technically the implementation here depends on how we implement #194.

**Comment by felixarntz** [comment]
Ah nevermind the above, I see you've created this against your branch for #194. I think for the future it would be better to create both PRs based on `trunk`, since if we merge this now, it would be harder to review #194 as it would include the changes from here which were already approved.

So I'd still say it's better to wait until #194 has been approved before we merge this.

**Comment by mitogh** [comment]
Thanks, mostly I've created this based on #194 just to have smaller diffs I agree this should is currently being blocked by #194 but having everything based on `trunk` will create merge conflicts after approval which usually triggers another review, so when having this approved and PR against #194 allows for simpler flow, however, I do see the problem specifically around dependencies between each PR.
