### PR TITLE
Disambiguate XPaths for children of BODY with `id`, `class`, or `role` attributes

### LINKED ISSUE #1787: XPaths for elements in URL Metrics can omit index for children of BODY to avoid needing to vary URL Metrics by whether a user is logged-in
Discussed initially at https://github.com/WordPress/performance/pull/1759#discussion_r1896188052

URL Metrics currently are varied by whether or not a user is logged-in. This is all of the XPaths used on the page differ based on whether or not the admin bar is present, since the element index is included with each element reference. For example, the following is the XPath for the first `IMG` in post content when logged-out vs logged-in:

```diff
- /*[1][self::HTML]/*[2][self::BODY]/*[1][self::DIV]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::DIV]/*[1][self::ARTICLE]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::FIGURE]/*[1][self::PICTURE]/*[2][self::IMG]
+ /*[1][self::HTML]/*[2][self::BODY]/*[3][self::DIV]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::DIV]/*[1][self::ARTICLE]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::FIGURE]/*[1][self::PICTURE]/*[2][self::IMG]
```

The difference is that when logged-in, two new elements appear at the beginning of the `BODY`:

1. A `SCRIPT` coming from `wp_customize_support_script()` (for admin users).
2. A `DIV#wpadminbar` for the admin bar.

These result in the page wrapper `DIV`'s XPath going `*[1][self::DIV]` to `*[3][self::DIV]`.

The purpose of the element index in the XPath is to differentiate one element from another. If there are 3 `IMG` tags appearing next to each other in a post, and only the first is LCP, then it's important to be able to uniquely reference that `IMG`. Nevertheless, at the root level of a page (when directly under the `BODY`) it is highly unlikely for there to be any such ambiguity. This is because themes almost always wrap the content between `wp_body_open()` and `wp_footer()`. Classic themes typically wrap the content in a `DIV#page` element, whereas Block Themes _always_ wrap the content in a `DIV.wp-site-blocks` element. The only exception in core is that the Twenty Twenty theme which does not have one root wrapper but instead has a `HEADER`, `MAIN`, and `FOOTER` at the root. In this case too there is no possibility for ambiguity since these three are unique.

So I suggest we do the following:

1. Eliminate this logic from `od_get_normalized_query_vars()`:

https://github.com/WordPress/performance/blob/b6e5c5a4c79234229ce061ce275c5b31af4ad7e8/plugins/optimization-detective/storage/data.php#L80-L83

2. Omit the element index from the `HTML`, `BODY`, and children directly under the `BODY`. So the XPaths above would become the following:

```
/HTML/BODY/DIV/*[2][self::DIV]/*[1][self::DIV]/*[1][self::DIV]/*[1][self::ARTICLE]/*[2][self::DIV]/*[1][self::DIV]/*[1][self::FIGURE]/*[1][self::PICTURE]/*[2][self::IMG]
```

3. Eliminate the restriction that Optimization Detective be disabled for admins. This was put in place because additional scripts often get added at `wp_body_open()`  (e.g. the `wp_customize_support_script()`). With the presence/absence of such elements printed at `wp_body_open` (and `wp_footer`) eliminated, we can eliminate this code from `od_can_optimize_response()` which would resolve #1425:

https://github.com/WordPress/performance/blob/b6e5c5a4c79234229ce061ce275c5b31af4ad7e8/plugins/optimization-detective/optimization.php#L121-L126

4. During this transitionary period in which old URL Metrics still contain the old XPaths, we can patch `OD_Element` to convert to this new format so existing optimizations will continue to apply based on old URL Metrics:

```diff
--- a/plugins/optimization-detective/class-od-element.php
+++ b/plugins/optimization-detective/class-od-element.php
@@ -52,6 +52,17 @@ class OD_Element implements ArrayAccess, JsonSerializable {
 	 */
 	public function __construct( array $data, OD_URL_Metric $url_metric ) {
 		$this->data       = $data;
+
+		// Convert old XPath scheme.
+		$xpath = preg_replace(
+			'#^/\*\[1\]\[self::HTML\]/\*\[2\]\[self::BODY\]/\*\[\d+\]\[self::(DIV)\]#',
+			'/HTML/BODY/$1',
+			$this->data['xpath']
+		);
+		if ( is_string( $xpath ) && '' !== $xpath ) {
+			$this->data['xpath'] = $xpath;
+		}
+
 		$this->url_metric = $url_metric;
 	}
```

Then in the next release or two we can eliminate this code since the old URL Metrics should have all been purged by then.

### PR DESCRIPTION
**Pull request by westonruter**
This is a follow-up to #1790 which fixed https://github.com/WordPress/performance/issues/1787. 

It is now possible for a generated XPath may not uniquely identify an element in a page. Consider the following example:

1. A theme uses a `DIV` for header and footer, `<div id="header" role="banner">` and `<div id="footer" role="contentinfo">`, which are direct children of the `BODY`.
2. There is an element of the same tag name in the exact same relative position in both of these `DIV`:

```html
<html>
  <body>
    <div id="header" role="banner">
      <img src="header-image.jpg">
    </div>
    <div id="footer" role="contentinfo">
      <img src="footer-logo.png">
    </div>
  </body>
</html>
```

In this case, both of the `IMG` tags here will have the same XPath: `/HTML/BODY/DIV/*[1][self::IMG]`.

I did a [search](https://wpdirectory.net/search/01JHGCESJ5XTBJFRJW7ZMYNJ28) for `<div[^>]*role=["']?banner` in WPDirectory and the only example I could find with a header and footer being direct children of `BODY` is the [Prose theme](https://wordpress.org/themes/prose/) (2,000 active installs and not updated in 12 years): https://themes.trac.wordpress.org/browser/prose/1.1/header.php

Granted, this search assumes that a theme is using the right ARIA roles. It wouldn't account for someone using `<div id="header">`. 

As noted in https://github.com/WordPress/performance/pull/1790#discussion_r1913708486:

> we could instead look at other ways to disambiguate children of the `BODY`, such as to capture the `id`, `class`, and `role` attributes to include with the XPath for that level alone.

This is experimented on in this PR, by adding the `id`, `class`, and `role` attributes to the XPaths generated for children of the `BODY` element. So in the example above, instead of both elements having the same XPath of `/HTML/BODY/DIV/*[1][self::IMG]` they would then be distinct:

1. `/HTML/BODY/DIV[@id='header'][@role='banner']/*[1][self::IMG]`
2. `/HTML/BODY/DIV[@id='footer'][@role='contentinfo']/*[1][self::IMG]`

The key changes in this PR are found in:

* `plugins/optimization-detective/class-od-html-tag-processor.php`. 
* `plugins/optimization-detective/class-od-element.php`
* `plugins/optimization-detective/optimization.php`
* `plugins/optimization-detective/storage/data.php`

Included in in the changes (94843c05f877f04eba2b38a7743b3ff9ad787c44) is the introduction of a "transitional XPath" format so that both of these XPaths:

* Old format: `/*[1][self::HTML]/*[2][self::BODY]/*[1][self::DIV]/*[1][self::IMG]`
* New format: `/HTML/BODY/DIV[@id=\'page\']/*[1][self::IMG]`

Are converted to `/HTML/BODY/DIV/*[1][self::IMG]` during the optimization process. Note the the new format is what is added to the `data-od-xpath` attributes and it is stored in the `od_url_metrics` custom post type. However, when a tag visitor accesses `$processor->get_xpath()` or `$element->get_xpath()` the XPaths are normalized to this transitional format. This is to prevent all of the URL Metrics currently captured in the wild from immediately becoming invalid. See the [`plugins/image-prioritizer/tests/test-cases/common-lcp-image-with-old-xpath-format`](https://github.com/WordPress/performance/tree/468b6a75ae7ddd4260f51299de7f85e8f90d2fe6/plugins/image-prioritizer/tests/test-cases/common-lcp-image-with-old-xpath-format) test case to show this in action. 

👉🏻 Note that this transitional format omits the disambiguating attribute for the sake of not throwing away existing URL Metrics. I consider the impact of a non-unique XPath conflict to be less than the negative performance implications of stopping all optimizations immediately upon updating until new URL Metrics are collected.

To further accelerate the collection of new URL Metrics with the new format, an XPath version is added to the data used to compute the current URL Metrics ETag (c47a6130551346e61e6aeb4f321f3434b87ed607 & 2922d4c0adab67bc8eb333594290676848b5dc16).

### CODE REVIEW

**Comment by westonruter** [comment]
Oh, I just discovered that the Image block with a lightbox is involved here. With the changes in this PR applied, WordPress outputs a `div.wp-lightbox-overlay.zoom` element [at `wp_footer`](https://github.com/WordPress/gutenberg/blob/aa38b2205f7fcbe18c8f06f48b06ba0dcc183b08/packages/block-library/src/image/index.php#L245C2-L245C71) via [`block_core_image_print_lightbox_overlay()`](https://github.com/WordPress/gutenberg/blob/aa38b2205f7fcbe18c8f06f48b06ba0dcc183b08/packages/block-library/src/image/index.php#L250-L308):

```html
<div
        class="wp-lightbox-overlay zoom"
        data-wp-interactive="core/image"
        data-wp-context='{}'
        data-wp-bind--role="state.roleAttribute"
        data-wp-bind--aria-label="state.currentImage.ariaLabel"
        data-wp-bind--aria-modal="state.ariaModal"
        data-wp-class--active="state.overlayEnabled"
        data-wp-class--show-closing-animation="state.showClosingAnimation"
        data-wp-watch="callbacks.setOverlayFocus"
        data-wp-on--keydown="actions.handleKeydown"
        data-wp-on-async--touchstart="actions.handleTouchStart"
        data-wp-on--touchmove="actions.handleTouchMove"
        data-wp-on-async--touchend="actions.handleTouchEnd"
        data-wp-on-async--click="actions.hideLightbox"
        data-wp-on-async-window--resize="callbacks.setOverlayStyles"
        data-wp-on-async-window--scroll="actions.handleScroll"
        tabindex="-1"
>
    <button type="button" aria-label="Close" style="fill: var(--wp--preset--color--contrast)" class="close-button">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20" aria-hidden="true" focusable="false"><path d="m13.06 12 6.47-6.47-1.06-1.06L12 10.94 5.53 4.47 4.47 5.53 10.94 12l-6.47 6.47 1.06 1.06L12 13.06l6.47 6.47 1.06-1.06L13.06 12Z"></path></svg>
    </button>
    <div class="lightbox-image-container">
        <figure data-wp-bind--class="state.currentImage.figureClassNames" data-wp-bind--style="state.figureStyles">
            <img class="od-missing-dimensions" data-od-added-class data-od-xpath="/HTML/BODY/DIV[@class=&#039;wp-lightbox-overlay zoom&#039;]/*[2][self::DIV]/*[1][self::FIGURE]/*[1][self::IMG]" data-wp-bind--alt="state.currentImage.alt" data-wp-bind--class="state.currentImage.imgClassNames" data-wp-bind--style="state.imgStyles" data-wp-bind--src="state.currentImage.currentSrc">
        </figure>
    </div>
    <div class="lightbox-image-container">
        <figure data-wp-bind--class="state.currentImage.figureClassNames" data-wp-bind--style="state.figureStyles">
            <img class="od-missing-dimensions" data-od-added-class data-od-xpath="/HTML/BODY/DIV[@class=&#039;wp-lightbox-overlay zoom&#039;]/*[3][self::DIV]/*[1][self::FIGURE]/*[1][self::IMG]" data-wp-bind--alt="state.currentImage.alt" data-wp-bind--class="state.currentImage.imgClassNames" data-wp-bind--style="state.imgStyles" data-wp-bind--src="state.enlargedSrc">
        </figure>
    </div>
    <div class="scrim" style="background-color: var(--wp--preset--color--base)" aria-hidden="true"></div>
    <style data-wp-text="state.overlayStyles"></style>
</div>
```

Note the XPath for the `IMG` in the overlay:

```
/HTML/BODY/DIV[@class='wp-lightbox-overlay zoom']/*[3][self::DIV]/*[1][self::FIGURE]/*[1][self::IMG]
```

Without the disambiguation, this would be:

```
/HTML/BODY/DIV/*[3][self::DIV]/*[1][self::FIGURE]/*[1][self::IMG]
```

This could be confused with an Image block appearing somewhere especially when `DIV` is used to wrap the header, main content, footer, or sidebar.

> [!IMPORTANT]
> If this change is made to add the disambiguation predicates to `/HTML/BODY/DIV` this will result in invalidating all existing XPaths for currently stored URL Metrics. 

To ease this migration, we may want to add an `od_is_xpath_equal( $xpath1, $xpath2 )` helper function which would check to see if a provided XPath contains the old node index up to the children of the `BODY`. If so, the comparison can fall back to stripping out both the node indices as well as any attribute predicates. The logic added to the `OD_Element` constructor to convert the XPath could be moved to this new helper function:

https://github.com/WordPress/performance/blob/6ca5c4bc2004d2e39133753ddc4c4be763c3ed96/plugins/optimization-detective/class-od-element.php#L56-L64

Then anywhere that we compare XPaths we should use this helper function as opposed to using `===`.

**Update:** This is not so straightforward. For example, `\OD_URL_Metric_Group_Collection::is_element_positioned_in_any_initial_viewport()` is provided an XPath as the argument. The XPath is then fetched from a hash lookup of the mappings returned by `\OD_URL_Metric_Group_Collection::get_all_elements_positioned_in_any_initial_viewport()`. 

This is also the case for code that uses `\OD_URL_Metric_Group_Collection::get_xpath_elements_map()` or `\OD_URL_Metric_Group_Collection::get_all_element_max_intersection_ratios()`, and so on.

Up until now, the XPath has been very constrained in its format, so it has been a reliably fixed string for comparisons. Changing the XPath construction has impacts that need to be carefully evaluated.

**Comment by felixarntz** [comment]
@westonruter I'm not sure I fully understand.

> Oh, I just discovered that the Image block with a lightbox is involved here. With the changes in this PR applied, WordPress outputs a `div.wp-lightbox-overlay.zoom` element [at `wp_footer`](https://github.com/WordPress/gutenberg/blob/aa38b2205f7fcbe18c8f06f48b06ba0dcc183b08/packages/block-library/src/image/index.php#L245C2-L245C71) via [`block_core_image_print_lightbox_overlay()`](https://github.com/WordPress/gutenberg/blob/aa38b2205f7fcbe18c8f06f48b06ba0dcc183b08/packages/block-library/src/image/index.php#L250-L308):

Are you saying this is only inserted with this change? Why that? OD shouldn't alter which DOM elements are inserted by any features right?

> Note the XPath for the `IMG` in the overlay:
> 
> ```
> /HTML/BODY/DIV[@class='wp-lightbox-overlay zoom']/*[3][self::DIV]/*[1][self::FIGURE]/*[1][self::IMG]
> ```
> 
> Without the disambiguation, this would be:
> 
> ```
> /HTML/BODY/DIV/*[3][self::DIV]/*[1][self::FIGURE]/*[1][self::IMG]
> ```
> 
> This could be confused with an Image block appearing somewhere especially when `DIV` is used to wrap the header, main content, footer, or sidebar.

So are you saying without this PR merged, there would be a risk of a duplicate? If so, it would be a good indicator that the risk we assessed as small on the other PR isn't actually that small and we should cater for it.

> Important
> 
> If this change is made to add the disambiguation predicates to `/HTML/BODY/DIV` this will result in invalidating all existing XPaths for currently stored URL Metrics.

Why that? Would it invalidate even URL metrics that have an index (how they're currently stored, without the recent `trunk` changes)? As far as I understand, the URL metrics with an index don't have that problem, so I'd argue the disambiguation only applies to the URL metrics without indices on the body children.

**Comment by westonruter** [comment]
> Are you saying this is only inserted with this change? Why that? OD shouldn't alter which DOM elements are inserted by any features right?

No, I'm saying that this was already being added to the page by Gutenberg. I wasn't aware that Gutenberg was outputting lightbox elements at `wp_footer`, so it breaks the premise I had that all content is inside of `DIV.wp-site-blocks` or `DIV#page`.

> So are you saying without this PR merged, there would be a risk of a duplicate? If so, it would be a good indicator that the risk we assessed as small on the other PR isn't actually that small and we should cater for it.

Correct.

> Why that? Would it invalidate even URL metrics that have an index (how they're currently stored, without the recent trunk changes)? As far as I understand, the URL metrics with an index don't have that problem, so I'd argue the disambiguation only applies to the URL metrics without indices on the body children.

What I mean is that URL Metrics currently stored use the node index, for example `/*[1][self::HTML]/*[2][self::BODY]/*[3][self::DIV]/*[2][self::IMG]`. Prior to this PR, with https://github.com/WordPress/performance/pull/1790, such old XPaths were migrated to the new schema via `OD_Element` so this would instead be `/HTML/BODY/DIV/*[2][self::IMG]`. However, if we start introducing element attributes to disambiguate `/HTML/BODY/DIV` then we won't be able to so easily migrate since we won't know what the attributes are on `/HTML/BODY/DIV`. Like, we wouldn't know how to convert `/*[1][self::HTML]/*[2][self::BODY]/*[3][self::DIV]` to `/HTML/BODY/DIV[@id='page']`. That is, unless we capture the attributes of this element as we iterate over the document and then use them _just in time_.

**Comment by felixarntz** [comment]
@westonruter Makes sense. So maybe we need to leave old data intact for now then and only migrate when we have all the context we need (i.e. in a request to the relevant URL). Since #1790 is not in any release yet, at least we don't have to worry about migrating from that. But we probably should fix it before this upcoming release.

This complicates things of course, but given we already found an exception in Core itself, this is probably going to happen more. Any plugin may add some `div` in `wp_footer`, e.g. for modals etc.

**Comment by westonruter** [comment]
> Makes sense. So maybe we need to leave old data intact for now then and only migrate when we have all the context we need (i.e. in a request to the relevant URL). Since #1790 is not in any release yet, at least we don't have to worry about migrating from that. But we probably should fix it before this upcoming release.

@felixarntz Well, I mean, "migration" will happen eventually as URL Metrics turn stale and get purged from the site. It would be ideal if a change to the XPath structure didn't result in this, however. It would be as if someone installed the plugin anew without any data collected.

File: plugins/optimization-detective/class-od-html-tag-processor.php [hunk 1]
```diff
@@ -123,7 +123,7 @@ final class OD_HTML_Tag_Processor extends WP_HTML_Tag_Processor {
 	 * @var string
 	 * @link https://github.com/WordPress/performance/issues/1787
 	 */
-	const XPATH_PATTERN = '^(/([a-zA-Z0-9:_-]+|\*\[\d+\]\[self::[a-zA-Z0-9:_-]+\]))+$';
+	const XPATH_PATTERN = '^(/([a-zA-Z0-9:_-]+|\*\[\d+\]\[self::[a-zA-Z0-9:_-]+\])(\[@(id|role|class)=\'[a-zA-Z0-9_.\s:-]*\'\])?)+$';
```
Comment (westonruter) [inline plugins/optimization-detective/class-od-html-tag-processor.php:128]: - [x] The phpdoc for this constant needs to be updated to reflect that while the node index is omitted from children of the `BODY`, a disambiguating attribute predicate is now used instead.

File: plugins/optimization-detective/class-od-html-tag-processor.php [hunk 2]
```diff
@@ -317,13 +327,40 @@ public function next_token(): bool {
...
 			}
 
 			$level                   = count( $this->open_stack_tags );
 			$this->open_stack_tags[] = $tag_name;
 
+			/*
+			 * Capture the most stable attribute which can be used to disambiguate an XPath expression when the node index is not appropriate.
+			 * This is used specifically for children of the BODY. The `id` and `role` attributes are most stable (cf. <https://g.co/gemini/share/032edd9063c1>),
+			 * although all Block Themes utilize the 'wp-site-blocks' class name in the root `DIV`.
+			 * TODO: Consider only doing this if $this->open_stack_tags[-2] === 'BODY' and $level === 2 (e.g. we're at a child of /HTML/BODY) since this is the only place we need this.
```
Comment (westonruter) [inline plugins/optimization-detective/class-od-html-tag-processor.php]: - [x] Add condition to avoid needlessly computing `$attributes` when they will not be used.

**Comment by westonruter** [comment]
@felixarntz Finally ready for review. I had to ruminate on this one a while, in particular the "transitional XPath format" aspect to prevent old URL Metrics from becoming invalid. I've updated the description to describe the changes.

File: plugins/optimization-detective/class-od-html-tag-processor.php [hunk 3]
```diff
@@ -102,29 +102,29 @@ final class OD_HTML_Tag_Processor extends WP_HTML_Tag_Processor {
...
 	 * at `wp_body_open()` without impacting the computed XPaths for subsequent tags. Omitting the node index at this
-	 * level, however, does incur a slight risk of duplicate XPaths being computed. For example, if a theme has a
+	 * level, however, does introduce the risk of duplicate XPaths being computed. For example, if a theme has a
 	 * `<div id="header" role="banner">` and a `<div id="footer" role="contentinfo">` which are both direct descendants
 	 * of `BODY`, then it is possible for an XPath like `/HTML/BODY/DIV/*[1][self::IMG]` to be duplicated if both of
-	 * these `DIV` elements has an `IMG` as the first child. The conflict could arise for any tags of the same name in
-	 * the same relative position, which does not seem likely. Additionally, as noted above, themes almost always wrap
-	 * the page content in an overall `DIV` or else they use semantic HTML tags like `HEADER` and `FOOTER`, so the risk
-	 * is low.
+	 * these `DIV` elements has an `IMG` as the first child. This is also an issue in sites using the Image block
```
Comment (felixarntz) [inline plugins/optimization-detective/class-od-html-tag-processor.php]:
```suggestion
	 * these `DIV` elements have an `IMG` as the first child. This is also an issue in sites using the Image block
```

File: plugins/optimization-detective/class-od-html-tag-processor.php [hunk 4]
```diff
@@ -102,29 +102,29 @@ final class OD_HTML_Tag_Processor extends WP_HTML_Tag_Processor {
...
+	 * because it outputs a `DIV.wp-lightbox-overlay.zoom` in `wp_footer`, resulting in there being a real possibility
+	 * for XPaths to not be unique in the page. Therefore, en lieu of node index being added to children of `BODY`,
```
Comment (felixarntz) [inline plugins/optimization-detective/class-od-html-tag-processor.php]: The image lightbox is a very specific example, but I would include a more general mention of any additional `divs` inserted via `wp_footer` for instance (which are often for modals, like image lightbox is an example for).

File: plugins/optimization-detective/class-od-html-tag-processor.php [hunk 5]
```diff
@@ -318,13 +343,21 @@ public function next_token(): bool {
...
 
 			$level                   = count( $this->open_stack_tags );
 			$this->open_stack_tags[] = $tag_name;
 
+			// For children of the BODY, capture disambiguating comments. See the get_xpath() method for where this data is used.
+			$attributes = array();
+			if ( isset( $this->open_stack_tags[1] ) && 'BODY' === $this->open_stack_tags[1] && 2 === $level ) {
+				$attributes = $this->get_disambiguating_attributes();
+			}
+			$this->open_stack_attributes[] = $attributes;
```
Comment (felixarntz) [inline plugins/optimization-detective/class-od-html-tag-processor.php:362]: Since this is not really aligned with what the `$open_stack_tags` property does (as this one only acts for the specific case of a `body` child element), maybe we should use another name? Could be something very specific like `body_child_element_attributes`.

File: plugins/optimization-detective/class-od-html-tag-processor.php [hunk 6]
```diff
@@ -348,6 +381,7 @@ public function next_token(): bool {
 			}
 
 			$popped_tag_name = array_pop( $this->open_stack_tags );
+			array_pop( $this->open_stack_attributes );
```
Comment (felixarntz) [inline plugins/optimization-detective/class-od-html-tag-processor.php:387]: Does this not need to be conditional (e.g. based on the parent tag and level)? Are we certain this wouldn't remove the attributes when it shouldn't?

File: plugins/optimization-detective/class-od-element.php [hunk 7]
```diff
@@ -129,11 +130,58 @@ public function is_lcp_candidate(): bool {
...
+				 * Note that the new XPath format for elements in the HEAD does not need to be converted to the
+				 * transitional format since disambiguating attributes are not used in the HEAD.
+				 *
+				 * Example:
+				 *   /HTML/BODY/DIV[@id='page']/*[1][self::IMG]
+				 *   =>
+				 *   /HTML/BODY/DIV/*[1][self::IMG]
+				 */
+				'#^(/HTML/BODY/\w+)\[@[^\]]+?]#' => '$1',
+			);
```
Comment (felixarntz) [inline plugins/optimization-detective/class-od-element.php:176]: I don't fully understand how this transitional xpath helps. Is it so that all the old xpaths and new xpaths are using the same format temporarily (i.e. without disambiguation of body child `div`s)? Wouldn't that be a risk (because of the lack of disambiguation) and because of that it would be better to for now still only record URL metrics for logged-out users? If I understand correctly, I would think we should only enable the URL metric recording for logged-out users once the transition is completed, otherwise we would have the risk that we (per this PR) deemed to risky to leave unaddressed.

We'll eventually remove this so that the new xpaths format should be used exclusively, right? Maybe worth adding a `TODO` here too, as I assume this means all this logic and the `$transitional_xpath` property can be removed again in the near future.

File: plugins/optimization-detective/class-od-html-tag-processor.php [hunk 8]
```diff
@@ -565,19 +636,51 @@ private function is_foreign_element(): bool {
...
+	 * Note that the first three levels lack any node index whereas the third level includes a disambiguating
+	 * attribute predicate (e.g. `/HTML/BODY/DIV[@id="page"]`) for the reasons explained in {@see self::XPATH_PATTERN}.
 	 *
 	 * @since 0.4.0
 	 *
+	 * @param bool $transitional_format Whether to use the transitional XPath format. Default true.
 	 * @return string XPath.
 	 */
-	public function get_xpath(): string {
+	public function get_xpath( bool $transitional_format = true ): string {
```
Comment (felixarntz) [inline plugins/optimization-detective/class-od-html-tag-processor.php]: I am wary of introducing a boolean parameter here, as it is of temporary nature - plus it's a code smell to have a parameter to change what a method does entirely, it should instead be a new method then.

A better path I think would be to introduce a separate method that we could later deprecate again - that gets in the way much less than having to deprecate a parameter of a method that will still be used long-term.

Since the default expectation for the transitional period here is to return the transitional format, I think we should replace the logic of this method entirely with what you have in the `if ( $transitional_format )` clause, and move the original logic to some new method like `get_xpath_to_store()` or something. The one place in the code that currently calls this with parameter `false` could then call the new temporary method, and once we are done with the transition, we could deprecate this method and move its logic back into this method, with fewer annoying side effects.

**Review by felixarntz — COMMENTED** [review]
@westonruter I think this looks pretty good, though I have a few important questions on the direction in regards to the transition. Most importantly, it seems to me that we need to wait for the transition to be completed until we actually enabled URL metrics for logged-out users (which was one of the main reasons to change the xpath format in the first place).

File: plugins/optimization-detective/class-od-element.php (hunk 7 above)
Comment (westonruter) [reply plugins/optimization-detective/class-od-element.php:176]: > Is it so that all the old xpaths and new xpaths are using the same format temporarily (i.e. without disambiguation of body child `div`s)?

Yes, that's right.

> Wouldn't that be a risk (because of the lack of disambiguation) and because of that it would be better to for now still only record URL metrics for logged-out users?

I don't think whether the user is logged-in matters so much because the presence of the Admin Bar still won't impact the XPaths since at that level the transitional XPath is `/HTML/BODY/DIV`. 

> If I understand correctly, I would think we should only enable the URL metric recording for logged-out users once the transition is completed, otherwise we would have the risk that we (per this PR) deemed to risky to leave unaddressed.

Once the transition is complete, all stored URL Metrics will have the disambiguating attribute predicate present on the XPath so at this point we will be even more safe to share XPaths between logged-in and logged-out users. Elements inside of `DIV#page` will have XPaths that start with `/HTML/BODY/DIV[@id='page']`.

> We'll eventually remove this so that the new xpaths format should be used exclusively, right? Maybe worth adding a `TODO` here too, as I assume this means all this logic and the `$transitional_xpath` property can be removed again in the near future.

That's right. The new format will be used exclusively, probably in the next release. And yes, all of the `$transitional_xpath` will be removed at that time as well. Basically https://github.com/WordPress/performance/commit/94843c05f877f04eba2b38a7743b3ff9ad787c44 will be reverted.

File: plugins/optimization-detective/class-od-html-tag-processor.php (hunk 8 above)
Comment (westonruter) [reply plugins/optimization-detective/class-od-html-tag-processor.php]: OK, sounds good.

File: plugins/optimization-detective/class-od-html-tag-processor.php (hunk 6 above)
Comment (westonruter) [reply plugins/optimization-detective/class-od-html-tag-processor.php:387]: It doesn't need to be conditional, no, since I'm pushing an empty array onto the stack when not at `BODY > *`:

https://github.com/WordPress/performance/blob/468b6a75ae7ddd4260f51299de7f85e8f90d2fe6/plugins/optimization-detective/class-od-html-tag-processor.php#L354-L359

I decided to do this this way for two reasons:

1. It's consistent with how the `open_stack_tags` variable is manipulated:

https://github.com/WordPress/performance/blob/468b6a75ae7ddd4260f51299de7f85e8f90d2fe6/plugins/optimization-detective/class-od-html-tag-processor.php#L318-L319

https://github.com/WordPress/performance/blob/468b6a75ae7ddd4260f51299de7f85e8f90d2fe6/plugins/optimization-detective/class-od-html-tag-processor.php#L345-L346

https://github.com/WordPress/performance/blob/468b6a75ae7ddd4260f51299de7f85e8f90d2fe6/plugins/optimization-detective/class-od-html-tag-processor.php#L333-L334

https://github.com/WordPress/performance/blob/468b6a75ae7ddd4260f51299de7f85e8f90d2fe6/plugins/optimization-detective/class-od-html-tag-processor.php#L502-L503

https://github.com/WordPress/performance/blob/468b6a75ae7ddd4260f51299de7f85e8f90d2fe6/plugins/optimization-detective/class-od-html-tag-processor.php#L521-L523

https://github.com/WordPress/performance/blob/468b6a75ae7ddd4260f51299de7f85e8f90d2fe6/plugins/optimization-detective/class-od-html-tag-processor.php#L563-L565

If we only captured only at the 3rd level (`BODY > *`) then additional logic would be needed in all these places to figure out if we're at that level.

2. We may want to capture these attributes at additional levels in the future for further disambiguation.

File: plugins/optimization-detective/class-od-html-tag-processor.php (hunk 5 above)
Comment (westonruter) [reply plugins/optimization-detective/class-od-html-tag-processor.php:362]: See https://github.com/WordPress/performance/pull/1797#discussion_r1926048532

File: plugins/optimization-detective/class-od-html-tag-processor.php (hunk 3 above)
Comment (westonruter) [reply plugins/optimization-detective/class-od-html-tag-processor.php]: See c259b5933b30d0ed07818c18742f592bc1cac7ac

File: plugins/optimization-detective/class-od-html-tag-processor.php (hunk 4 above)
Comment (westonruter) [reply plugins/optimization-detective/class-od-html-tag-processor.php]: See c259b5933b30d0ed07818c18742f592bc1cac7ac

File: plugins/optimization-detective/class-od-element.php (hunk 7 above)
Comment (westonruter) [reply plugins/optimization-detective/class-od-element.php:176]: Added todos in 8c526e5d3

File: plugins/optimization-detective/class-od-html-tag-processor.php (hunk 8 above)
Comment (westonruter) [reply plugins/optimization-detective/class-od-html-tag-processor.php]: Done in 8c526e5d3

**Comment by westonruter** [comment]
> Most importantly, it seems to me that we need to wait for the transition to be completed until we actually enabled URL metrics for logged-out users (which was one of the main reasons to change the xpath format in the first place).

The transitional logic here basically maintains the behavior to what was introduced in https://github.com/WordPress/performance/pull/1790, where there is no index and no disambiguating attribute predicates added to children of `BODY`. However, the key change is that it starts collecting URL Metrics with the _new_ format so that once the transitional period is over we can go live with the XPaths with the disambiguating predicates. During this transitional period, there is a chance for multiple XPaths to be equal in a given document as outlined in the problem statement of this PR. However, I deem this to not be extremely likely to occur since the two element trees would have to be identical. It seems worthwhile to risk a possible conflict while not invalidating all existing URL Metrics which have the old XPath format.

Related:

* https://github.com/WordPress/performance/pull/1816

File: plugins/optimization-detective/storage/data.php [hunk 9]
```diff
@@ -200,6 +200,7 @@ function od_get_current_url_metrics_etag( OD_Tag_Visitor_Registry $tag_visitor_r
 	}
 
 	$data = array(
+		'xpath_version'    => 2, // Bump whenever a major change to the XPath format occurs so that new URL Metrics are proactively gathered.
```
Comment (felixarntz) [inline plugins/optimization-detective/storage/data.php:203]: Just curious: Will this need another bump once we switch from the transition format to the new format? Or is this only relevant for the new format, which now already is being stored?

**Review by felixarntz — APPROVED** [review]
@westonruter LGTM!

I just noticed if we follow WordPress version convention, the upcoming OD plugin release will be 1.0.0. Is that the plan? Given the changed xpath format and the improved stability of the plugin, I feel like it's great timing actually.

File: plugins/optimization-detective/storage/data.php (hunk 9 above)
Comment (felixarntz) [reply plugins/optimization-detective/storage/data.php:203]: Should we maybe set it to `1`, just because it better aligns with the current/upcoming version? And because it wasn't there before its mere presence should trigger an invalidation of existing metrics anyway, correct?

Comment (westonruter) [reply plugins/optimization-detective/storage/data.php:203]: I was thinking this should be considered more like `$wp_db_version` where it is just an incremented integer. Originally I had it set to `OPTIMIZATION_DETECTIVE_VERSION` but there's no need for the ETag to change with each version unless there's something fundamentally changed about the format, like with the change here to the XPath structure.

Comment (westonruter) [reply plugins/optimization-detective/storage/data.php:203]: > Will this need another bump once we switch from the transition format to the new format? Or is this only relevant for the new format, which now already is being stored?

We won't need to bump it after the transitional period because at that point the URL Metrics will all have the new XPaths stored, so then it's just a matter of actually using them as opposed to the transitional form (🐵).

**Comment by westonruter** [comment]
> I just noticed if we follow WordPress version convention, the upcoming OD plugin release will be 1.0.0. Is that the plan? Given the changed xpath format and the improved stability of the plugin, I feel like it's great timing actually.

We could, but I was thinking to hold off one more release perhaps, until WordCamp Asia, to make the 1.0.0 version. So I think the next version we can have be `0.10.0` as a sort of RC.

File: plugins/optimization-detective/storage/data.php (hunk 9 above)
Comment (westonruter) [reply plugins/optimization-detective/storage/data.php:203]: > Should we maybe set it to `1`, just because it better aligns with the current/upcoming version? And because it wasn't there before its mere presence should trigger an invalidation of existing metrics anyway, correct?

Right, it could be anything since anything would be different than nothing. But I thought `2` made sense since it's the second version after the initial format we had been using.

Comment (felixarntz) [reply plugins/optimization-detective/storage/data.php:203]: I would slightly prefer `1` (you could argue the previous one was `0`, just like the release versions have been `0.*`). But either works for me.

**Comment by felixarntz** [comment]
> > I just noticed if we follow WordPress version convention, the upcoming OD plugin release will be 1.0.0. Is that the plan? Given the changed xpath format and the improved stability of the plugin, I feel like it's great timing actually.
> 
> We could, but I was thinking to hold off one more release perhaps, until WordCamp Asia, to make the 1.0.0 version. So I think the next version we can have be `0.10.0` as a sort of RC.

We're obviously not tied to the regular WordPress versioning approach, but we have been doing it that way for all the performance plugins so far (after `{x}.9.0` comes `{x+1}.0.0`). I think especially because of where the Optimization Detective plugin is at this point, I would say it would be a great point to use `1.0.0`. I don't think we should tie it to a specific event.

**Comment by westonruter** [comment]
> We're obviously not tied to the regular WordPress versioning approach, but we have been doing it that way for all the performance plugins so far (after `{x}.9.0` comes `{x+1}.0.0`). I think especially because of where the Optimization Detective plugin is at this point, I would say it would be a great point to use `1.0.0`. 

Not quite, as for Modern Image Formats we went from 1.1.1 to 2.0.0 when it was no longer strictly about WebP. I don't feel strongly, however.

> I don't think we should tie it to a specific event.

Not specifically because of WordCamp Asia, but more because this is the point at which the documentation and code I'd consider stable as it getting increased exposure.

**Comment by felixarntz** [comment]
> Not quite, as for Modern Image Formats we went from 1.1.1 to 2.0.0 when it was no longer strictly about WebP. I don't feel strongly, however.

That's true, though I meant specifically the other part of the versioning approach, to not have a minor version segment greater than a single digit.

If the plugin wasn't in a 1.0.0 worthy state, I would definitely reconsider this here. But I feel like it is a good time to make it 1.0.0.

Alternatively, why don't we make it `1.0.0-beta.1`? Of course WordPress.org would still ship this to all users on previous versions, but in this particular scenario I think that is totally fine, because anything pre-1.0.0 can be considered a pre release anyway, just like any `-beta` release.

> Not specifically because of WordCamp Asia, but more because this is the point at which the documentation and code I'd consider stable as it getting increased exposure.

From that perspective, it may be a better approach to release another beta or an RC for that event, as increased exposure would uncover potential problems that would ideally be addressed before a 1.0.0 stable. I think having a 1.0.0 beta or RC release ready for such a major event is still an excellent milestone and invites users to give feedback.

**Comment by westonruter** [comment]
Doing a 1.0.0 beta release makes sense to me. We'd just have to make sure our tooling supports such version identifiers.

**Comment by felixarntz** [comment]
@westonruter Looks like in some places in our tooling we cater for version suffixes like `-beta`, while in others we don't: https://github.com/search?q=repo%3AWordPress%2Fperformance+%5Cd%2B%5C.%5Cd%2B%5C.%5Cd%2B&type=code

I think it should be rather trivial to modify the relevant regexes that don't support the suffix yet. Then we could do a `1.0.0-beta` for Optimization Detective next week.
