### PR TITLE
Fix incorrect image size selection in `PICTURE` element

### LINKED ISSUE #1882: Modern Image Format return wrong size in picture element
Hi, in picture element I have wrong AVIF image with resolution 768x768px. 

How to reproduce

1. Add to php
```php
    add_image_size( 'square', 768, 768, true );
    add_filter( 'pre_option_medium_size_h', function() { return '768'; } );
    add_filter( 'pre_option_medium_size_w', function() { return '512'; } );
    add_filter( 'pre_option_medium_crop', function() { return array( 'center', 'center' ); } );
```
2. Upload image to Media Library
3. in template call `wp_get_attachment_image( $post_thumbnail_id, 'medium', false );`
4. give me WRONG size in SOURCE element =>
```html
    <picture>
        <source data-sizes="auto, (max-width: 768px) 100vw, 768px" data-srcset="gku6acxnr_a-768x768-jpg.avif 768w, gku6acxnr_a-1152x768-jpg.avif 1152w, gku6acxnr_a-1536x1024-jpg.avif 1536w, gku6acxnr_a-150x100-jpg.avif 150w, gku6acxnr_a-jpg.avif 1600w" type="image/avif"  >
        <img data-sizes="auto, (max-width: 768px) 100vw, 768px" data-src="gku6acxnr_a-768x512.jpg" data-srcset="gku6acxnr_a-768x512.jpg 768w, gku6acxnr_a-1152x768.jpg 1152w, gku6acxnr_a-1536x1024.jpg 1536w, gku6acxnr_a-150x100.jpg 150w, gku6acxnr_a.jpg 1600w" width="768" height="512" src="//:0" class="lazyload" alt="gku6acxnr a" decoding="async" loading="lazy"   data-has-transparency="false" data-dominant-color="9b6e44" style="--dominant-color: #9b6e44;" />
    </picture>
````

5. In function `webp_uploads_wrap_image_in_picture()` I have array size_array =>

```
    print_r( $size_array );
    [image/jpeg] => Array
        (
            [w] => Array
                (
                    [1600] => Array
                        (
                            [file] => gku6acxnr_a.jpg
                            [filesize] => 346046
                        )

                    [768] => Array
                        (
                            [file] => gku6acxnr_a-768x768.jpg
                            [filesize] => 90049
                        )

                    [150] => Array
                        (
                            [file] => gku6acxnr_a-150x100.jpg
                            [filesize] => 6883
                        )

                    [1152] => Array
                        (
                            [file] => gku6acxnr_a-1152x768.jpg
                            [filesize] => 126075
                        )

                    [1536] => Array
                        (
                            [file] => gku6acxnr_a-1536x1024.jpg
                            [filesize] => 216081
                        )

                    [384] => Array
                        (
                            [file] => gku6acxnr_a-384x384.jpg
                            [filesize] => 29420
                        )

                )

            [h] => Array
                (
                    [1067] => Array
                        (
                            [file] => gku6acxnr_a.jpg
                            [filesize] => 346046
                        )

                    [512] => Array
                        (
                            [file] => gku6acxnr_a-768x512.jpg
                            [filesize] => 62979
                        )

                    [150] => Array
                        (
                            [file] => gku6acxnr_a-150x150.jpg
                            [filesize] => 8625
                        )

                    [768] => Array
                        (
                            [file] => gku6acxnr_a-768x768.jpg
                            [filesize] => 90049
                        )

                    [1024] => Array
                        (
                            [file] => gku6acxnr_a-1536x1024.jpg
                            [filesize] => 216081
                        )

                    [384] => Array
                        (
                            [file] => gku6acxnr_a-384x384.jpg
                            [filesize] => 29420
                        )

                    [100] => Array
                        (
                            [file] => gku6acxnr_a-150x100.jpg
                            [filesize] => 6883
                        )

                )

        )

    [image/avif] => Array
        (
            [w] => Array
                (
                    [1600] => Array
                        (
                            [file] => gku6acxnr_a-jpg.avif
                            [filesize] => 262685
                        )

                    [768] => Array
                        (
                            [file] => gku6acxnr_a-768x768-jpg.avif
                            [filesize] => 75746
                        )

                    [150] => Array
                        (
                            [file] => gku6acxnr_a-150x100-jpg.avif
                            [filesize] => 4278
                        )

                    [1152] => Array
                        (
                            [file] => gku6acxnr_a-1152x768-jpg.avif
                            [filesize] => 104232
                        )

                    [1536] => Array
                        (
                            [file] => gku6acxnr_a-1536x1024-jpg.avif
                            [filesize] => 184244
                        )

                    [384] => Array
                        (
                            [file] => gku6acxnr_a-384x384-jpg.avif
                            [filesize] => 24190
                        )

                )

            [h] => Array
                (
                    [1067] => Array
                        (
                            [file] => gku6acxnr_a-jpg.avif
                            [filesize] => 262685
                        )

                    [512] => Array
                        (
                            [file] => gku6acxnr_a-768x512-jpg.avif
                            [filesize] => 49628
                        )

                    [150] => Array
                        (
                            [file] => gku6acxnr_a-150x150-jpg.avif
                            [filesize] => 6105
                        )

                    [768] => Array
                        (
                            [file] => gku6acxnr_a-768x768-jpg.avif
                            [filesize] => 75746
                        )

                    [1024] => Array
                        (
                            [file] => gku6acxnr_a-1536x1024-jpg.avif
                            [filesize] => 184244
                        )

                    [384] => Array
                        (
                            [file] => gku6acxnr_a-384x384-jpg.avif
                            [filesize] => 24190
                        )

                    [100] => Array
                        (
                            [file] => gku6acxnr_a-150x100-jpg.avif
                            [filesize] => 4278
                        )

                )
        )
```

### PR DESCRIPTION
**Pull request by b1ink0**
## Summary

Fixes #1882 

## Relevant technical choices

The `srcset` is generated differently for the `SOURCE` and `IMG` tags when there are two image sizes with the same width but different heights. This discrepancy occurs because the [`wp_image_matches_ratio`](https://github.com/WordPress/wordpress-develop/blob/d9846f86b1fdee4825928432db5ab3b868903fb1/src/wp-includes/media.php#L726) check is applied during [`wp_calculate_image_srcset`](https://github.com/WordPress/wordpress-develop/blob/d9846f86b1fdee4825928432db5ab3b868903fb1/src/wp-includes/media.php#L1323) for generating the `srcset` of the `IMG` tag. However, for the `SOURCE` tag, the `srcset` is generated within the [`webp_uploads_wrap_image_in_picture`](https://github.com/WordPress/performance/blob/8050a1b1721ae92dafb4797e3c2b57426e6ff9b8/plugins/webp-uploads/picture-element.php#L21) function, which then overrides the sources created by the [`wp_get_attachment_image_srcset`](https://github.com/WordPress/wordpress-develop/blob/d9846f86b1fdee4825928432db5ab3b868903fb1/src/wp-includes/media.php#L1287) function using [`wp_calculate_image_srcset`](https://github.com/WordPress/wordpress-develop/blob/d9846f86b1fdee4825928432db5ab3b868903fb1/src/wp-includes/media.php#L1511) filter. The issue was caused by the absence of the [`wp_image_matches_ratio`](https://github.com/WordPress/wordpress-develop/blob/d9846f86b1fdee4825928432db5ab3b868903fb1/src/wp-includes/media.php#L726) check in [`webp_uploads_wrap_image_in_picture`](https://github.com/WordPress/performance/blob/8050a1b1721ae92dafb4797e3c2b57426e6ff9b8/plugins/webp-uploads/picture-element.php#L21), leading to incorrect image size selection.

Below is the code snippet to reproduce the bug.

```php
add_image_size( 'square', 768, 768, true );
add_filter( 'pre_option_medium_large_size_w', function() { return '768'; } );
add_filter( 'pre_option_medium_large_size_h', function() { return '512'; } );
```

### CODE REVIEW

File: plugins/webp-uploads/tests/test-picture-element.php [hunk 1]
```diff
@@ -373,4 +373,27 @@ public function test_picture_source_should_have_full_size_image_in_its_srcset():
 			$this->assertStringContainsString( $image_meta['sources'][ self::$mime_type ]['file'], $picture_processor->get_attribute( 'srcset' ), 'Make sure the IMG srcset should have full size image.' );
 		}
 	}
+
+	/**
+	 * Test handling of case when wp_get_attachment_image_src returns false.
+	 */
+	public function test_wrap_image_in_picture_with_false_image_src(): void {
```
Comment (felixarntz) [inline plugins/webp-uploads/tests/test-picture-element.php:510]: This test is good to have, but it's not actually testing the more important fix that this PR implements. It would be great if you could add a test that verifies that what is reported in #1882 gets fixed by this PR. You could probably use the code snippet you have in the PR description in that test itself.

A great way to do that is test-driven development:
1. Work on the test based on the codebase without this fix. (For example temporarily comment out or revert the changes in `webp_uploads_wrap_image_in_picture()` locally.)
2. Once you implemented the test, it should fail.
3. Re-enable the changes in `webp_uploads_wrap_image_in_picture()`.
4. Now the same test should pass without any changes to it.

This way you verify the bug gets fixed by this PR.

**Review by felixarntz — COMMENTED** [review]
@b1ink0 The production code changes look good to me, but it would be great if you could add a unit test to verify that it fixes the originally reported bug.

File: plugins/webp-uploads/tests/test-picture-element.php (hunk 1 above)
Comment (b1ink0) [reply plugins/webp-uploads/tests/test-picture-element.php:510]: Thanks for the detailed guidance! I will make sure to integrate the step provided for test-driven development into my workflow from now on.

File: plugins/webp-uploads/tests/test-picture-element.php [hunk 2]
```diff
@@ -264,6 +264,115 @@ function ( string $content ): string {
...
+		$source_files = $extract_file_names_from_srcset( $source_srcset );
+		$img_files    = $extract_file_names_from_srcset( $img_srcset );
+
+		$this->assertCount( count( $source_files ), $img_files );
+
+		foreach ( $img_files as $img_index => $img_file ) {
+			// Check the file name starts with the same prefix.
+			// e.g. $img_file = 'leaves-350x200' and $source_files[ $img_index ] = 'leaves-350x350-jpg'.
+			$this->assertStringStartsWith( $img_file, $source_files[ $img_index ] );
+		}
```
Comment (felixarntz) [inline plugins/webp-uploads/tests/test-picture-element.php:361]: I think this could be shortened to use the `assertSameSets()` assertion instead?

File: plugins/webp-uploads/tests/test-picture-element.php [hunk 3]
```diff
@@ -264,6 +264,115 @@ function ( string $content ): string {
...
+
+		wp_delete_attachment( $attachment_id, true );
+
+		if ( $tear_down instanceof Closure ) {
+			$tear_down();
+		}
```
Comment (felixarntz) [inline plugins/webp-uploads/tests/test-picture-element.php]: Having this cleanup logic called here is not reliable, since any assertion failing would result in this code not being reached. Can we instead incorporate this in an actual `tear_down()` method on the class that will always get invoked after each test?

You could store the attachment IDs generated in a class property, so that after each check any new IDs result in their attachment being deleted.

File: plugins/webp-uploads/tests/test-picture-element.php [hunk 4]
```diff
@@ -264,6 +264,115 @@ function ( string $content ): string {
...
+						static function () {
+							return '512';
+						}
+					);
+				},
+				'tear_down' => static function (): void {
+					remove_image_size( 'square' );
+					remove_all_filters( 'pre_option_medium_large_size_w' );
+					remove_all_filters( 'pre_option_medium_large_size_h' );
+				},
```
Comment (felixarntz) [inline plugins/webp-uploads/tests/test-picture-element.php]: Since this is the only usage of the `tear_down` closure, we can probably work without them:
* Filters added in a test are removed automatically after the test, so I don't think we need to clean them up here.
* For the image size, maybe you can handle it in a `tear_down()` method on the class? Alternatively if it makes sense to keep it, we need to move when this `tear_down` closure is invoked in the test (see above comment).

**Review by felixarntz — COMMENTED** [review]
@b1ink0 Thank you for the updates, the test looks great! Just a few minor points of feedback on following some best practices for PHPUnit tests in WordPress.

File: plugins/webp-uploads/tests/test-picture-element.php (hunk 2 above)
Comment (b1ink0) [reply plugins/webp-uploads/tests/test-picture-element.php:361]: We can't use `assertSameSets()` here because we're checking that each image file name is a prefix of the corresponding source file name, not that they are identical.

Comment (felixarntz) [reply plugins/webp-uploads/tests/test-picture-element.php:361]: Good point, I missed that. Thanks, this is good as is then!

File: plugins/webp-uploads/tests/test-picture-element.php [hunk 5]
```diff
@@ -264,6 +296,110 @@ function ( string $content ): string {
...
+						}
+					);
+					add_filter(
+						'pre_option_medium_large_size_h',
+						static function () {
+							return '512';
+						}
+					);
+				},
+				'custom_sizes' => array( 'square' ),
```
Comment (felixarntz) [inline plugins/webp-uploads/tests/test-picture-element.php]: I think we could do without this key, having only `set_up` would be sufficient: You already add the `square` image size in the `set_up` callback. Since the size is otherwise only used to add to `$this->temp_custom_image_sizes`, you could include that in the `set_up` callback instead (change it from `static function ()` to `function ()`).

File: plugins/webp-uploads/tests/test-picture-element.php [hunk 6]
```diff
@@ -264,6 +296,110 @@ function ( string $content ): string {
...
+	/**
+	 * Test that the picture element source tag srcset has the same image sizes as the img tag srcset.
+	 *
+	 * @dataProvider data_provider_test_picture_element_source_tag_srcset_has_same_image_sizes_as_img_tag_srcset
+	 * @covers ::webp_uploads_wrap_image_in_picture
+	 *
+	 * @param Closure|null       $set_up Set up the test.
+	 * @param array<string>|null $custom_sizes Custom image sizes.
+	 */
+	public function test_picture_element_source_tag_srcset_has_same_image_sizes_as_img_tag_srcset( ?Closure $set_up, ?array $custom_sizes ): void {
```
Comment (felixarntz) [inline plugins/webp-uploads/tests/test-picture-element.php]: See my other comment, I think you can remove the `array $custom_sizes` parameter.

**Review by felixarntz — APPROVED** [review]
@b1ink0 This looks great, thank you for the updates!

I have one more feedback, which would be great to address, but I'm already going to approve it as it overall is good.

**Comment by felixarntz** [comment]
Thanks for the updates @b1ink0, looks good!

@westonruter Did you already create a branch for the next release set on Monday, or can this still be merged into `trunk`? This should be included in Monday's releases.

**Comment by westonruter** [comment]
@felixarntz No, I didn't create branch yet. There are still several PRs pending merge.
