### PR TITLE
Enhance object-cache.php drop-in interoperability with other plugins

### LINKED ISSUE #612: object-cache.php conflicts with third party plugins
## Bug Description

As highlighted by [one user in the support forums](https://wordpress.org/support/topic/conflict-on-object-cache-php-2/#post-16306986), there is a conflict between the Performance Lab generated object-cache.php file and the same file generated by third party plugins. 

The **expected behavior** with an additional object-cache.php file generated by another plugin (if the PL plugin is installed first):
1. The PL plugin renames the third party plugins object-cache.php to object-cache-plst-orig.php
2. The PL plugin then loads it's own file, while also loading the object-cache-plst-orig.php file

## Steps to reproduce

1. Install the PL plugin
2. Check that that object-cache.php file exists within the sites wp-content directory
3. Install and active W3 Total Cache 
4. Within the W3 Total cache settings enable Object Caching (_Performance > General > Object Cache > Object Cache > Enable_)
5. After enabling object caching within the W3 Total Cache settings a notice will appear recognising the conflict. You can then choose to allow W3 Total Cache to remove the PL inserted object-cache.php file. If doing so, the PL file is removed. 

The same issue can be found if using LiteSpeed Cache and applying Object Caching (_ListeSpeed Cache > Cache > Object > Object Cache > ON_). For this plugin there is no conflict highlighted, instead the PL file is removed ([recording of experience](https://recordit.co/swOQTIlESb)) 

https://user-images.githubusercontent.com/41326532/208740415-38f42a90-e661-4b43-b8e7-96aa89f62066.mp4

### PR DESCRIPTION
**Pull request by felixarntz**
## Summary

Fixes #612

## Relevant technical choices

* Fixes the one PL-side bug outlined in https://github.com/WordPress/performance/issues/612#issuecomment-1363417637.
* Adds comprehensive test coverage for the change and original logic in `perflab_maybe_set_object_cache_dropin()`, which previously was basically untested. It does so via a new (for now very basic) mock filesystem class.

## Checklist

- [x] PR has either `[Focus]` or `Infrastructure` label.
- [x] PR has a `[Type]` label.
- [x] PR has a milestone or the `no milestone` label.

### CODE REVIEW

File: load.php [hunk 1]
```diff
@@ -300,11 +300,32 @@ function perflab_maybe_set_object_cache_dropin() {
...
+			// If even the backup file already exists, we should not do anything,
+			// except for the case where that file is the same as the main
+			// object-cache.php file. This can happen if another plugin is
+			// aggressively trying to re-add its own object-cache.php file,
+			// ignoring that the Performance Lab object-cache.php file still
+			// loads that other file. This is also outlined in the bug
+			// https://github.com/WordPress/performance/issues/612).
+			// In that case we can simply delete the main file since it is
+			// already backed up.
+			if ( $wp_filesystem->exists( WP_CONTENT_DIR . '/object-cache-plst-orig.php' ) ) {
```
Comment (tillkruss) [inline load.php]: What's the `plst` reference?

Comment (felixarntz) [reply load.php]: Just a shorthand for "Performance Lab Server Timing" to make the file name more "unique" (e.g. in case another plugin would already do something similar using `-orig` suffix).

File: load.php [hunk 2]
```diff
@@ -300,11 +300,32 @@ function perflab_maybe_set_object_cache_dropin() {
...
+				$oc_content      = $wp_filesystem->get_contents( WP_CONTENT_DIR . '/object-cache.php' );
+				$oc_orig_content = $wp_filesystem->get_contents( WP_CONTENT_DIR . '/object-cache-plst-orig.php' );
```
Comment (mukeshpanchal27) [inline load.php]: Similar to this use variable for `WP_CONTENT_DIR . '/object-cache.php'` and `WP_CONTENT_DIR . '/object-cache-plst-orig.php'` and use it.

```
$oc_file = WP_CONTENT_DIR . '/object-cache.php';
$oc_orig_file = WP_CONTENT_DIR . '/object-cache-plst-orig.php';
```

File: tests/load-tests.php [hunk 3]
```diff
@@ -237,23 +237,130 @@ function( $module_settings, $module_dir ) {
...
+		global $wp_filesystem;
 
-		if ( ! $GLOBALS['wp_filesystem']->is_writable( WP_CONTENT_DIR ) ) {
-			$this->markTestSkipped( 'This system does not allow file modifications within WP_CONTENT_DIR.' );
-		}
+		$this->set_up_mock_filesystem();
+
+		// Ensure PL object-cache.php drop-in is not present and constant is not set.
+		$this->assertFalse( $wp_filesystem->exists( WP_CONTENT_DIR . '/object-cache.php' ) );
+		$this->assertFalse( PERFLAB_OBJECT_CACHE_DROPIN_VERSION );
```
Comment (mukeshpanchal27) [inline tests/load-tests.php:247]: Got an error when run unit tests in local system.

`Failed asserting that 1 is false.`

**Review by mukeshpanchal27 — COMMENTED** [review]
Thanks @felixarntz Overall looks solid to me. Left some feedbacks.

File: load.php (hunk 2 above)
Comment (felixarntz) [reply load.php]: @mukeshpanchal27 Good idea! Updated in https://github.com/WordPress/performance/pull/616/commits/6eb9a0eaf42e2a9eb56b759e056df24adb4b8a26

File: tests/load-tests.php (hunk 3 above)
Comment (felixarntz) [reply tests/load-tests.php:247]: @mukeshpanchal27 Is that maybe because your test setup still had the actual `object-cache.php` file present from some older code? Can you try checking that in your test setup, and if so delete the file and rerun?

Comment (jjgrainger) [reply tests/load-tests.php:247]: @mukeshpanchal27 testing this locally myself I did not come across this error, all tests passed.

**Review by jjgrainger — APPROVED** [review]
Thanks @felixarntz changes look good

File: tests/load-tests.php (hunk 3 above)
Comment (mukeshpanchal27) [reply tests/load-tests.php:247]: Thanks for checking. Working now.

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @felixarntz, LGTM!

**Review by merkys7 — APPROVED** [review]
