### PR TITLE
Fix unpredictable LCP element being identified in a URL Metric Group

### LINKED ISSUE #1896: Common LCP element `IMG` not resulting in single preload `LINK`
## Bug Description

In looking at my site, I have tried populating all the URL Metrics for the [homepage](https://weston.ruter.net/) to the point where a common LCP element was reported for all viewports (via [OD Admin UI](https://github.com/westonruter/od-admin-ui)) (disregard the erroneous phablet label for tablet):

> Image

Nevertheless, when I looked at the first post's `IMG` (the LCP element), I saw unexpectedly that `fetchpriority="high"` was not added:

```html
<img
  data-od-removed-fetchpriority="high"
  data-od-replaced-sizes="(max-width: 1200px) 100vw, 1200px"
  data-od-xpath="/HTML/BODY/DIV[@class='wp-site-blocks']/*[2][self::MAIN]/*[2][self::DIV]/*[1][self::UL]/*[1][self::LI]/*[1][self::DIV]/*[1][self::FIGURE]/*[1][self::A]/*[1][self::IMG]"
  width="1200"
  height="675"
  src="https://weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond-1200x675.png"
  class="attachment-post-thumbnail size-post-thumbnail wp-post-image"
  alt="Boosting Performance with Optimization Detective"
  style="width: 100%; height: 100%; object-fit: cover"
  decoding="async"
  srcset="
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1200%2C675&amp;ssl=1  1200w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=300%2C169&amp;ssl=1    300w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=700%2C394&amp;ssl=1    700w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=768%2C432&amp;ssl=1    768w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1536%2C864&amp;ssl=1  1536w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=2048%2C1152&amp;ssl=1 2048w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1980%2C1114&amp;ssl=1 1980w,
    https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=150%2C84&amp;ssl=1     150w
  "
  sizes="(width <= 480px) 300px, (480px < width <= 600px) 455px, (600px < width <= 782px) 644px, (782px < width) 645px"
>
```

However, I see that two preload links were added which were identical except for the viewport ranges:

```html
<link data-od-added-tag rel="preload" fetchpriority="high" as="image" href="https://weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond-1200x675.png" imagesrcset="https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1200%2C675&amp;ssl=1 1200w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=300%2C169&amp;ssl=1 300w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=700%2C394&amp;ssl=1 700w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=768%2C432&amp;ssl=1 768w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1536%2C864&amp;ssl=1 1536w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=2048%2C1152&amp;ssl=1 2048w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1980%2C1114&amp;ssl=1 1980w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=150%2C84&amp;ssl=1 150w" imagesizes="(width &lt;= 480px) 300px, (480px &lt; width &lt;= 600px) 455px, (600px &lt; width &lt;= 782px) 644px, (782px &lt; width) 645px" media="screen and (width &lt;= 600px)">
<link data-od-added-tag rel="preload" fetchpriority="high" as="image" href="https://weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond-1200x675.png" imagesrcset="https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1200%2C675&amp;ssl=1 1200w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=300%2C169&amp;ssl=1 300w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=700%2C394&amp;ssl=1 700w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=768%2C432&amp;ssl=1 768w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1536%2C864&amp;ssl=1 1536w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=2048%2C1152&amp;ssl=1 2048w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=1980%2C1114&amp;ssl=1 1980w, https://i0.wp.com/weston.ruter.net/wp-content/uploads/2025/02/weston-ruter-beyond.png?resize=150%2C84&amp;ssl=1 150w" imagesizes="(width &lt;= 480px) 300px, (480px &lt; width &lt;= 600px) 455px, (600px &lt; width &lt;= 782px) 644px, (782px &lt; width) 645px" media="screen and (782px &lt; width)">
```

The two ranges are:

* `width <= 600px` (i.e. `max-width: 600px`)
* `782px < width` (i.e. `min-width: 782px`)

So there seems to be a missing preload link for the tablet viewport width.

When looking at all of the URL Metrics, they all have `/HTML/BODY/DIV[@class='wp-site-blocks']/*[2][self::MAIN]/*[2][self::DIV]/*[1][self::UL]/*[1][self::LI]/*[1][self::DIV]/*[1][self::FIGURE]/*[1][self::A]/*[1][self::IMG]` with `isLCP: true`, _except_ for one:

```json
{
    "url": "https://weston.ruter.net/",
    "viewport": {
        "width": 763,
        "height": 662
    },
    "elements": [
        {
            "isLCP": true,
            "isLCPCandidate": true,
            "xpath": "/*[1][self::HTML]/*[2][self::BODY]/*[4][self::MAIN]/*[1][self::ARTICLE]/*[2][self::FIGURE]/*[1][self::DIV]/*[1][self::IMG]",
...
```

This is for the tablet viewport (600px – 782px) and there is one other URL Metric for this viewport:

```json
{
    "url": "https://weston.ruter.net/",
    "viewport": {
        "width": 763,
        "height": 1451
    },
    "elements": [
        {
            "isLCP": true,
            "isLCPCandidate": true,
            "xpath": "/HTML/BODY/DIV[@class='wp-site-blocks']/*[2][self::MAIN]/*[2][self::DIV]/*[1][self::UL]/*[1][self::LI]/*[1][self::DIV]/*[1][self::FIGURE]/*[1][self::A]/*[1][self::IMG]",
            "intersectionRatio": 1
...
```

This seems to explain why tablet is missing a preload link. Nevertheless, I'm confused why both `\OD_URL_Metric_Group_Collection::get_common_lcp_element()` and `\OD_URL_Metric_Group::get_lcp_element()` are returning the same element for all viewport groups, when seemingly `\Image_Prioritizer_Img_Tag_Visitor::add_image_preload_link_for_lcp_element_groups()` is behaving differently. Maybe it has has to do something with  `\OD_URL_Metric_Group_Collection::get_groups_by_lcp_element()` but this needs further investigation.

## Steps to reproduce

1. Fully populate the homepage of a site with URL metrics running the Twenty Twenty theme, where there is a post with featured image that is the LCP element.
2. Switch the theme to something else (e.g. Twenty Twenty-Five) so the XPath differ.
3. Fully populate the URL Metrics for mobile, phablet, and desktop and only _one_ of phablet.
4. See unexpected results (hopefully).

### PR DESCRIPTION
**Pull request by westonruter**
## Summary

Fixes #1896
See #1902

## Relevant technical choices

Now `\OD_URL_Metric_Group::get_lcp_element()` will prefer to use URL Metrics which have a current ETag. If there are none, then it falls back to using all of the stale URL Metrics. This ensures that if a URL Metric group has two URL Metrics, one with a mismatched ETag and another with an ETag that matches the current ETag, that the logic will not possibly result in the LCP element being pulled from the URL Metric with the stale ETag, which can currently happen if there are an equal number of stale and fresh URL Metrics in a group.

### CODE REVIEW

File: plugins/optimization-detective/class-od-url-metric-group.php [hunk 1]
```diff
@@ -360,7 +360,20 @@ public function get_lcp_element(): ?OD_Element {
...
+					return $url_metric->get_etag() === $this->get_collection()->get_current_etag();
+				}
+			);
+
+			// Otherwise, if no URL Metrics have a current ETag, fall back to using all the stale ones.
+			if ( count( $url_metrics ) === 0 ) {
+				$url_metrics = $this->url_metrics;
+			}
+
+			foreach ( $url_metrics as $url_metric ) {
```
Comment (westonruter) [inline plugins/optimization-detective/class-od-url-metric-group.php:376]: This is the only actual plugin code change. Everything else is for tests.

File: plugins/optimization-detective/tests/test-class-od-url-metrics-group.php [hunk 2]
```diff
@@ -417,6 +417,84 @@ public function test_get_lcp_element( array $breakpoints, array $url_metrics, ar
...
+	 * Test get_lcp_element() when half of the URL Metrics in a group are stale.
+	 *
+	 * @covers ::get_lcp_element
+	 * @covers OD_URL_Metric_Group_Collection::get_common_lcp_element
+	 * @dataProvider data_provider_test_get_lcp_element_when_group_half_stale
+	 *
+	 * @param bool $order_reversed Whether the order of URL Metrics should be reversed.
+	 */
+	public function test_get_lcp_element_when_group_half_stale( bool $order_reversed ): void {
+		$current_etag = 'f8527651f96776745f88cc49df70b62d';
```
Comment (felixarntz) [inline plugins/optimization-detective/tests/test-class-od-url-metrics-group.php]: Maybe read this from any of the elements in the fixture data instead of hard-coding?

File: bin/test-php-watch.sh [hunk 3]
```diff
@@ -13,5 +13,5 @@ while true; do
 	echo "Running phpunit tests for $(tput bold)$plugin_slug$(tput sgr0):"
 	# TODO: Interrupt when a change is made while running tests or re-run if change made since tests started running.
 	# Note: This is calling phpunit directly and not the composer script due to extra noise it outputs.
-	npm run wp-env --silent -- run tests-cli --env-cwd=/var/www/html/wp-content/plugins/performance -- vendor/bin/phpunit --testsuite "$plugin_slug" "$@"
+	npm run wp-env --silent -- run tests-cli --env-cwd=/var/www/html/wp-content/plugins/performance -- vendor/bin/phpunit --testsuite "$plugin_slug" --verbose "$@"
```
Comment (felixarntz) [inline bin/test-php-watch.sh]: Why is this changed here? Mostly asking since it'll affect all plugins.

**Review by felixarntz — COMMENTED** [review]
@westonruter This mostly looks good, just two points of feedback.

File: bin/test-php-watch.sh (hunk 3 above)
Comment (westonruter) [reply bin/test-php-watch.sh]: I added it because without `--verbose` the messages communicated by `markTestIncomplete()` are not printed:

https://github.com/WordPress/performance/blob/db322a37e675aeea54db7afba8a31ac0c40e6393/plugins/optimization-detective/tests/class-optimization-detective-test-helpers.php#L318-L319

However, I just realized this can still be passed as extra args:

```
npm run test-php-watch  -- --verbose
```

So I've reverted this.

File: plugins/optimization-detective/tests/test-class-od-url-metrics-group.php (hunk 2 above)
Comment (westonruter) [reply plugins/optimization-detective/tests/test-class-od-url-metrics-group.php]: I've addressed this in b96df7cfa by finding the ETag that is used most often as the one which is the current ETag.

**Review by felixarntz — APPROVED** [review]
@westonruter Thanks for the updates, LGTM!
