### PR TITLE
Fix missing `PICTURE` element support for post thumbnail and add missing Modern Image Formats support for Widget Block

### LINKED ISSUE #2178: Modern Image Formats - post thumbnail dont follow picture element
No others plugins installed, only Modern Image Formats with settings

AVIF - Generate images in this format 
✓ Also generate fallback images in the original upload format 
✓ Generate all fallback image sizes including custom sizes
✓ Use < picture > Element (experimental)

in php call 

`
    <?php the_post_thumbnail( 'medium_large' ); ?>
`

`
    Deserunt reprehenderit minim
    `

**Shouldn't it also be in the picture element with a source tag?**
Thank you

### PR DESCRIPTION
**Pull request by b1ink0**
## Summary

Fixes #2178 

## Relevant technical choices

This PR fixes the `webp_uploads_update_featured_image` function not outputting the `<picture>` element for featured image when the experimental picture element setting is enabled.

Also fixes a issue where image blocks used inside widgets (like Image and Gallery blocks) weren’t getting replaced with modern formats.

### CODE REVIEW

**Comment by adamsilverstein** [comment]
@b1ink0 Code looks good, lets get some wider testing before landing. 

This PR also fixes the problem with working in image widgets (etc) - can you please update the description to include that?

File: plugins/webp-uploads/picture-element.php [hunk 1]
```diff
@@ -19,7 +19,7 @@
  * @return string The new image tag.
  */
 function webp_uploads_wrap_image_in_picture( string $image, string $context, int $attachment_id ): string {
-	if ( 'the_content' !== $context ) {
+	if ( ! in_array( $context, array( 'the_content', 'post_thumbnail_html', 'widget_block_content' ), true ) ) {
```
Comment (b1ink0) [inline plugins/webp-uploads/picture-element.php:22]: As mentioned https://github.com/WordPress/performance/issues/2178#issuecomment-3303291033, I also added `widget_block_content` for testing the widgets. From my testing, adding `widget_block_content` as a context solves the issue for widgets. Should this be handled in a separate PR?

Comment (b1ink0) [reply plugins/webp-uploads/picture-element.php:22]: Nevermind see https://github.com/WordPress/performance/pull/2179#issuecomment-3313170815.

Comment (adamsilverstein) [reply plugins/webp-uploads/picture-element.php:22]: ~probably, since its a separate issue entirely!~

Comment (adamsilverstein) [reply plugins/webp-uploads/picture-element.php:22]: Ha! Cross path. Its fine to include in a single PR since the changes are tiny and its a bunch of extra work to add additional Issue and PR.

Comment (b1ink0) [reply plugins/webp-uploads/picture-element.php:22]: Okay, I’ll update this PR then.

File: plugins/webp-uploads/hooks.php [hunk 2]
```diff
@@ -673,6 +673,9 @@ function webp_uploads_img_tag_update_mime_type( string $original_image, string $
  * @return string The updated HTML markup.
  */
 function webp_uploads_update_featured_image( string $html, int $post_id, int $attachment_id ): string {
+	if ( webp_uploads_is_picture_element_enabled() ) {
+		return webp_uploads_wrap_image_in_picture( $html, 'post_thumbnail_html', $attachment_id );
+	}
 	return webp_uploads_img_tag_update_mime_type( $html, 'post_thumbnail_html', $attachment_id );
 }
 add_filter( 'post_thumbnail_html', 'webp_uploads_update_featured_image', 10, 3 );
```
Comment (b1ink0) [inline plugins/webp-uploads/hooks.php:681]: >And, right now we are using the `post_thumbnail_html` filter for the featured image, but we could use the `wp_get_attachment_image` filter as the bug reporter suggested. However, this filter would also include any image echoed using the `wp_get_attachment_image()` function, which is used for featured images and is also typically used by other plugins. So, I'm not sure whether the Modern Image Formats plugin should also handle those images.

@adamsilverstein what do you think about this?

Comment (adamsilverstein) [reply plugins/webp-uploads/hooks.php:681]: lets avoid altering other plugin output for now, the unexpected change could break things or cause conflicts.

**Review by westonruter — APPROVED** [review]
This seems to work with my testing. A diff from `trunk`:

```diff
--- before.html	2025-09-25 15:44:24
+++ after.html	2025-09-25 15:44:26
@@ -2518,24 +2518,35 @@
             style="aspect-ratio: 3/2"
             class="wp-block-post-featured-image"
           >
-            <img
-              width="1200"
-              height="1594"
-              src="http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-jpg.webp"
-              class="attachment-post-thumbnail size-post-thumbnail wp-post-image"
-              alt=""
-              style="width: 100%; height: 100%; object-fit: cover"
-              decoding="async"
-              fetchpriority="high"
-              srcset="
-                http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-jpg.webp           1200w,
-                http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-226x300-jpg.webp    226w,
-                http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-771x1024-jpg.webp   771w,
-                http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-768x1020-jpg.webp   768w,
-                http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-1156x1536-jpg.webp 1156w
-              "
-              sizes="(max-width: 1200px) 100vw, 1200px"
-            />
+            <picture class="wp-picture-437" style="display: contents"
+              ><source
+                type="image/webp"
+                srcset="
+                  http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-jpg.webp           1200w,
+                  http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-226x300-jpg.webp    226w,
+                  http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-771x1024-jpg.webp   771w,
+                  http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-768x1020-jpg.webp   768w,
+                  http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-1156x1536-jpg.webp 1156w
+                "
+                sizes="(max-width: 1200px) 100vw, 1200px" />
+              <img
+                width="1200"
+                height="1594"
+                src="http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px.jpg"
+                class="attachment-post-thumbnail size-post-thumbnail wp-post-image"
+                alt=""
+                style="width: 100%; height: 100%; object-fit: cover"
+                decoding="async"
+                fetchpriority="high"
+                srcset="
+                  http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px.jpg           1200w,
+                  http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-226x300.jpg    226w,
+                  http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-771x1024.jpg   771w,
+                  http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-768x1020.jpg   768w,
+                  http://localhost:8000/wp-content/uploads/2025/09/Heimdall-PXL_20250919_195438368.MP-1200px-1156x1536.jpg 1156w
+                "
+                sizes="(max-width: 1200px) 100vw, 1200px"
+            /></picture>
           </figure>
 
           <div class="wp-block-post-date">

```

File: plugins/webp-uploads/tests/test-picture-element.php [hunk 3]
```diff
@@ -526,4 +526,62 @@ public function test_wrap_image_in_picture_with_false_image_src(): void {
...
+			array(
+				'class' => 'wp-image-' . self::$image_id,
+				'alt'   => 'Green Leaves',
+			)
+		);
+
+		$this->opt_in_to_picture_element();
+		$filtered_image = apply_filters( 'wp_content_img_tag', $image, $context, self::$image_id );
+		if ( $expected ) {
+			$this->assertStringStartsWith( '<picture', $filtered_image );
```
Comment (westonruter) [inline plugins/webp-uploads/tests/test-picture-element.php]: Better to use the HTML Tag Processor here.

```suggestion
			$p = new WP_HTML_Tag_Processor( $filtered_image );
			$this->assertTrue( $p->next_tag() );
			$this->assertSame( 'PICTURE', $p->get_tag() );
			$this->assertTrue( $p->next_tag() );
			$this->assertSame( 'SOURCE', $p->get_tag() );
			$this->assertTrue( $p->next_tag() );
			$this->assertSame( 'IMG', $p->get_tag() );
```

File: plugins/webp-uploads/tests/test-load.php [hunk 4]
```diff
@@ -1268,4 +1268,44 @@ static function () {
 		);
 		$this->assertSameSets( $file, webp_uploads_convert_palette_png_to_truecolor( $file ) );
 	}
+
+	/**
+	 * Test that the webp_uploads_update_featured_image function is hooked to the post_thumbnail_html filter.
+	 *
+	 * @covers ::webp_uploads_update_featured_image
```
Comment (westonruter) [inline plugins/webp-uploads/tests/test-load.php]: This doesn't actually test the function, but rather just that the filter is present. This filter is added outside of any function.
