### PR TITLE
Use modern image formats in background images for Cover blocks and Group blocks

### LINKED ISSUE #2111: Modern image formats not used for fixed background image in Cover Block
## Bug Description

If you create a Cover Block and add an image with a fixed background, the image is not replaced with AVIF/WebP when the block is rendered on the frontend. The original JPEG (or other) format is used.

These images are especially important to have a modern image format used, because there is no `srcset` to reduce the size.

## Steps to reproduce

1. Enable Modern Image Formats.
2. Upload an image to the media library so that it generates a modern image format.
3. Add a Cover Block.
4. Add the uploaded image to the Cover block.
5. Enable "fixed background" in the Cover block's settings.
6. View the Cover block on the frontend and see that the modern image format is not used.

### Cover Block Markup

```html
<div
  class="wp-block-cover alignwide is-light has-parallax"
  style="border-radius: 100px"
>
  <div
    class="wp-block-cover__image-background wp-image-8 size-large has-parallax"
    style="
      background-position: 50% 50%;
      background-image: url(https://wcus-perf-talk-demo.local/wp-content/uploads/2025/06/American_bison_k5680-1-1024x668.jpg);
    "
  ></div>
  <span
    aria-hidden="true"
    class="wp-block-cover__background has-background-dim"
    style="background-color: #93825b"
  ></span>
  <div
    class="wp-block-cover__inner-container has-global-padding is-layout-constrained wp-block-cover-is-layout-constrained"
  >
    <h2
      class="wp-block-heading has-text-align-center has-base-color has-accent-6-background-color has-text-color has-background has-link-color has-xx-large-font-size wp-elements-f7ac82b376aa52ed5a9058a4e2fb6f3e"
      style="border-radius: 100px"
    >
      <strong>Bison</strong> 🦬
    </h2>
  </div>
</div>
```

### Image Block Markup

This is using the same underlying image, and it is successfully rendered as AVIF:

```html
<figure class="wp-block-image size-large">
  <img
    loading="lazy"
    decoding="async"
    width="1024"
    height="668"
    src="https://wcus-perf-talk-demo.local/wp-content/uploads/2025/06/American_bison_k5680-1-1024x668-jpg.avif"
    alt=""
    class="wp-image-8"
    srcset="
      https://wcus-perf-talk-demo.local/wp-content/uploads/2025/06/American_bison_k5680-1-1024x668-jpg.avif  1024w,
      https://wcus-perf-talk-demo.local/wp-content/uploads/2025/06/American_bison_k5680-1-300x196-jpg.avif    300w,
      https://wcus-perf-talk-demo.local/wp-content/uploads/2025/06/American_bison_k5680-1-768x501-jpg.avif    768w,
      https://wcus-perf-talk-demo.local/wp-content/uploads/2025/06/American_bison_k5680-1-1536x1002-jpg.avif 1536w,
      https://wcus-perf-talk-demo.local/wp-content/uploads/2025/06/American_bison_k5680-1-2048x1336-jpg.avif 2048w
    "
    sizes="auto, (max-width: 1024px) 100vw, 1024px"
  />
</figure>
```

### PR DESCRIPTION
**Pull request by vipul0425**
## Summary

Fixes https://github.com/WordPress/performance/issues/2111

## Relevant technical choices

Adds functionality to process background images used in Cover and Group blocks, particularly for cases with special styling options like fixed or repetitive backgrounds. Our current approach was limited to only processing `` tags in content, but this missed background images applied through inline CSS styles.

When users set specific styling options in Cover blocks (such as fixed backgrounds) or Group blocks with background images, these images are added via inline styles rather than standard `` tags. As a result, these images weren't being converted to modern formats.

### CODE REVIEW

File: plugins/webp-uploads/hooks.php [hunk 1]
```diff
@@ -747,13 +747,84 @@ function webp_uploads_render_generator(): void {
...
+		$image_url     = isset( $block['attrs']['url'] ) ? $block['attrs']['url'] : '';
+	}
+
+	// Process Group block with background image.
+	if ( 'core/group' === $block['blockName'] && isset( $block['attrs']['style']['background']['backgroundImage'] ) ) {
+		$bg_image = $block['attrs']['style']['background']['backgroundImage'];
+
+		if ( isset( $bg_image['id'] ) ) {
+			$attachment_id = $bg_image['id'];
+			$image_url     = isset( $bg_image['url'] ) ? $bg_image['url'] : '';
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]:
```suggestion
			$image_url     = $bg_image['url'] ?? '';
```

File: plugins/webp-uploads/hooks.php [hunk 2]
```diff
@@ -747,13 +747,84 @@ function webp_uploads_render_generator(): void {
...
+		return $block_content;
+	}
+
+	$attachment_id = null;
+	$image_url     = '';
+
+	// Process Cover block.
+	if ( 'core/cover' === $block['blockName'] && isset( $block['attrs']['id'] ) ) {
+		$attachment_id = $block['attrs']['id'];
+		$image_url     = isset( $block['attrs']['url'] ) ? $block['attrs']['url'] : '';
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]:
```suggestion
		$image_url     = $block['attrs']['url'] ?? '';
```

File: plugins/webp-uploads/hooks.php [hunk 3]
```diff
@@ -747,13 +747,84 @@ function webp_uploads_render_generator(): void {
 }
 add_action( 'wp_head', 'webp_uploads_render_generator' );
 
+/**
+ * Process a block's content to handle background images for specific block types.
+ *
+ * This function targets blocks like Cover and Group that may use background images,
+ * converting them to modern image formats when appropriate.
+ *
+ * @since n.e.x.t
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php:756]: We can add more specific typing for this arg:

```suggestion
 * @since n.e.x.t
 *
 * @phpstan-param array{
 *                    blockName: string|null,
 *                    attrs: array{
 *                        id?: positive-int,
 *                        url?: string,
 *                        style?: array{
 *                            background?: array{
 *                                backgroundImage?: string
 *                            }
 *                        }
 *                    }
 *                } $block
```

File: plugins/webp-uploads/hooks.php [hunk 4]
```diff
@@ -747,13 +747,84 @@ function webp_uploads_render_generator(): void {
...
+ *
+ * @param string               $block_content The block content.
+ * @param array<string, mixed> $block         The block.
+ * @return string The filtered block content.
+ */
+function webp_uploads_filter_block_background_images( string $block_content, array $block ): string {
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]: Since plugins can filter this value to be anything, it's not safe to add a PHP type hint since a fatal error could happen. So it's better to allow for `mixed`:

```suggestion
 * @param string|mixed         $block_content The block content.
 * @param array<string, mixed> $block         The block.
 * @return string The filtered block content.
 */
function webp_uploads_filter_block_background_images( $block_content, array $block ): string {
	// Because plugins can do bad things.
	if ( ! is_string( $block_content ) ) {
		$block_content = '';
	}

```

File: plugins/webp-uploads/hooks.php [hunk 5]
```diff
@@ -747,13 +747,84 @@ function webp_uploads_render_generator(): void {
...
+	}
+
+	// If we have a valid attachment and URL, process it.
+	if ( ! is_null( $attachment_id ) && '' !== $image_url ) {
+		$metadata = wp_get_attachment_metadata( $attachment_id );
+
+		if ( is_array( $metadata ) ) {
+			$original_mime = get_post_mime_type( $attachment_id );
+
+			if ( null !== $original_mime && '' !== $original_mime ) {
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]: The `get_post_mime_type()` function is supposed to return `string|false`, so shouldn't this be:

```suggestion
			if ( is_string( $original_mime ) {
```

File: plugins/webp-uploads/hooks.php [hunk 6]
```diff
@@ -747,13 +747,84 @@ function webp_uploads_render_generator(): void {
...
+				$target_mimes = webp_uploads_get_content_image_mimes( $attachment_id, 'background_image' );
+
+				foreach ( $target_mimes as $target_mime ) {
+					if ( $target_mime === $original_mime ) {
+						continue;
+					}
+
+					$new_url = webp_uploads_get_mime_type_image( $attachment_id, $image_url, $target_mime );
+
+					if ( null !== $new_url && '' !== $new_url ) {
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]: I don't think the check for an empty string is needed?

```suggestion
					if ( is_string( $new_url ) ) {
```

Probably a good idea to update `webp_uploads_get_mime_type_image()` so that it is explicitly returning `non-empty-string|null` and to have it return `null` if the the string it returns happens to be empty.

File: plugins/webp-uploads/hooks.php [hunk 7]
```diff
@@ -747,13 +747,84 @@ function webp_uploads_render_generator(): void {
...
+						// Replace the URL in the content.
+						$block_content = str_replace( $image_url, $new_url, $block_content );
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]: I think it would be better to Would this be better to use HTML Tag Processor to do the replacement specifically in the context of the `style` attribute. It could even append the new style property as opposed to doing a replacement, since the later CSS property will override the former. (Maybe a string replacement inside the attribute is still better though.)

Also, shouldn't this `break` the `foreach` loop when a replacement is done?

```suggestion
						$processor = new WP_HTML_Tag_Processor( $block_content );
						while ( $processor->next_tag() ) {
							$style = $processor->get_attribute( 'style' );
							if ( is_string( $style ) && str_contains( 'background-image:', $style ) && str_contains( $image_url, $style ) ) {
								$style .= sprintf( 'background-image: url( "%s" );', $new_url );
								$processor->set_attribute( 'style', $style );
								$block_content = $processor->get_updated_html();
								break 2;
							}
						}
```

File: plugins/webp-uploads/hooks.php [hunk 8]
```diff
@@ -747,13 +747,84 @@ function webp_uploads_render_generator(): void {
...
+			$attachment_id = $bg_image['id'];
+			$image_url     = isset( $bg_image['url'] ) ? $bg_image['url'] : '';
+		}
+	}
+
+	// If we have a valid attachment and URL, process it.
+	if ( ! is_null( $attachment_id ) && '' !== $image_url ) {
+		$metadata = wp_get_attachment_metadata( $attachment_id );
+
+		if ( is_array( $metadata ) ) {
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]: The `$metadata` variable is unused except to see if it is an array. It seems like the condition could be removed, or else combined:

```suggestion
	if ( ! is_null( $attachment_id ) && '' !== $image_url && is_array( wp_get_attachment_metadata( $attachment_id ) ) ) {
```

File: plugins/webp-uploads/hooks.php [hunk 9]
```diff
@@ -747,13 +747,84 @@ function webp_uploads_render_generator(): void {
...
+	// Process Group block with background image.
+	if ( 'core/group' === $block['blockName'] && isset( $block['attrs']['style']['background']['backgroundImage'] ) ) {
+		$bg_image = $block['attrs']['style']['background']['backgroundImage'];
+
+		if ( isset( $bg_image['id'] ) ) {
+			$attachment_id = $bg_image['id'];
+			$image_url     = isset( $bg_image['url'] ) ? $bg_image['url'] : '';
+		}
+	}
+
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php:800]: Some of the nested conditions could be removed by adding two `if` statements up before:

```suggestion

	// Abort if there is no associated background image, since there will be no replacement.
	if ( is_null( $attachment_id ) || '' === $image_url ) {
		return $block_content;
	}
	$original_mime = get_post_mime_type( $attachment_id );
	if ( ! is_string( $original_mime ) ) {
		return $block_content;
	}

```

**Review by westonruter — CHANGES_REQUESTED** [review]
Thanks for working on this!

File: plugins/webp-uploads/helper.php [hunk 10]
```diff
@@ -471,11 +472,12 @@ function webp_uploads_get_mime_type_image( int $attachment_id, string $src, stri
 				continue;
 			}
 
-			return str_replace(
+			$result = str_replace(
 				$size_data['file'],
 				$size_data['sources'][ $mime ]['file'],
 				$src
 			);
+			return '' === $result ? null : $result;
```
Comment (westonruter) [inline plugins/webp-uploads/helper.php:480]: Don't forget to update the `@return` tag for `webp_uploads_get_mime_type_image()` to be `non-empty-string|null`

Comment (vipul0425) [reply plugins/webp-uploads/helper.php:480]: Sorry missed that 😅

File: plugins/webp-uploads/hooks.php [hunk 11]
```diff
@@ -747,13 +747,112 @@ function webp_uploads_render_generator(): void {
...
+				$style = $processor->get_attribute( 'style' );
+
+				if ( is_string( $style ) && str_contains( $style, 'background-image:' ) && str_contains( $style, $image_url ) ) {
+					$updated_style = str_replace( $image_url, $new_url, $style );
+					$processor->set_attribute( 'style', $updated_style );
+					$block_content = $processor->get_updated_html();
+					break 2;
+				}
+			}
+		}
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]: For consistency with the use of `continue` above.

```suggestion
		if ( ! is_string( $new_url ) ) {
			continue;
		}

		$processor = new WP_HTML_Tag_Processor( $block_content );
		while ( $processor->next_tag() ) {
			$style = $processor->get_attribute( 'style' );

			if ( is_string( $style ) && str_contains( $style, 'background-image:' ) && str_contains( $style, $image_url ) ) {
				$updated_style = str_replace( $image_url, $new_url, $style );
				$processor->set_attribute( 'style', $updated_style );
				$block_content = $processor->get_updated_html();
				break 2;
			}
		}
```

**Review by westonruter — CHANGES_REQUESTED** [review]
This is getting close! The main thing left, other than the two minor suggestions I left, is to add PHPUnit tests for this new `webp_uploads_filter_block_background_images()` function.

**Comment by vipul0425** [comment]
Thanks @westonruter for the detailed review. I'll add the test cases and update the PR. 🙇

File: plugins/webp-uploads/hooks.php [hunk 12]
```diff
@@ -747,13 +747,113 @@ function webp_uploads_render_generator(): void {
...
+	}
+
+	// Abort if there is no associated background image.
+	if ( is_null( $attachment_id ) || '' === $image_url || ! is_array( wp_get_attachment_metadata( $attachment_id ) ) ) {
+		return $block_content;
+	}
+
+	$original_mime = get_post_mime_type( $attachment_id );
+
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]:
```suggestion
```

File: plugins/webp-uploads/hooks.php [hunk 13]
```diff
@@ -747,13 +747,113 @@ function webp_uploads_render_generator(): void {
...
+	$target_mimes = webp_uploads_get_content_image_mimes( $attachment_id, 'background_image' );
+
+	foreach ( $target_mimes as $target_mime ) {
+		if ( $target_mime === $original_mime ) {
+			continue;
+		}
+
+		$new_url = webp_uploads_get_mime_type_image( $attachment_id, $image_url, $target_mime );
+
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]:
```suggestion
```

File: plugins/webp-uploads/hooks.php [hunk 14]
```diff
@@ -747,13 +747,113 @@ function webp_uploads_render_generator(): void {
...
+	// Process Cover block.
+	if ( 'core/cover' === $block['blockName'] && isset( $block['attrs']['id'] ) ) {
+		$attachment_id = $block['attrs']['id'];
+		$image_url     = $block['attrs']['url'] ?? '';
+	}
+
+	// Process Group block with background image.
+	if ( 'core/group' === $block['blockName'] && isset( $block['attrs']['style']['background']['backgroundImage'] ) ) {
+		$bg_image = $block['attrs']['style']['background']['backgroundImage'];
+
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]:
```suggestion
```

File: plugins/webp-uploads/hooks.php [hunk 15]
```diff
@@ -747,13 +747,113 @@ function webp_uploads_render_generator(): void {
...
+		$new_url = webp_uploads_get_mime_type_image( $attachment_id, $image_url, $target_mime );
+
+		if ( ! is_string( $new_url ) ) {
+			continue;
+		}
+
+		$processor = new WP_HTML_Tag_Processor( $block_content );
+		while ( $processor->next_tag() ) {
+			$style = $processor->get_attribute( 'style' );
+
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]:
```suggestion
```

**Review by westonruter — COMMENTED** [review]
Some micro nits to reduce extra newlines where they don't seem needed.

File: plugins/webp-uploads/hooks.php [hunk 16]
```diff
@@ -747,13 +747,109 @@ function webp_uploads_render_generator(): void {
...
+		if ( isset( $bg_image['id'] ) ) {
+			$attachment_id = $bg_image['id'];
+			$image_url     = $bg_image['url'] ?? '';
+		}
+	}
+
+	// Abort if there is no associated background image.
+	if ( is_null( $attachment_id ) || '' === $image_url || ! is_array( wp_get_attachment_metadata( $attachment_id ) ) ) {
+		return $block_content;
+	}
```
Comment (westonruter) [inline plugins/webp-uploads/hooks.php]: What about this refactor for a bit more hardening?

```suggestion
	$attachment_id = null;
	$image_url     = null;

	if ( 'core/cover' === $block['blockName'] ) {
		if ( isset( $block['attrs']['id'], $block['attrs']['url'] ) ) {
			$attachment_id = $block['attrs']['id'];
			$image_url     = $block['attrs']['url'];
		}
	} elseif ( 'core/group' === $block['blockName'] ) {
		if ( isset( $block['attrs']['style']['background']['backgroundImage']['id'], $block['attrs']['style']['background']['backgroundImage']['url'] ) ) {
			$attachment_id = $block['attrs']['style']['background']['backgroundImage']['id'];
			$image_url     = $block['attrs']['style']['background']['backgroundImage']['url'];
		}
	}

	// Abort if there is no associated background image.
	if (
		! isset( $attachment_id, $image_url ) ||
		$attachment_id <= 0 ||
		'' === $image_url ||
		! is_array( wp_get_attachment_metadata( $attachment_id ) )
	) {
		return $block_content;
	}
```

File: plugins/webp-uploads/tests/test-block-background-images.php [hunk 17]
```diff
@@ -0,0 +1,178 @@
...
+			$block_content = '<div class="wp-block-cover"><div style="background-image:url(' . esc_url( $original_url ) . ')"><span class="wp-block-cover__inner-container">' . esc_html( $content ) . '</span></div></div>';
+			$block         = array(
+				'blockName' => 'core/cover',
+				'attrs'     => array(
+					'id'  => $attachment_id,
+					'url' => $original_url,
+				),
+			);
+		} elseif ( 'core/group' === $block_name ) {
+			$block_content = '<div class="wp-block-group" style="background-image:url(' . esc_url( $original_url ) . ')"><div class="wp-block-group__inner-container">' . esc_html( $content ) . '</div></div>';
```
Comment (westonruter) [inline plugins/webp-uploads/tests/test-block-background-images.php]: Looks like `$content` can be removed since it is never supplied as an arg.

```suggestion
	 * @return array{block_content:string,block:array<string,mixed>} Array containing 'block_content' HTML and 'block' parsed block structure.
	 */
	private function generate_block_with_background( string $block_name, int $attachment_id, string $original_url ): array {
		if ( 'core/cover' === $block_name ) {
			$block_content = '<div class="wp-block-cover"><div style="background-image:url(' . esc_url( $original_url ) . ')"><span class="wp-block-cover__inner-container">Content</span></div></div>';
			$block         = array(
				'blockName' => 'core/cover',
				'attrs'     => array(
					'id'  => $attachment_id,
					'url' => $original_url,
				),
			);
		} elseif ( 'core/group' === $block_name ) {
			$block_content = '<div class="wp-block-group" style="background-image:url(' . esc_url( $original_url ) . ')"><div class="wp-block-group__inner-container">Content</div></div>';
```

File: plugins/webp-uploads/tests/test-block-background-images.php [hunk 18]
```diff
@@ -0,0 +1,178 @@
...
+
+		return array(
+			'block_content' => $block_content,
+			'block'         => $block,
+		);
+	}
+
+	/**
+	 * It should replace a Cover block background image URL with a WebP variant when available.
+	 */
```
Comment (westonruter) [inline plugins/webp-uploads/tests/test-block-background-images.php:109]:
```suggestion
	 *
	 * @covers ::webp_uploads_filter_block_background_images
	 */
```

File: plugins/webp-uploads/tests/test-block-background-images.php [hunk 19]
```diff
@@ -0,0 +1,178 @@
...
+		$this->assertNotNull( $webp_url, 'Expected a generated WebP URL.' );
+
+		if ( $webp_url !== $original_url ) {
+			$this->assertStringContainsString( $webp_url, $filtered, 'Filtered markup should reference WebP background image.' );
+		}
+	}
+
+	/**
+	 * It should not change background when no WebP source exists.
+	 */
```
Comment (westonruter) [inline plugins/webp-uploads/tests/test-block-background-images.php:134]:
```suggestion
	 *
	 * @covers ::webp_uploads_filter_block_background_images
	 */
```

File: plugins/webp-uploads/tests/test-block-background-images.php [hunk 20]
```diff
@@ -0,0 +1,178 @@
...
+
+		remove_filter( 'webp_uploads_upload_image_mime_transforms', $filter, 10 );
+
+		$this->assertSame( $generated['block_content'], $filtered, 'Background image should remain unchanged when no WebP source exists.' );
+		$this->assertStringNotContainsString( '-jpg.webp', $filtered );
+	}
+
+	/**
+	 * It should replace a Group block background image URL with a WebP variant when available.
+	 */
```
Comment (westonruter) [inline plugins/webp-uploads/tests/test-block-background-images.php:163]:
```suggestion
	 *
	 * @covers ::webp_uploads_filter_block_background_images
	 */
```

**Review by westonruter — APPROVED** [review]
Thank you!
