### PR TITLE
Include static page for posts for article transitions

### LINKED ISSUE #2305: Article view transition does not apply when using a static page for posts
## Bug Description

This was spurred on by a [support topic](https://wordpress.org/support/topic/cant-see-any-transition/). When testing, I only saw a cross-fade view transition as opposed to seeing the title and featured image for a post in The Loop animate into position for the corresponding elements on the single template. It appears to be due to setting a static pages for the homepage and blog:

Image

If I instead set it so that I see the latest posts on the homepage, then I do see the elements animate into position as expected.

Homepage shows latest posts ✅ | Static page for home and blog ❌
--|--
<video src="https://github.com/user-attachments/assets/c8e49f11-7f3f-4887-9f93-630205ccb0f4"> | <video src="https://github.com/user-attachments/assets/e91f55b8-f2a4-4860-8120-cc8ab1165246">

### PR DESCRIPTION
**Pull request by westonruter**
## Summary

Fixes #2305

When a static page is used for posts:

image

The `BODY` element here is:

```html
<body class="blog wp-embed-responsive wp-theme-twentytwentyfive">
```

However, when showing the latest posts on the homepage, the `BODY` is:

```html
<body class="home blog wp-embed-responsive wp-theme-twentytwentyfive">
```

Currently only the `home` and `archive` class names are accounted for. The `blog` class name, which is the only one shown on a static page for posts, was not. This PR fixes that.

### CODE REVIEW

**Comment by westonruter** [comment]
Build for testing: [view-transitions.zip](https://github.com/user-attachments/files/24250975/view-transitions.zip)

File: plugins/view-transitions/js/view-transitions.js [hunk 1]
```diff
@@ -155,6 +155,7 @@ window.plvtInitViewTransitions = ( config ) => {
 					);
 				} else if (
 					document.body.classList.contains( 'home' ) ||
+					document.body.classList.contains( 'blog' ) ||
```
Comment (mukeshpanchal27) [inline plugins/view-transitions/js/view-transitions.js:158]: Have you check the different `Transition Animation` instead of fade without the changes?

Comment (westonruter) [reply plugins/view-transitions/js/view-transitions.js:158]: No. I didn't make any changes to the settings.

**Review by felixarntz — APPROVED** [review]
@westonruter Great catch!

**Review by mukeshpanchal27 — APPROVED** [review]
